### ISSUE TITLE
http://www.snik.eu/ontology/bb/InformationManagementStaff (http://www.snik.eu/ontology/meta/isResponsibleFor) http://www.snik.eu/ontology/bb/TacticalInformationManagement v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#101]
The edge "http://www.snik.eu/ontology/bb/InformationManagementStaff (http://www.snik.eu/ontology/meta/isResponsibleFor) http://www.snik.eu/ontology/bb/TacticalInformationManagement" is incorrect.

**Details**
Diese Beziehung ist nicht richtig. Das IMStaff kümmert sich zwar um TIM, aber verantwortlich ist nur der CIO

**Comment by AnnaLoerke** [comment]
Verbindung ist aufgrund von anderem Ticket schon gelöscht. Alternative wäre noch "isInvolvedIn"?

**Comment by AlfredWinter** [comment]
nee. so lassen. AW
