### ISSUE TITLE
http://www.snik.eu/ontology/bb/ChiefInformationOfficer (http://www.snik.eu/ontology/meta/isResponsibleFor) http://www.snik.eu/ontology/bb/InformationManagementDepartment v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#102]
The edge "http://www.snik.eu/ontology/bb/ChiefInformationOfficer (http://www.snik.eu/ontology/meta/isResponsibleFor) http://www.snik.eu/ontology/bb/InformationManagementDepartment" is incorrect.

**Details**
Der Beziehungstyp "isResponsibleFor" entspricht hier und überall NICHT dem Meta-Modell: Nach dem MetaModell sind verschiedene ResponsibleFor zu unterscheiden und zwischen zwei Rollen darf es gar keine responsibleFor geben.

**Comment by KonradHoeffner** [comment]
Ich glaube hier sind zwei Fehler:

1. bb:InformationManagementDepartment muss ein EntityType sein, keine Rolle
2. die oben genannte Kante muss vom Typ isResponsibleForEntityType sein.

Ich habe das mal so geändert, falls das nicht so gewünscht ist, dann dieses Ticket bitte nochmal öffnen. Fehler mit falschen responsibleFor werde ich jetzt auch mal generell automatisch beheben.

**Comment by AlfredWinter** [comment]
Die Korrektur hat zu Folgefehlern geführt. Dazu gibt es ein neues Tickt #180
AW
