### ISSUE TITLE
http://www.snik.eu/ontology/bb/EstablishAndPromoteTheStrategicInformationManagementPlan v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#104]
The class http://www.snik.eu/ontology/bb/EstablishAndPromoteTheStrategicInformationManagementPlan has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
eine "uses" Beziehung zu StrategicInformationManagementPlan ergänzen.

**Comment by AnnaLoerke** [comment]
done.
