### ISSUE TITLE
http://www.snik.eu/ontology/bb/StrategicInformationManagementPlan v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#105]
The class http://www.snik.eu/ontology/bb/StrategicInformationManagementPlan has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Bitte (inverse) relation "uses" von TacticalHISPlaning, TacticalHISDirecting und TacticalHISMonitoring zu diesem Begriff einführen

**Comment by AnnaLoerke** [comment]
done.
