### ISSUE TITLE
http://www.snik.eu/ontology/bb/ReportToTheCEO v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#106]
The class http://www.snik.eu/ontology/bb/ReportToTheCEO has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Der Name suggeriert einen EntityType. Namen umändern in "ReportingToTheCEO"

**Comment by KonradHoeffner** [comment]
Erledigt.
