### ISSUE TITLE
CIOx-Ontologie

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#107]
dcterms:source

Wir hatten gesagt, dass bei den Elementen der CIOx-Ontologie die Quelle anzugeben ist. Nun habe ich bei zumindest einem Element gesehen  dcterms:source: ...Kücherer. Das meine ich nicht als Quelle. Die Quelle ist der CIO des UK-Leipzig. Das hätte ich auch gerne als gut lesbaren Kommentartext: "Quelle: Interview mit dem CIO des Universitätsklinikums Leipzig im Jahr 2016". bzw. auf englisch.
Eine solche gut lesbare und leicht verständliche Quellenangabe hätte ich auch gerne für bb, ob, he, ...

**Comment by KonradHoeffner** [comment]
Das waren die manuell von Christian Kücherer hinzugefügten Tripel, die sie separat markiert haben wollten. Die Quellenangabe der Subtontologien ist nicht in jedem Tripel enthalten, um Platz zu sparen.
Die von http://www.snik.eu/ontology/ciox ist z.B.:

> Based on interviews about the Health Information System with Department B1, the Department for Information Management, of the Uniklinikum Leipzig.

**Comment by AlfredWinter** [comment]
Ok. Habe ich verstanden. (Aber ich fürchte, das werde ich irgendwann noch mal fragen – bitte nicht böse sein). 
AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      ++49 341-97-16107, 
Mobile: ++49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Konrad Höffner [mailto:notifications@github.com] 
Gesendet: Freitag, 23. Juni 2017 15:58
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-ontology] CIOx-Ontologie (#107)
 
Das waren die manuell von Christian Kücherer hinzugefügten Tripel, die sie separat markiert haben wollten. Die Quellenangabe der Subtontologien ist nicht in jedem Tripel enthalten, um Platz zu sparen.
Die von http://www.snik.eu/ontology/ciox ist z.B.:
Based on interviews about the Health Information System with Department B1, the Department for Information Management, of the Uniklinikum Leipzig.

**Comment by KonradHoeffner** [comment]
Kein Problem :-)
