### ISSUE TITLE
http://www.snik.eu/ontology/ciox/ChiefInformationOfficer v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#108]
The class http://www.snik.eu/ontology/ciox/ChiefInformationOfficer has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
close match zu ChiefInformationOfficer in ob ergänzen

**Comment by AnnaLoerke** [comment]
schon vorhanden.
