### ISSUE TITLE
http://www.snik.eu/ontology/ciox/Projektewarteliste v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#110]
The class http://www.snik.eu/ontology/ciox/Projektewarteliste has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Bitte englisches label ergänzen: "project waitlist"

**Comment by AnnaLoerke** [comment]
done
