### ISSUE TITLE
http://www.snik.eu/ontology/ciox/CABDurchfuehrung v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#111]
The class http://www.snik.eu/ontology/ciox/CABDurchfuehrung has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
englisches label ergänzen: "CAB execution"

**Comment by AnnaLoerke** [comment]
done
