### ISSUE TITLE
http://www.snik.eu/ontology/bb/HospitalStaff v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#113]
The class http://www.snik.eu/ontology/bb/HospitalStaff has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
auch subclassof-Beziehung zu bb/ChiefInformationOfficer ergänzen.

**Comment by KonradHoeffner** [comment]
Erledigt.
