### ISSUE TITLE
http://www.snik.eu/ontology/bb/InformationManagementBoard (http://www.w3.org/2000/01/rdf-schema#subClassOf) http://www.snik.eu/ontology/bb/HisStakeholder v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#114]
The edge "http://www.snik.eu/ontology/bb/InformationManagementBoard (http://www.w3.org/2000/01/rdf-schema#subClassOf) http://www.snik.eu/ontology/bb/HisStakeholder" is incorrect.

**Details**
Das ist keine Subclassof-Beziehung. Der IMB setzt sich aus verschiedenen HIS-stakeholdern zusammen. isDecomposedIn???

**Comment by KonradHoeffner** [comment]
Ist bereits so modelliert jetzt, das hat wohl schon jemand behoben, ohne die issue zu aktualisieren.
