### ISSUE TITLE
http://www.snik.eu/ontology/bb/IncidentManagement v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#118]
The class http://www.snik.eu/ontology/bb/IncidentManagement has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Bitte closeMatch zu CIOX:IncidentManagement ergänzen

**Comment by AnnaLoerke** [comment]
Done.
