### ISSUE TITLE
http://www.snik.eu/ontology/ob/ManagementOfInformationSystems v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#119]
The class http://www.snik.eu/ontology/ob/ManagementOfInformationSystems has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
(1) Bitte ergänzen: CloseMatch zu http://www.snik.eu/ontology/bb/InformationManagement 
(2) dieser Begriff ist identisch mit http://www.snik.eu/ontology/ob/InformationManagement. Da beide aus demselben Buch stammen, müssen diese beiden Begriffe irgendwie verschmolzen werden.

**Comment by KonradHoeffner** [comment]
Bereits gemerged wegen issue https://github.com/IMISE/snik-ontology/issues/120, dadurch ist jetzt auch ein closematch zu bb:InformationManagement drin.
