### ISSUE TITLE
http://www.snik.eu/ontology/ob/ManagementOfInformationSystems (http://www.w3.org/2000/01/rdf-schema#subClassOf) http://www.snik.eu/ontology/ob/InformationManagement v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#120]
The edge "http://www.snik.eu/ontology/ob/ManagementOfInformationSystems (http://www.w3.org/2000/01/rdf-schema#subClassOf) http://www.snik.eu/ontology/ob/InformationManagement" is incorrect.

**Details**
diese Beziehung ist falsch. in Wirklichkeit sind beide Begriffe identisch. Es handelt sich nur um zwei unterschiedliche, synonyme labels.

**Comment by KonradHoeffner** [comment]
Habe alle Tripel von ob:ManagementOfInformationSystems nach ob:InformationManagement verschoben. Genauer gesagt: In allen Tripeln, die es als Subjekt oder Objekt haben, dieses ersetzt.
