### ISSUE TITLE
CIOx: URL bei Format-Relation durch Label ersetzen 

### ISSUE THREAD

**Issue by FranziskaJahn** [IMISE/snik-ontology#13]
In der CIOx-Ontologie gibt es die Relation "format". Als Label wird die URL angezeigt, bitte nur die Bezeichnung als Label verwenden.

**Comment by KonradHoeffner** [comment]
CIOx benutzt `dct:format`, daher steht das label nicht in der ciox Ontologie. Ich öffne mal ein Ticket bei der zur Visualisierung, die damit klarkommen muss.
