### ISSUE TITLE
http://www.snik.eu/ontology/ciox/DurchfuehrungJourFixeCEO v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#141]
The class http://www.snik.eu/ontology/ciox/DurchfuehrungJourFixeCEO has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Rechtschreibfehler: Im englischen label nicht "joure fixe" sondern "jour fix"

**Comment by KonradHoeffner** [comment]
Sind sie sicher? Jour Fixe ist ja dem französischen entliehen. Im Wiktionary steht es auch mit e:  https://en.wiktionary.org/wiki/jour_fixe

**Comment by AlfredWinter** [comment]
Soweit ich weiß, ist es ein französischer 'false friend' wie "handy". Jour Fix gibt es im Französischen gar nicht. Haben mir mal Leute gesagt...

**Comment by KonradHoeffner** [comment]
"Jour fix" wird und wurde weder im British English, noch im American English jemals verwendet in Büchern vom Jahr 1800 bis jetzt:

https://books.google.com/ngrams/graph?content=jour+fix%2Cjour+fixe&year_start=1800&year_end=2018&corpus=17&smoothing=3&share=&direct_url=t1%3B%2Cjour%20fixe%3B%2Cc0
https://books.google.com/ngrams/graph?content=jour+fix%2Cjour+fixe&year_start=1800&year_end=2008&corpus=18&smoothing=3&share=&direct_url=t1%3B%2Cjour%20fixe%3B%2Cc0

Im Französischen gibt es das zwar aber die Häufigkeit ist nahe null:
https://books.google.com/ngrams/graph?content=jour+fix%2Cjour+fixe&year_start=1800&year_end=2018&corpus=19&smoothing=3&share=&direct_url=t1%3B%2Cjour%20fix%3B%2Cc0%3B.t1%3B%2Cjour%20fixe%3B%2Cc0

**Comment by AlfredWinter** [comment]
Herr Höffner hat recht. Nur ein "e".

**Comment by KonradHoeffner** [comment]
@AnnaLoerke: Bitte label "Joure-fixe Execution CEO" zu "Jour-fixe Execution CEO" korrigieren.
