### ISSUE TITLE
http://www.snik.eu/ontology/bb/TacticalInformationManagement (http://www.w3.org/2004/02/skos/core#closeMatch) http://www.snik.eu/ontology/ob/TacticalManagementOfInformationSystems v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#142]
The edge "http://www.snik.eu/ontology/bb/TacticalInformationManagement (http://www.w3.org/2004/02/skos/core#closeMatch) http://www.snik.eu/ontology/ob/TacticalManagementOfInformationSystems" is incorrect.

**Details**
das stimmt nicht; der CIO ist verantwortlich. Bitte löschen.

**Comment by KonradHoeffner** [comment]
Erledigt.
