### ISSUE TITLE
http://www.snik.eu/ontology/bb/StrategicInformationManagement v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#143]
The class http://www.snik.eu/ontology/bb/StrategicInformationManagement has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
die inverse isresponsible-Beziehung zu information Management staff ist falsch und muss weg. Stattdessen bitte responsible von  bb/cio !

**Comment by KonradHoeffner** [comment]
Ist im virtual graph, ich überprüfe, wie wir sowas am besten handeln.

**Comment by AnnaLoerke** [comment]
done.
