### ISSUE TITLE
http://www.snik.eu/ontology/bb/OperationalInformationManagement v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#144]
The class http://www.snik.eu/ontology/bb/OperationalInformationManagement has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
die inverse isresponsible-Beziehung zu information Management staff ist falsch und muss weg. Stattdessen bitte responsible von bb/cio !

**Comment by AnnaLoerke** [comment]
Die Verbindung zwischen bb/OperationalInformationManagement und bb/CIO ist erstellt. 

bb/InformationManagementStaff ist aktuell sowohl für strategisches, taktisches als auch operatives Informationsmanagment als isResposibleForFunction modelliert. Sollen dann alle drei gelöscht werden?

**Comment by AlfredWinter** [comment]
ja

**Comment by AnnaLoerke** [comment]
done.
