### ISSUE TITLE
http://www.snik.eu/ontology/ob/FinalReportPresentation (http://www.snik.eu/ontology/meta/uses) http://www.snik.eu/ontology/ob/FinalReport v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#146]
The edge "http://www.snik.eu/ontology/ob/FinalReportPresentation (http://www.snik.eu/ontology/meta/uses) http://www.snik.eu/ontology/ob/FinalReport" is incorrect.

**Details**
Syntaxfehler

**Comment by KonradHoeffner** [comment]
Habe es zur Funktion geändert. Dadurch geht meta:uses wieder und das stimmt auch mit der Oberklasse ob:InformationManagement überein.
