### ISSUE TITLE
Klassen zusammenführen

### ISSUE THREAD

**Issue by FranziskaJahn** [IMISE/snik-ontology#15]
Bitte Information Management Department (BB) mit Department of Information Management (BB) zusammenführen. Department of Information Management als Label

**Comment by KonradHoeffner** [comment]
Bitte nochmal verifizieren. Es gibt in bb.rdf (Stand commit b80d3ec081d58f8aede5711c5b131bf1392e0243) nur die Klasse`bb:InformationManagementDepartment`und keine Klasse `bb:DepartmentOfInformationManagement`. Ich habe allerdings das label mit dem altlabel getauscht.
