### ISSUE TITLE
Widerspruch zwischen LodLive und Visualisierung & Fehler in LodLive

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#150]
In LodLive und LodView gibt es jede Menge falsche closeMatch Beziehungen zu http://www.snik.eu/ontology/ob/InformationSystem. Das sind in der Regel "isA" (subclassOf??) Beziehungen. Muss sorgfältig durchgegangen werden. Einige haben auch eine andere Beziehung. 

Diese Sachen finden sich in snik.eu/graph nicht. 
AW

**Comment by KonradHoeffner** [comment]
Ah das sind die LIMES-Beziehungen, ich habe auch die nicht 100%-sicheren mit reingenommen in der Hoffnung, dass die schon gut genug sind, dann nehme ich die wieder raus. Im Graph sind die LIMES-Beziehungen noch nicht drin.

**Comment by AlfredWinter** [comment]
Wir brauchen dazu auch die Anzeige der Qualitätsstufen, damit man gleich sieht, dass es möglicherweise nicht richtig ist. 
AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      ++49 341-97-16107, 
Mobile: ++49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Konrad Höffner [mailto:notifications@github.com] 
Gesendet: Dienstag, 1. August 2017 14:35
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-ontology] Widerspruch zwischen LodLive und Visualisierung & Fehler in LodLive (#150)
 
Ah das sind die LIMES-Beziehungen, ich habe auch die nicht 100%-sicheren mit reingenommen in der Hoffnung, dass die schon gut genug sind, dann nehme ich die wieder raus. Im Graph sind die LIMES-Beziehungen noch nicht drin.

**Comment by KonradHoeffner** [comment]
So, die nichtexakten sind jetzt wieder draußen.

**Comment by KonradHoeffner** [comment]
Wie finden sie ein Warnschild bei LIMES-Links?

![limesquality](https://user-images.githubusercontent.com/839577/28833064-99ae12ee-76de-11e7-97f2-df399a98932e.png)

**Comment by AlfredWinter** [comment]
Sollten wir versuchen. Gut.
AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      ++49 341-97-16107, 
Mobile: ++49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Konrad Höffner [mailto:notifications@github.com] 
Gesendet: Dienstag, 1. August 2017 17:27
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-ontology] Widerspruch zwischen LodLive und Visualisierung & Fehler in LodLive (#150)
 
Wie finden sie ein Warnschild bei LIMES-Links?

**Comment by KonradHoeffner** [comment]
OK ist jetzt drin und im pgraph online. Es gibt zwischen CIOX und IT allerdings wenige LIMES-Links, ein Beispiel ist Service Desk.
