### ISSUE TITLE
Instanzen

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#151]
Bei der Generierung der URI der Instanzen muss automatisch für Eindeutigkeit gesorgt werden, z.B. durch einen Zeitstempel. Hintergrund: Es können z.b. viele Ziele formuliert werden und da kann keiner Garantieren, dass es Ziel nicht schon mal gegeben hat. 

Mir wäre auch wohler, wenn bei den Konzepten automatisch für Eindeutigkeit gesorgt würde. 

AW

**Comment by KonradHoeffner** [comment]
Wäre eine Fehlermeldung OK, wenn es eine URI schon gibt?

**Comment by AlfredWinter** [comment]
Ich dachte, Sie haben Urlaub?? Oder ist Ihnen Urlaub im Moment zu stressig? ;-)
 
Fehlermeldung geht auch. 
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      ++49 341-97-16107, 
Mobile: ++49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Konrad Höffner [mailto:notifications@github.com] 
Gesendet: Dienstag, 1. August 2017 13:29
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-ontology] Instanzen (#151)
 
Wäre eine Fehlermeldung OK, wenn es eine URI schon gibt?

**Comment by KonradHoeffner** [comment]
Ich glaube das bezog sich auf die Instanzerzeugung im SNIK Graph, die es jetzt nicht mehr gibt, daher mache ich das mal zu. Bitte wieder aufmachen und schreiben, falls das doch noch relevant ist.

**Comment by AlfredWinter** [comment]
ok
