### ISSUE TITLE
Quellen

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#152]
Im Kommentar der Klasse http://www.snik.eu/ontology/bb müssen die Bibliographischen Angaben des Buchs sauber eingetragen werden ("Blaues Buch" ist Slang und muss weg): 

Winter A, Haux R, Ammenwerth E, Brigl B, Hellrung N, Jahn F. Health Information Systems - Architectures and Strategies. London: Springer; 2011.

Dasselbe auch für die anderen Bücher:

ob:  Ammenwerth E, Haux R, Knaup-Gregori P, Winter A. IT-Projektmanagement im Gesundheitswesen - Lehrbuch und Projektleitfaden. Stuttgart: Schattauer; 2014.

he: Heinrich LJ, Riedl R, Stelzer D, Sikora H. Informationsmanagement: Grundlagen, Aufgaben, Methoden. 11., vollst. überarb. Aufl. Berlin: de Gruyter; 2014. Available from: URL: http://www.degruyter.com/view/product/343705.

Bitte auch bei den Interviewdaten von Smers und anderen Teilonotologien darauf achten, dass förmlich korrekte Bezeichnungen gewählt sind und kein interner Slang. Die Dinge sind ja jetzt öffentlich. 

Grüße, aW

**Comment by KonradHoeffner** [comment]
Hinzugefügt. Muss bei he eventuell nochmal gemacht werden, falls da noch eine neue Revision kommt.

**Comment by SebStaeubert** [comment]
Auch bei it4it gibt es nun die bibliografischen Informationen.
