### ISSUE TITLE
http://www.snik.eu/ontology/ob/PreparationAndModeling v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#153]
The class http://www.snik.eu/ontology/ob/PreparationAndModeling has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
merkwürderweise wird die deutsche Bezeichnung angezeigt, nicht die Englische.

**Comment by KonradHoeffner** [comment]
Gleiches Problem wie https://github.com/IMISE/snik-cytoscape.js/issues/96, behoben in https://github.com/IMISE/snik-cytoscape.js/commit/0cadcfeeeb71fc541797d1682c35d779e63cce32.
