### ISSUE TITLE
http://www.snik.eu/ontology/ob/VerificationSystemAnalysis v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#154]
The class http://www.snik.eu/ontology/ob/VerificationSystemAnalysis has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
statt der englischen wird die deutsche Bezeichnung angezeigt

**Comment by KonradHoeffner** [comment]
Das war ein Problem in der Visualisierung. Für https://github.com/IMISE/snik-cytoscape.js/issues/96 bereits erledigt in https://github.com/IMISE/snik-cytoscape.js/commit/0cadcfeeeb71fc541797d1682c35d779e63cce32.
