### ISSUE TITLE
http://www.snik.eu/ontology/he/Schuesselfaktorenanalyse v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#155]
The class http://www.snik.eu/ontology/he/Schuesselfaktorenanalyse has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Falsch geschrieben im label und auch in der URL: es fehlt ein "l" . 
Ferner: 
-- lässt sich in der Suche auch mit "Schüsselfaktorenanalyse" nicht finden
-- Im Lodview ist ein Close match zu <he:Erfolgsfaktorenanalyse> angegeben. Ein Klick dadrauf führt zum Fehler "Adresse nicht erkannt"

**Comment by AnnaLoerke** [comment]
closeMatch-Problem behoben.

Rest offen.

**Comment by KonradHoeffner** [comment]
Warum man es in der Suche nicht findet, verstehe ich nicht. Laut log wird folgende SPARQL Query generiert, die auch Erfolg hat:
```
select distinct(?s) { {?s a owl:Class.} UNION {?s a rdf:Property.}
			{?s rdfs:label ?l.} UNION {?s skos:altLabel ?l.}	
filter(regex(replace(str(?l)," ",""),"Schüsselfaktorenanalyse","i")) } 
order by asc(strlen(str(?l))) limit 100
```

**Comment by KonradHoeffner** [comment]
OK den Suchfehler habe ich jetzt behoben, das war ein Bug. Siehe https://github.com/IMISE/snik-cytoscape.js/commit/950ca19dfac76c59c53d642879f5c205269bbed0.

**Comment by KonradHoeffner** [comment]
Habe die Klasse umbenannt.
Im Wiki unter https://wiki.imise.uni-leipzig.de/Projekte/SNIK/ontologie/sparul ist jetzt beschrieben, wie man beliebige Klassen umbenennt.

%%
SPARQL
with <http://www.snik.eu/ontology/he>
delete
{
<http://www.snik.eu/ontology/he/Schuesselfaktorenanalyse> ?p ?o .
}
insert
{
<http://www.snik.eu/ontology/he/Schluesselfaktorenanalyse> ?p ?o .
}
where
{
<http://www.snik.eu/ontology/he/Schuesselfaktorenanalyse> ?p ?o .
}
%%

%%
SPARQL
with <http://www.snik.eu/ontology/he>
delete
{
?s ?p <http://www.snik.eu/ontology/he/Schuesselfaktorenanalyse>.
}
insert
{
?s ?p <http://www.snik.eu/ontology/he/Schluesselfaktorenanalyse>.
}
where
{
?s ?p <http://www.snik.eu/ontology/he/Schuesselfaktorenanalyse>.
}
%%

**Comment by KonradHoeffner** [comment]
Label korrigiert. Damit sind jetzt alle Probleme behoben.
