### ISSUE TITLE
http://www.snik.eu/ontology/bb/HealthInformationSystem v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#157]
The class http://www.snik.eu/ontology/bb/HealthInformationSystem has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Im ob müsste es auch ein HIS geben. Beide über CloseMatch verbinden

**Comment by AnnaLoerke** [comment]
Ich kann im ob nur Hospital Information System finden. Dies gibt es dann auch im bb. Zwischen den beiden Hospital Information Systems gibt es auch einen closeMatch.

**Comment by AlfredWinter** [comment]
Ok, das hatte ich nicht bedacht. Es fehlt aber dann noch ein sinnvoller Zusammenhang von Health Information System und Hospital Information System. Den Bezug habe ich über ein Ticket dadurch hergestellt, dass nun das institutional health IS eine Subclass von Health IS ist (Hospital IS ist ja schon eine subclass von institutional health IS).

**Comment by FranziskaJahn** [comment]
Das ist doch jetzt geklärt, oder?

**Comment by AlfredWinter** [comment]
ja. AW
