### ISSUE TITLE
http://www.snik.eu/ontology/bb/IheCrossEnterpriseDocumentSharing v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#158]
The class http://www.snik.eu/ontology/bb/IheCrossEnterpriseDocumentSharing has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
page number and description is missing

**Comment by AnnaLoerke** [comment]
done.
