### ISSUE TITLE
http://www.snik.eu/ontology/ob/FormulationOfProjectGoals v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#159]
The class http://www.snik.eu/ontology/ob/FormulationOfProjectGoals has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Die englische Übersetzung "Formulation" finde ich nicht so gut. Bitte in "Defining" ändern.
AW

**Comment by KonradHoeffner** [comment]
Habe das englische Label umbenannt in "Definition of Project Goals" sowie die URL zu http://www.snik.eu/ontology/ob/DefinitionOfProjectGoals.
