### ISSUE TITLE
Fehlende IOR CIOx und Rest

### ISSUE THREAD

**Issue by FranziskaJahn** [IMISE/snik-ontology#16]
Anbei alle fehlenden IOR-Beziehungen von CIOx. (PDF ließ sich hier nicht hochladen, docx schon)

[IOR_CIOx.docx](https://github.com/IMISE/snik-ontology/files/575659/IOR_CIOx.docx)

**Comment by KonradHoeffner** [comment]
sind drin (gehört zum CIOX repository).
