### ISSUE TITLE
Kante "responsible for" von CIO zu Information Mangagement Department

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#160]
The edge "undefined" is incorrect.

**Details**
1. es gibt den Relationstyp "responsible for" nicht (mehr) (nur ..for function oder ... for entity type.
2. Im Meta-Modell müsste ein neuer Relationtyp "is responsible for role" von Rolle zu Rolle eingefügt werden. ABER: Bitte vorher in der Gruppe diskutieren!
3. Dann hier und bei anderen ähnlichen Situationen reparieren.

**Comment by KonradHoeffner** [comment]
Kann ich gerne machen. Franziska und Birgit, habt ihr da Einwände?

**Comment by KonradHoeffner** [comment]
Duplicate of  #196.
