### ISSUE TITLE
http://www.snik.eu/ontology/ob/ProjectSteeringCommittee v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#161]
The class http://www.snik.eu/ontology/ob/ProjectSteeringCommittee has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
In LodView ist zu diesem Begirff ein Closematch zu "Lenkungsauschuss" aus CIOX eingetragen. Das ist falsch! Aber interessanterweise wird dieser closematch in snik-graph nicht angezeigt. Bitte zuerst die Diskrepanz zwischen LodView und Snik-graph klären und dann den closmatch löschen.

**Comment by KonradHoeffner** [comment]
Mittlerweile wird es auch im SNIK Graph angezeigt, ich weiß nicht, warum das vorher nicht so war. Auf jeden Fall habe ich es jetzt gelöscht.

![closematch](https://user-images.githubusercontent.com/839577/47732384-6095b900-dc66-11e8-8d83-741a4f4bca16.png)
