### ISSUE TITLE
http://www.snik.eu/ontology/bb/InformationManagementBoard v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#162]
The class http://www.snik.eu/ontology/bb/InformationManagementBoard has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Die Zusammensetzung (decomposed in) muss vervollständigt werden: Abteilungsleiter, Berufsgruppe Pflege, Berufsgruppe Ärzte, Verwaltungsmitarbeiter. Überlegen, wie man diese Begriffe repräsentiert.

**Comment by AlfredWinter** [comment]
Zurück! Bitte nicht wie oben angefordert neue Begriffe einführen! Stattdessen: die "Subclass of" zu HIS-Stakeholdern ersetzen durch "decomposed in"

**Comment by KonradHoeffner** [comment]
Erledigt (genaueres roleComponent benutzt).
Außerdem habe ich meta:Role als Oberklasse hinzugefügt, weil es sonst keine mehr gab nach der Änderung.
