### ISSUE TITLE
http://www.snik.eu/ontology/bb/ProjectManagementBoard v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#163]
The class http://www.snik.eu/ontology/bb/ProjectManagementBoard has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Hier gibt es communicates with Relationen. Die sind nicht erlaubt, statt dessen: --- weiß ich nicht. Muss geklärt werden, wie man das mit dem Meta-Modell ausdrückt - oder meta-Modell erweitern? -----

**Comment by FranziskaJahn** [comment]
Wäre es denn sinnvoll eine Relation "communicates with" oder vielleicht auch "interacts with" zwischen Rollen zu haben? Ich glaube wir haben diese Relation illegalerweise ab und zu dafür genutzt. Oder ist es interessanter zu sehen, an welchen Aufgabe diese Rollen gemeinsam beteiligt sind - das sollte in den meisten Fällen Kommunikation mit einschließen, aber vielleicht auch nicht?

**Comment by AlfredWinter** [comment]
Ich finde Relationen "communicates with" oder vielleicht auch "interacts with" nicht so gut. Aussagekräftiger finde ich, zu modellieren, an welchen Aufgabe diese Rollen gemeinsam beteiligt sind.

**Comment by BirgitSNIK** [comment]
Von: FranziskaJahn [mailto:notifications@github.com] 
Gesendet: Mittwoch, 7. November 2018 13:13
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: BirgitSNIK <birgit.schneider@imise.uni-leipzig.de>; Assign <assign@noreply.github.com>
Betreff: Re: [IMISE/snik-ontology] http://www.snik.eu/ontology/bb/ProjectManagementBoard v (#163)
 
Wäre es denn sinnvoll eine Relation "communicates with" oder vielleicht auch "interacts with" zwischen Rollen zu haben? Ich glaube wir haben diese Relation illegalerweise ab und zu dafür genutzt. Oder ist es interessanter zu sehen, an welchen Aufgabe diese Rollen gemeinsam beteiligt sind - das sollte in den meisten Fällen Kommunikation mit einschließen, aber vielleicht auch nicht?
Ich finde es interessanter zu sehen, an welchen Aufgabe diese Rollen gemeinsam beteiligt sind. Zu wissen, dass da Kommunikation stattfindet, sagt noch nichts darüber aus, was das Thema dieser Kommunikation ist.
Hast du ein konkretes Beispiel, für das du diese „neue“ Relation gerne einführen würdest?
 
Birgit

**Comment by KonradHoeffner** [comment]
Aus Meeting 9.11.2018:
Zählen, wie oft communicates with vorkommt und wie oft das implizit bereits dadurch ausgedrückt ist, dass beide Rollen in die gleiche Aufgabe involviert sind oder dafür verantwortlich sind.
Liste erstellen und per Mail an Beteiligte schicken.

**Comment by AlfredWinter** [comment]
Herr Wermke darf das übernehmen. Nur zwischen Typen, bei denen mindestens einer keine Informationssystemkomponente ist, zum Beispiel zwischen Rollen oder zwischen Rollen und Funktionen.  In dem Kontext ist das falsch verwendet, weil das in der Extraktionstabelle nicht verhindert wurde. Das andere communicatesWith ist zwischen Komponenten des Informationssystems im meta Modell erlaubt und ist völlig legal.

**Comment by KonradHoeffner** [comment]
![communicateswith](https://user-images.githubusercontent.com/839577/50165271-e20fdc00-02e4-11e9-8973-aef4ca7a70ea.jpg)

**Comment by LudwigWermke** [comment]
alle communicate-with-matches (in Absprache mi Konrad, Birgit und Franziska) gelöscht, die keinen Sinn ergeben
