### ISSUE TITLE
http://www.snik.eu/ontology/bb/InformationManagementEntityType v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#164]
The class http://www.snik.eu/ontology/bb/InformationManagementEntityType has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Dieser Begriff ist für Auswertungen absolut störend. Das sieht man schon daran, dass er Beziehungen zu ca. 140 anderen Begriffen Beziehungen hat. Diskussion nötig: Ganz entfernen oder zumindest als "meta" oder "quasi-meta" kennzeichnen, damit man diesen Begriff und ggf. auch ähnliche rausfiltern kann. Ferner ist zu prüfen, ob es überhaupt im BB vorkommt.

**Comment by AlfredWinter** [comment]
Falls es im BB vorkommt, dann muss auch Seitenzahl etc. hier dokumentiert werden.

**Comment by AlfredWinter** [comment]
Franziska fragen, ob man es löschen kann.
Bezieht sich auch auf "Information Management Function/Role".

**Comment by KonradHoeffner** [comment]
@FranziskaJahn : Kann man das löschen oder ist es notwendig?

**Comment by KonradHoeffner** [comment]
Franziska ist einverstanden: Löschen.

**Comment by KonradHoeffner** [comment]
143 Klassen haben bb:InformationManagementEntityType als Oberklasse: `SELECT COUNT(DISTINCT(?x)) {?x rdfs:subClassOf bb:InformationManagementEntityType.}`

140 davon haben keine andere Oberklasse:
```
SELECT COUNT(DISTINCT(?x))
{
 ?x rdfs:subClassOf bb:InformationManagementEntityType.
 MINUS
 {
  ?x rdfs:subClassOf ?y.
  FILTER(?y != bb:InformationManagementEntityType)
 }
}
```

**Comment by KonradHoeffner** [comment]
Backed up SPARQL endpoint with prefix "20200629".
Added triples via

```
SPARQL
WITH <http://www.snik.eu/ontology/bb>
insert
{
?x rdfs:subClassOf meta:EntityType.
}
where
{
 ?x rdfs:subClassOf bb:InformationManagementEntityType.
 MINUS
 {
  ?x rdfs:subClassOf ?y.
  FILTER(?y != bb:InformationManagementEntityType)
 }
}
```

`Insert into <http://www.snik.eu/ontology/bb>, 140 (or less) triples -- done`

**Comment by KonradHoeffner** [comment]
```
SPARQL
WITH <http://www.snik.eu/ontology/bb>
DELETE WHERE
{
 bb:InformationManagementEntityType ?y ?z.
}
DELETE WHERE
{
 ?x ?y bb:InformationManagementEntityType.
}
```

**Comment by KonradHoeffner** [comment]
Now we just have the persian label and the skos:broader links.

**Comment by KonradHoeffner** [comment]
There are also derived links but those go away on recalculation.

**Comment by KonradHoeffner** [comment]
```
SPARQL
WITH <http://www.snik.eu/ontology/ob>
DELETE WHERE
{
 bb:InformationManagementEntityType ?y ?z.
}
DELETE WHERE
{
 ?x ?y bb:InformationManagementEntityType.
}
```

**Comment by KonradHoeffner** [comment]
Done
