### ISSUE TITLE
http://www.snik.eu/ontology/bb/StrategicInformationManagementPlan v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#165]
The class http://www.snik.eu/ontology/bb/StrategicInformationManagementPlan has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
benötigt noch eine "decomposedIn" Beziehung zu http://www.snik.eu/ontology/bb/DirectiveForHISConstruction

**Comment by KonradHoeffner** [comment]
Erledigt (mit dem genaueren meta:entityTypeComponent).
