### ISSUE TITLE
http://www.snik.eu/ontology/bb/DirectiveForHISConstruction v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#166]
The class http://www.snik.eu/ontology/bb/DirectiveForHISConstruction has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Die Beziehung "updates" von http://www.snik.eu/ontology/bb/StrategicHISPlanning nach hier muss weg.

**Comment by KonradHoeffner** [comment]
Erledigt.
