### ISSUE TITLE
http://www.snik.eu/ontology/bb/StrategicInformationManagementPlan v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#167]
The class http://www.snik.eu/ontology/bb/StrategicInformationManagementPlan has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Von hier gibt es eine update zu http://www.snik.eu/ontology/bb/StrategicHISPlanning. das ist falsch-rum. Bitte drehen

**Comment by KonradHoeffner** [comment]
Ist bereits richtig herum, vielleicht hat das schon jemand gedreht und nicht vermerkt? Oder das stand bei den inversen Properties.
