### ISSUE TITLE
http://www.snik.eu/ontology/bb/ChiefInformationOfficer v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#168]
The class http://www.snik.eu/ontology/bb/ChiefInformationOfficer has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
ist auch noch responsible for http://www.snik.eu/ontology/bb/OperationalInformationManagement

**Comment by KonradHoeffner** [comment]
Erledigt.
