### ISSUE TITLE
http://www.snik.eu/ontology/meta/MethodApplication v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#169]
The class http://www.snik.eu/ontology/meta/MethodApplication has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Wird als Sechseck dargestellt. Was bedeutet das? Es gibt auch noch mehr Sechsecke.

**Comment by KonradHoeffner** [comment]
Das bedeutet, es ist weder function, role noch entity type. Das liegt wohl daran, dass wir die subTopClass Relation in meta nicht benutzt haben, ich habe das korrigiert für diese Klasse.
