### ISSUE TITLE
undefined v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#172]
The edge "undefined" is incorrect.

Der close-match zwischen http://www.snik.eu/ontology/bb/InformationManagement und http://www.snik.eu/ontology/it/ManagementInformation ist falsch. Zum Einen, weil das eine ein entitytype und das andere eine Funktion ist. Zum anderen scheint mir das aber auch von der Beschreibung her nicht dasselbe zu sein. 
AW

**Comment by KonradHoeffner** [comment]
Habe die ganze Klasse http://www.snik.eu/ontology/it/ManagementInformation gelöscht, da es dazu garkeine Daten gibt, das war wohl nur noch eine Sammlung von veralteten Limes-Links.
