### ISSUE TITLE
http://www.snik.eu/ontology/he/AdministrativeInformationsmanagementaufgabe v

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#174]
The class http://www.snik.eu/ontology/he/AdministrativeInformationsmanagementaufgabe has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Das ist kein eigenes Konzept sondern nur die Deutsche Übersetzung von http://www.snik.eu/ontology/he/AdministrativesInformationsmanagement. Also als Konzept löschen und die Bezeichnung als deutsches label zu http://www.snik.eu/ontology/he/AdministrativesInformationsmanagement****

**Comment by KonradHoeffner** [comment]
Habe wie gewünscht http://www.snik.eu/ontology/he/AdministrativeInformationsmanagementaufgabe gelöscht. http://www.snik.eu/ontology/he/AdministrativesInformationsmanagement hat bereits das deutsche Label "Administratives Informationsmanagement", daher musste hier nichts hinzugefügt werden.
