### ISSUE TITLE
Two classes for CIO in "he"

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#175]
There are two classes for CIO in "he":

    http://www.snik.eu/ontology/he/ChiefInformationOfficer
    http://www.snik.eu/ontology/he/Cio

As per our standards, there should be only one. I recommend merging them into http://www.snik.eu/ontology/he/ChiefInformationOfficer.

**Comment by KonradHoeffner** [comment]
Bitte generell genau einen ausgeschrieben Bezeichnung als rdfs:label benutzen. Alle anderen Bezeichnungen und Abkürzungen bitte als skos:prefLabel modellieren.

Siehe https://wiki.imise.uni-leipzig.de/Projekte/SNIK/ontologie/extraktion/extraktionstabelle, Sektionen "SubjektDe, SubjektEn (deutsches und/oder englisches Label)" und "SubjektAltDe, SubjektAltEn (alternative Subjektlabel)":

> Mindestens ein Label muss immer vorhanden sein aber maximal eines pro Sprache.
> In einem deutschen Buch wird meist das deutsche Label vorhanden sein, analog bei einem englischen Buch.
> Das Label ist kurz und prägnant, z.B. “Informationsmanagement” oder “information management”.
> Wichtig ist auch die korrekte Großschreibung. Achtung: Im Englischen werden nur Eigennamen groß geschrieben.
>

**Comment by AnnaLoerke** [comment]
done.
