### ISSUE TITLE
http://www.snik.eu/ontology/ciox/ItStrategie

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#182]
Komisch, bisher wurde bei den Tickets auch immer ein Text zu dem objekt angezeigt, zu dem man das Ticket einrichtet. 

Hier gibt es eine Dublette wegen Rechtschreibfehler (kleines und großes T):
http://www.snik.eu/ontology/ciox/ItStrategie und http://www.snik.eu/ontology/ciox/ITStrategie 
Die beiden müssen zusammengeführt werden.
AW

**Comment by KonradHoeffner** [comment]
Der Text zu den Issues müsste jetzt wieder funktionieren.

**Comment by AlfredWinter** [comment]
?

**Comment by AnnaLoerke** [comment]
@KonradHoeffner : Welche Schreibweise entspricht der Konvention? ItStrategie oder ITStrategie?

**Comment by AnnaLoerke** [comment]
Ist die Relation "isMasterFor" zwischen zwei Entity Types durch entityTypeComponent oder isBasedOn ersetzt worden? Wenn ja, welches soll verwendet werden? Wenn nein, wie ummodellieren? Relation ist ciox/Kollaborationsplattform meta:isMasterFor ciox/ITStrategie.

**Comment by AlfredWinter** [comment]
Ich weiß nicht genau, was mit masterfor gemeint war, vermute aber dass das aus 3LGM² kommt. Diese Bedeutung passt aber hier ohnehin nicht. Birgit möge bitte sagen, welche Beziehung zwischen ciox/Kollaborationsplattform und ciox/ITStrategie herrschen könnte.

**Comment by KonradHoeffner** [comment]
@AnnaLoerke: Die Konvention ist UpperCamelCase für Klassen und lowerCamelCase für Relationen.

In diesem Fall wäre es ItStrategie.

Siehe Wiki: https://wiki.imise.uni-leipzig.de/Projekte/SNIK/ontologie/extraktion/extraktionstabelle

**Comment by BirgitSNIK** [comment]
[SNIK-Metamodell BBundOB.pdf](https://github.com/IMISE/snik-ontology/files/2951340/SNIK-Metamodell.BBundOB.pdf)
Im OB und BB gibt es für computerbasierte Anwendungssysteme die Beziehung isMasterFor. Macht dort Sinn und wurde offensichtlich von Christian auch für CIOX verwendet. Siehe Metamodell vom Februar 2017.

**Comment by AnnaLoerke** [comment]
@KonradHoeffner 
Könntest du mal gucken, wie oft und in welchen Büchern "isMasterFor" verwendet wird?

**Comment by BirgitSNIK** [comment]
Außerdem könntest du gleich noch überprüfen, wie oft communicatesWith und supports verwendet wird. Und dann gibt es noch das spezielle isBasedOn zwischen Computer-Based Application Component und SoftwareProduct.
Muss aber nicht sofort sein, könntest du auch erst nach unserer Besprechung machen, je nach Ergebnis.
Birgit
 
Von: AnnaLoerke <notifications@github.com> 
Gesendet: Montag, 11. März 2019 09:51
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: BirgitSNIK <birgit.schneider@imise.uni-leipzig.de>; Assign <assign@noreply.github.com>
Betreff: Re: [IMISE/snik-ontology] http://www.snik.eu/ontology/ciox/ItStrategie (#182)
 
@KonradHoeffner
Könntest du mal gucken, wie oft und in welchen Büchern "isMasterFor" verwendet wird?

**Comment by AnnaLoerke** [comment]
Meeting 11.03. bezüglich "isMasterFor": Was wollen wir genau sagen? Längere Besprechung nötig. Erweitertes Metamodell mit IT4IT? Gemeinsame Besprechung mit Ticket #286

**Comment by KonradHoeffner** [comment]
@BirgitSNIK @AnnaLoerke 

```
select count(*) ?g
{
 graph ?g {?x meta:isMasterFor ?y}
}
```


callret-0 | g
-- | --
24 | http://www.snik.eu/ontology/ciox

```
select *
{
 ?x meta:isMasterFor ?y
}
```


x | y
-- | --
http://www.snik.eu/ontology/ciox/Arbeitsablaufsystem | http://www.snik.eu/ontology/ciox/Angebot
http://www.snik.eu/ontology/ciox/Materialwirtschaftssystem | http://www.snik.eu/ontology/ciox/Bestellung
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Betriebskonzept
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Dienstanweisung
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Etat
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Projektabschlussbericht
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Projektauftrag
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Projekteliste
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Projektewarteliste
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Projektplan
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Projektstatusbericht
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Projektuebergabeprotokoll
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Projektwebsite
http://www.snik.eu/ontology/ciox/Arbeitsablaufsystem | http://www.snik.eu/ontology/ciox/Rechnung
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Rechnung
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Ressourcenplan
http://www.snik.eu/ontology/ciox/ITServiceManagementSystem | http://www.snik.eu/ontology/ciox/Ticket
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Wartungsaktivitaetsprotokoll
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/Wartungsvertrag
http://www.snik.eu/ontology/ciox/Kostenrechnungssystem | http://www.snik.eu/ontology/ciox/Wirtschaftsplan
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/ChangeAntrag
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/ChangeAntragProtokoll
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/ITStrategie
http://www.snik.eu/ontology/ciox/Kollaborationsplattform | http://www.snik.eu/ontology/ciox/JourFixeProtokoll

**Comment by KonradHoeffner** [comment]
@BirgitSNIK

```
select count(*) ?g
{
 graph ?g {?x meta:communicatesWith ?y}
}
```

callret-0 | g
-- | --
12 | http://www.snik.eu/ontology/bb

```
select count(*) ?g
{
 graph ?g {?x meta:supports ?y}
}
```


callret-0 | g
-- | --
22 | http://www.snik.eu/ontology/ciox
4 | http://www.snik.eu/ontology/ob
100 | http://www.snik.eu/ontology/bb
24 | http://www.snik.eu/ontology/it4it

```
select count(*) ?g
{
 graph ?g {?x meta:isBasedOn ?y}
}
```

callret-0 | g
-- | --
17 | http://www.snik.eu/ontology/ciox
56 | http://www.snik.eu/ontology/he
13 | http://www.snik.eu/ontology/ob
21 | http://www.snik.eu/ontology/bb

**Comment by AlfredWinter** [comment]
@BirgitSNIK : Bitte meta:isMasterFor zum Metamodell hinzufügen.

**Comment by KonradHoeffner** [comment]
@BirgitSNIK: Kannst du eine neue Version vom SNIK Metamodell mit meta:isMasterFor rumschicken? Was ist domain und range davon? Dann trage ich das auch in den SPARQL Endpunkt ein.

**Comment by KonradHoeffner** [comment]
```
SPARQL
with <http://www.snik.eu/ontology/ciox> # "with" specifies the graph that the query modifies
delete
{
<http://www.snik.eu/ontology/ciox/ITStrategie> ?p ?o . # delete our original triple
}
insert
{
<http://www.snik.eu/ontology/ciox/ItStrategie> ?p ?o . # insert the new triple
}
where
{
<http://www.snik.eu/ontology/ciox/ITStrategie> ?p ?o . # again our original triple
}
```

`Modify <http://www.snik.eu/ontology/ciox>, delete 7 (or less) and insert 7 (or less) triples -- done`

```
SPARQL
with <http://www.snik.eu/ontology/ciox>
delete
{
?s ?p <http://www.snik.eu/ontology/ciox/ITStrategie> .
}
insert
{
?s ?p <http://www.snik.eu/ontology/ciox/ItStrategie> .
}
where
{
?s ?p <http://www.snik.eu/ontology/ciox/ITStrategie> .
}
```

`Modify <http://www.snik.eu/ontology/ciox>, delete 3 (or less) and insert 3 (or less) triples -- done`

**Comment by KonradHoeffner** [comment]
```
SPARQL
with <http://www.snik.eu/ontology/limes-exact>
delete data
{
<http://www.snik.eu/ontology/ciox/ITStrategie> <http://www.w3.org/2004/02/skos/core#closeMatch> <http://www.snik.eu/ontology/he/ITStrategie>.
}
```

```
SPARQL
with <http://www.snik.eu/ontology/limes-exact>
delete data
{
<http://www.snik.eu/ontology/ciox/ITStrategie> <http://www.w3.org/2004/02/skos/core#closeMatch> <http://www.snik.eu/ontology/he/ItStrategie>.
}
```
```
SPARQL
with <http://www.snik.eu/ontology/ciox>
insert data
{
<http://www.snik.eu/ontology/ciox/ITStrategie> <http://www.w3.org/2004/02/skos/core#closeMatch> <http://www.snik.eu/ontology/he/ItStrategie>.
}
```
