### ISSUE TITLE
bb:HospitalStaff rdfs:subClassOf bb:ChiefInformationOfficer v2018-10-22

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#184]
The edge "bb:HospitalStaff rdfs:subClassOf bb:ChiefInformationOfficer" is incorrect.

**Details**
There is an implicit relationship in the other direction. Remove this edge.

**Comment by AnnaLoerke** [comment]
Die Relation ist schon nicht mehr vorhanden. Ticket wird geschlossen.
