### ISSUE TITLE
ob:ProjectManagementTriangle rdfs:subClassOf ob:InformationManagement v2018-10-22

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#187]
The edge "ob:ProjectManagementTriangle rdfs:subClassOf ob:InformationManagement" is incorrect.

**Details**
Relation ist falsch, da unterschiedliche Typen.
AW

**Comment by KonradHoeffner** [comment]
Umhängen auf ob:ProjectManagement.

**Comment by AlfredWinter** [comment]
Das ist aber auch keine SubClass of ob:ProjectManagement. Ich fürchte, hier geht nur associates. AW

**Comment by AnnaLoerke** [comment]
done.
