### ISSUE TITLE
he:Informationsmanagement skos:closeMatch bb:InformationManagement v2018-10-22

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#188]
The edge "he:Informationsmanagement skos:closeMatch bb:InformationManagement" is incorrect.

**Details**
Beziehung muss gelöscht werden. information management Function ist eine art Meta-Konzept.

**Comment by AlfredWinter** [comment]
ACHTUNG ZURÜCK!!!!!
da steckt irgendwo ein Fehler. Es wird offenbar nicht zwischen bb:Informationsmanagement und Informationsmanagementfunction unterschieden

**Comment by KonradHoeffner** [comment]
They are not the same, in fact they are homonyms.
Can this be expressed in SKOS? See https://lists.w3.org/Archives/Public/public-esw-thes/2009Nov/0087.html.

**Comment by KonradHoeffner** [comment]
Jeweils zwischen hh-bb und zwischen hh-ob das closeMatch löschen. bb-ob ist richtig und bleibt!
Da wo es falsch ist, die Homonymbeziehung einbauen, wenn möglich.
