### ISSUE TITLE
http://www.snik.eu/ontology/bb/InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#190]
als Label wird angezeigt: "Information Management Function". Ich fürchte, hier ist irgendetwas durcheinandergeraten: Bitte eine kleine Krisenkonferenz!

**Comment by AlfredWinter** [comment]
mein Verdacht: irgendwann wurde "Information Management Function" und "Information Management" gemerget.
AW

**Comment by FranziskaJahn** [comment]
Ja, das ist so geschehen. Das hatten wir mal irgendwann in einer SNIK-Besprechung festgelegt.

**Comment by AlfredWinter** [comment]
An diesem Begriff hängen jetzt über subClassOf viel zu viele Begriffe. Diesen Begriff einfach als Sammelbegriff für alle functions des Informationssystems zu nehmen, bringt uns nicht weiter. Alle Functions in SNIK sind ja letztlich irgendwie Information Management functions. Sinnvoll sind subclasses wie Strategic Information Management oder Tactical Information Management. Aber nicht http://www.snik.eu/ontology/bb/HisBudgetPlanning .
Bitte alle SubClasses durchgehen, prüfen ob Sie schon unter einem spezifischeren Begriff hängen und in diesem Fall die SubClassOf zu Information Management entfernen. 
Wir sollten hier eine Transitivitätsregel einführen: Wenn es in SNIK von einem Knoten zu einem anderen einen genauer zu definierenden Weg gibt, dann sollte es keine 'Abkürzung' über eine direkte Relation, z.B. SubClassOf geben. Kann mal jemand eine solche Transitivitätsregel definieren?
AW

**Comment by BirgitSNIK** [comment]
(#190)
 
Bitte alle SubClasses durchgehen, prüfen ob Sie schon unter einem spezifischeren Begriff hängen und in diesem Fall die SubClassOf zu Information Management entfernen.
Finde ich gut.

Wir sollten hier eine Transitivitätsregel einführen: Wenn es in SNIK von einem Knoten zu einem anderen einen genauer zu definierenden Weg gibt, dann sollte es keine 'Abkürzung' über eine direkte Relation, z.B. SubClassOf geben. Kann mal jemand eine solche Transitivitätsregel definieren?
Ich denke, das betrifft nur die Beziehung subClassOf. Dann ist eine Transitivitätsregel aber recht einfach. Fällt jemandem ein Gegenbeispiel ein?
Vielleicht gibt es manchmal „Abkürzungen“ über isAssociatedWith, die sollten aber auch raus.
Birgit

**Comment by AlfredWinter** [comment]
Besprechung 18.12.2018
- [ ] "Information Management" (Function) und "Information Management Function" (Function) wieder aufteilen. (AL)

**Comment by KonradHoeffner** [comment]
@KonradHoeffner: Git commit history prüfen, ob das dort drin liegt und man es rückgängig machen kann.

**Comment by KonradHoeffner** [comment]
@AnnaLoerke Wie ist der Status?

**Comment by KonradHoeffner** [comment]
> Vielleicht gibt es manchmal „Abkürzungen“ über isAssociatedWith, die sollten aber auch raus. Birgit
isAssociatedWith ist meiner Meinung nach nicht transitiv, da es ja für jedwede Verbindung stehen kann. Z.B. Fred kennt Tom und Tom kennt Ernie aber Fred kennt Ernie nicht. Daher denke ich, dass man da nichts rausnehmen kann.

**Comment by KonradHoeffner** [comment]
## Fälle von ausmodellierter Transitivität
```
select ?g count(*)
{
 graph ?g
{
?a rdfs:subClassOf ?b.
 ?b rdfs:subClassOf ?c.
 ?a rdfs:subClassOf ?c.
}
}
```
graph | count
-- | --
http://www.snik.eu/ontology/he-unconsolidated | 3
http://www.snik.eu/ontology/ob | 32
http://www.snik.eu/ontology/bb | 16

### bb


a | b | c
-- | -- | --
http://www.snik.eu/ontology/bb/HL7Standard | http://www.snik.eu/ontology/bb/CommunicationStandard | http://www.snik.eu/ontology/bb/Standard
http://www.snik.eu/ontology/bb/MonitorAndEvaluate | http://www.snik.eu/ontology/bb/CobitDomain | http://www.snik.eu/ontology/bb/InformationManagement
http://www.snik.eu/ontology/bb/AcquireAndImplement | http://www.snik.eu/ontology/bb/CobitDomain | http://www.snik.eu/ontology/bb/InformationManagement
http://www.snik.eu/ontology/bb/HisBenchmarking | http://www.snik.eu/ontology/bb/PermanentMonitoring | http://www.snik.eu/ontology/bb/InformationManagement
http://www.snik.eu/ontology/bb/InformationManagementCost | http://www.snik.eu/ontology/bb/KeyPerformanceIndicator | http://www.snik.eu/ontology/bb/InformationManagementEntityType
http://www.snik.eu/ontology/bb/HL7MessageType | http://www.snik.eu/ontology/bb/MessageType | http://www.snik.eu/ontology/bb/InformationManagementEntityType
http://www.snik.eu/ontology/bb/Ward | http://www.snik.eu/ontology/bb/InpatientUnit | http://www.snik.eu/ontology/bb/OrganizationalUnitOfAHospital
http://www.snik.eu/ontology/bb/AvailabilityOfApplicationComponents | http://www.snik.eu/ontology/bb/SoftwareQuality | http://www.snik.eu/ontology/bb/QualityOfComputerBasedApplicationComponentsAndTheirIntegration
http://www.snik.eu/ontology/bb/Consistency | http://www.snik.eu/ontology/bb/IntegrityOfData | http://www.snik.eu/ontology/bb/QualityOfData
http://www.snik.eu/ontology/bb/PlanAndOrganize | http://www.snik.eu/ontology/bb/CobitDomain | http://www.snik.eu/ontology/bb/InformationManagement
http://www.snik.eu/ontology/bb/ReferenceModel | http://www.snik.eu/ontology/bb/Model | http://www.snik.eu/ontology/bb/InformationManagementEntityType
http://www.snik.eu/ontology/bb/SystemAnalysis | http://www.snik.eu/ontology/bb/ProjectExecution | http://www.snik.eu/ontology/bb/InformationManagement
http://www.snik.eu/ontology/bb/Systemtroduction | http://www.snik.eu/ontology/bb/ProjectExecution | http://www.snik.eu/ontology/bb/InformationManagement
http://www.snik.eu/ontology/bb/SystemSpecification | http://www.snik.eu/ontology/bb/ProjectExecution | http://www.snik.eu/ontology/bb/InformationManagement
http://www.snik.eu/ontology/bb/SystemSelection | http://www.snik.eu/ontology/bb/ProjectExecution | http://www.snik.eu/ontology/bb/InformationManagement
http://www.snik.eu/ontology/bb/SystemEvaluation | http://www.snik.eu/ontology/bb/ProjectExecution | http://www.snik.eu/ontology/bb/InformationManagement

**Comment by KonradHoeffner** [comment]
Ich habe mal nachgeforscht und die Klasse `bb:InformationManagement` hat schon in Version 0.3.0 vom 18.11.2016 das Label "Information Management Function".

**Comment by BirgitSNIK** [comment]
Ich würde da nichts transitiv vererben.
Birgit
 
Von: Konrad Höffner <notifications@github.com> 
Gesendet: Mittwoch, 6. November 2019 14:14
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: BirgitSNIK <birgit.schneider@imise.uni-leipzig.de>; Assign <assign@noreply.github.com>
Betreff: Re: [IMISE/snik-ontology] http://www.snik.eu/ontology/bb/InformationManagement (#190)
 
Vielleicht gibt es manchmal „Abkürzungen“ über isAssociatedWith, die sollten aber auch raus. Birgit
isAssociatedWith ist meiner Meinung nach nicht transitiv, da es ja für jedwede Verbindung stehen kann. Z.B. Fred kennt Tom und Tom kennt Ernie aber Fred kennt Ernie nicht. Daher denke ich, dass man da nichts rausnehmen kann.

**Comment by KonradHoeffner** [comment]
Da forsche ich nochmal nach, wie der Status ist. Vielleicht steht es noch auf ALs A3-Zettel (Ausdruck eines Teilgraphen mit Notizen).

**Comment by KonradHoeffner** [comment]
@FranziskaJahn sieht sich die Umgebung von bb:InformationManagement an und versucht, es zu entwirren. Bei der nächsten Jour fixe weitermachen am 21.4.2020.

**Comment by KonradHoeffner** [comment]
Vertagt auf die nächste Jour Fixe am 19.5.2020.

**Comment by KonradHoeffner** [comment]
FJ: Bild 1: Strategisches IM hat Aufgaben der Planung, Steuerung und Überwachung. Wir haben die meisten Aufgaben über die Dekompositionsbeziehung abgebildet, während wir sonst eher die Subclassbeziehung benutzen.

Bild 2: Aufgabe Tactical Information Management: Auch hier wieder Planung, Steuerung und Überwachung. Auf einer anderen Ebene Project Completion und die Execution.

Bild 3: Aufgabe Operatives Informationsmanagement. Hier sind auch wieder verschiedene Dinge untergeordnet. Beispielsweise Risk Management. Auch diese Aufgabe hängt an dem übergeordneten Konzept Information Management. Steuerung fehlt hier.

Bild 4: Andere Perspektive, Star auf Management Function. Auch hier wieder die Dekompositionsbeziehung. Vorschlag, Monitoring und Directing Aufgaben vom Informationsmanagement entweder als Subclass oder per decompose unterordnen.
AW: Dann müsste man aber beides erledigen. Dann müsste Informationsmanagement auch Subclass of Management sein.
FJ: Ja, Beziehung zwischen Information Management und Management. Auch Planung, Steuerung und Überwachung.
AW: Taktische , Strategische und Operative Planung muss alles unter Planung hängen dann. Aber dann gibt es eventuell zuviele Kanten.
TP: Overplotting ist generelles Problem aber sollte nicht davon abhalten, korrekte Beziehungen zu modellieren.


@FranziskaJahn: Bitte die Screenshots noch in die Issue einfügen. Geht per drag and drop ganz bequem.
@KonradHoeffner:
- [ ] Add Triple: bb:InformationsManagement subClassOf bb:Management
- [ ] Remove Triple: Planning subClassof Management Function (component existiert bereits)
- [ ] Add Quality Check for two classes that are connected both via subclassOf and also via component relation, possibly in the other direction. If there are more occurences, decide manually about those.
@ThomasPause:
- research "disjunctive" properties

**Comment by KonradHoeffner** [comment]
Momentan gibt es 96 direkte Unterklassen von bb:InformationManagement:

```
SELECT COUNT(DISTINCT(?u))
{
 ?u rdfs:subClassOf bb:InformationManagement.
}
```

**Comment by KonradHoeffner** [comment]
Unterklassen tiefer hängen ausgelagert in https://github.com/IMISE/snik-ontology/issues/366.
