### ISSUE TITLE
ciox:ChiefInformationOfficer meta:isResponsibleForFunction ciox:Projektleiter v2018-10-22

### ISSUE THREAD

**Issue by FranziskaJahn** [IMISE/snik-ontology#194]
The edge "ciox:ChiefInformationOfficer meta:isResponsibleForFunction ciox:Projektleiter" is incorrect.

**Details**
IsResponsibleForFunction wird hier zwischen zwei Rollen benutzt. Bitte entfernen.

**Comment by KonradHoeffner** [comment]
Ist eine range violation, die sollten generell mal behoben werden:

https://imise.github.io/snik-ontology/2017/06/01/qualitycheck/#range-violation

**Comment by T-P-1** [comment]
done.

**Comment by T-P-1** [comment]
for range violation workaround see #181
