### ISSUE TITLE
Subclass cycle in bb: HospitalStaff -> CIO -> InformationManagementStaff -> HospitalStaff

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#195]
Das kann doch nicht richtig sein. Ich denke, HospitalStaff subClassOf CIO muss weg. Was sagt ihr?

![subclass-cycle](https://user-images.githubusercontent.com/839577/48542729-36780400-e8c0-11e8-8cb5-800cb5b1f334.png)

**Comment by FranziskaJahn** [comment]
Ja, das muss weg.

**Comment by KonradHoeffner** [comment]
Done.
