### ISSUE TITLE
http://www.snik.eu/ontology/ob/SystemAnalysis

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#199]
The class http://www.snik.eu/ontology/ob/SystemAnalysis has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Bitte ein closematch zu http://www.snik.eu/ontology/he/Informationssystemanalyse

**Comment by LudwigWermke** [comment]
done

**Comment by LudwigWermke** [comment]
@AlfredWinter 
ist hinzugefügt, ist das so in Ordnung?

**Comment by AlfredWinter** [comment]
0k
