### ISSUE TITLE
he:Anwendungssystem skos:closeMatch ob:ApplicationSystem v2018-10-22

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#203]
The edge "he:Anwendungssystem skos:closeMatch ob:ApplicationSystem" is incorrect.

**Details**
nicht ganz richtig. Der Closematch muss gehe zu: http://www.snik.eu/ontology/ob/ComputerBasedApplicationSystem

**Comment by AnnaLoerke** [comment]
done.
