### ISSUE TITLE
http://www.snik.eu/ontology/meta/ApplicationComponent

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#204]
The class http://www.snik.eu/ontology/meta/ApplicationComponent has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Wozu braucht man das, wenn es schon http://www.snik.eu/ontology/bb/ApplicationComponent gibt. Zusammenführen und dabei auf meta verzichten?

**Comment by AnnaLoerke** [comment]
vgl #204?

**Comment by AlfredWinter** [comment]
Das hier ist #204. Welcher Link war gemeint?

**Comment by AlfredWinter** [comment]
Ergründen, wo es benutzt wird und wie oft. Suchen, wie oft die Relationen meta:supports und meta:communicatesWith vorkommen, da diese fälschlicherweise benutzt werden können.

Tripel hinzufügen: bb:ApplicationComponent (und equivalente Klasse anderer Unterontologien) und per rdfs:subClassOf an meta:ApplicationComponent hängen.

**Comment by FranziskaJahn** [comment]
Erledigt durch Ludwig und Konrad.
