### ISSUE TITLE
http://www.snik.eu/ontology/meta/ComputerBasedApplicationComponent

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#205]
The class http://www.snik.eu/ontology/meta/ComputerBasedApplicationComponent has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Wozu brauche ich das als meta, wenn es das auch 'richtig' gibt: http://www.snik.eu/ontology/bb/ComputerBasedApplicationComponent. Zusammenführen?

**Comment by KonradHoeffner** [comment]
Wir brauchen es auf der Metaebene. Das Konzept finden wir auch in der Literatur.
Im ob weichen die Bezeichnungen etwas ab.

bb:PatientDataManagementSystem rdfs:subClassOf bb:ComputerBasedApplicationComponent.

Wir haben hier ein Konzept aus dem blauen Buch auf die Metaebene gehoben. Daher erlauben wir eine besondere Beziehung zwischen allen Knoten die daran hängen.

**Comment by KonradHoeffner** [comment]
So wie ich das interpretiere, müssen alle die beiden BB Klassen, die an meta:ComputerBasedApplicationComponent hängen, auf bb:ComputerBasedApplicationComponent umgehängt werden. Wenn da noch etwas zu erledigen ist, bitte eine neue Issue eröffnen mit den gewünschten Änderungen.

```
SELECT ?x from sniko:bb
{
 ?x rdfs:subClassOf meta:ComputerBasedApplicationComponent.
 FILTER(?x!=bb:ComputerBasedApplicationComponent)
}
```

x
--
http://www.snik.eu/ontology/bb/IntegrationTechnology
http://www.snik.eu/ontology/bb/PatientDataManagementSystem

**Comment by KonradHoeffner** [comment]
Done

**Comment by AlfredWinter** [comment]
Ich habe nicht verstanden, was jetzt gemacht wurde. Bitte noch einmal beim JourFixe erklären. 
AW
