### ISSUE TITLE
he:SAN skos:closeMatch bb:San

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#214]
The edge "he:SAN skos:closeMatch bb:San" is incorrect.

**Details**
Das bestätige ich.

**Comment by KonradHoeffner** [comment]
@LudwigWermke Bitte diese Kante entfernen. Das ist eine gute Übungsaufgabe.

**Comment by LudwigWermke** [comment]
Kante wie gewünscht bestätigt; 
fraglich, warum es im BB sowohl bb:San als auch bb:StorageAreaNetwork als close match gibt, was schlussfolgern lässt, dass bb:San und bb:StorageAreaNetwork das gleiche Konzept beschreiben
Mergen? Ja/Nein + welche Modellierung?

**Comment by AlfredWinter** [comment]
Ja, mergen. als Entitiy-Typ
AW

**Comment by AnnaLoerke** [comment]
done.

**Comment by KonradHoeffner** [comment]
Einige Tripel wurden vergessen umzubenennen, habe das jetzt nachgeholt.
