### ISSUE TITLE
he:Efficiency skos:closeMatch bb:Efficiency

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#215]
The edge "he:Efficiency skos:closeMatch bb:Efficiency" is incorrect.

**Details**
Das bestätige ich.

**Comment by KonradHoeffner** [comment]
@LudwigWermke Bitte diese Kante entfernen.

**Comment by LudwigWermke** [comment]
automatische Referenz entfernt und neu integriert

**Comment by KonradHoeffner** [comment]
Die Kante sollte doch entfernt werden, nicht hinzugefügt, ich korrigiere das mal.

**Comment by KonradHoeffner** [comment]
Wenn ich mir die Definitionen ansehe kommt mir das schon ziemlich gleich vor.
