### ISSUE TITLE
http://www.snik.eu/ontology/bb/Efficiency

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#216]
The class http://www.snik.eu/ontology/bb/Efficiency has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
bitte auch close match zu http://www.snik.eu/ontology/he/Effizienz

**Comment by KonradHoeffner** [comment]
@LudwigWermke Bitte die Kante <http://www.snik.eu/ontology/bb/Efficiency> skos:closeMatch <http://www.snik.eu/ontology/he/Effizienz> zum bb Graphen hinzufügen.

**Comment by LudwigWermke** [comment]
hinzugefügt und außerdem die Übersetzung noch eingefügt
