### ISSUE TITLE
he:ChangeRequest skos:closeMatch ob:ChangeRequest

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#217]
The edge "he:ChangeRequest skos:closeMatch ob:ChangeRequest" is incorrect.

**Details**
bstätige ich

**Comment by KonradHoeffner** [comment]
@LudwigWermke Bitte diese Kante entfernen.

**Comment by LudwigWermke** [comment]
automatische Kennzeichnung entfernt und in HE-graph integriert

**Comment by KonradHoeffner** [comment]
> automatische Kennzeichnung entfernt und in HE-graph integriert

Das klingt als wäre die Kante hinzugefügt worden und nicht wie angefragt entfernt, aber da die Kante tatsächlich nicht mehr da ist lasse ich die issue zu.
