### ISSUE TITLE
http://www.snik.eu/ontology/ciox/Etat

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#218]
The class http://www.snik.eu/ontology/ciox/Etat has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Es gibt einige Klassen die mit Budget zu tun haben, z.B.:
- http://www.snik.eu/ontology/ob/ProjectBudget
- http://www.snik.eu/ontology/he/Budget
- http://www.snik.eu/ontology/bb/AnnualITBudget
- http://www.snik.eu/ontology/ciox/Etat

Das ist aber nicht immer dasselbe, selbst dann, wenn die Namen gleich sind. Bitte prüfen, ob hier Hierarchien hin müssen und wo wirklich ein closematch hingehört.

**Comment by FranziskaJahn** [comment]
Die jetzt vorhandenen Verbindungen sind i. O.
