### ISSUE TITLE
http://www.snik.eu/ontology/ob/Bid

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#220]
The class http://www.snik.eu/ontology/ob/Bid has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
bitte CloseMatch zu http://www.snik.eu/ontology/he/Angebot

**Comment by LudwigWermke** [comment]
hinzugefügt
