### ISSUE TITLE
http://www.snik.eu/ontology/he/Informationssystem

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#221]
The class http://www.snik.eu/ontology/he/Informationssystem has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Bitte im Buch die Definition suchen und hier einfügen. Anschließend in der Gruppe diskutieren, welche Beziehung zu den ähnlichen Begriffen (Informationssystem) im bb und ob besteht. Das ist nicht sicher ein close match.

**Comment by KonradHoeffner** [comment]
Welcher close Match ist hier gemeint? Der zu ob oder der zu bb?

**Comment by KonradHoeffner** [comment]
Das Problem ist, dass he von verschiedenen Authoren geschrieben wurde. Im Schlagwortverzeichnis ist es nicht enthalten, aber Informationsinfrastruktur, Kapitel ARCHI. 

Es ist jetzt konsolidiert, beide Teile vereinigen.

Wir entfernen die closeMatches zu bb und ob InformationSystem und fügen closeMatches zu rechnerbasiertem Anwendungssystem http://www.snik.eu/ontology/bb/ComputerBasedApplicationComponent im bb und computerbasierte Anwendungssystem https://www.snik.eu/ontology/ob/ComputerBasedApplicationSystem im ob.

**Comment by KonradHoeffner** [comment]
Done

**Comment by AlfredWinter** [comment]
ok. dann haben wir jetzt - wie besprochen - für die Ewigkeit dokumentiert, dass Heinrich mit "Informationssystem" eigentlich ein Anwendeungssystem meint. Hoffen wir, dass wir recht haben. Ich habe fast Angst vor eigenen Courage.
