### ISSUE TITLE
http://www.snik.eu/ontology/he/Projektportfolio

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#222]
The class http://www.snik.eu/ontology/he/Projektportfolio has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
das ist ein entity type. Bitte 'rundherum' prüfen, ob der Typ geändert werden kann.

**Comment by AnnaLoerke** [comment]
done.
