### ISSUE TITLE
he:PMBOK skos:closeMatch bb:Pmbok

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#223]
The edge "he:PMBOK skos:closeMatch bb:Pmbok" is incorrect.

**Details**
bestätige ich

**Comment by KonradHoeffner** [comment]
@LudwigWermke: Bitte diese Kante entfernen.

**Comment by LudwigWermke** [comment]
solved

**Comment by AlfredWinter** [comment]
wiederherstellen!

**Comment by AlfredWinter** [comment]
:-)
