### ISSUE TITLE
http://www.snik.eu/ontology/he/KeyPerformanceIndicator

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#224]
The class http://www.snik.eu/ontology/he/KeyPerformanceIndicator has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Das ist identisch mit http://www.snik.eu/ontology/he/KPI . Bitte zu einer Klasse zusammenführen.

**Comment by KonradHoeffner** [comment]
@AnnaLoerke, kannst du @LudwigWermke zeigen wie man zwei Klassen merged?

**Comment by AnnaLoerke** [comment]
done. 

Hier gab es nicht zu mergen, da die Inhalte/Relationen komplett identisch waren. Zeige es gerne bei einem anderen Beispiel.

**Comment by AlfredWinter** [comment]
heißt das, eins konnte einfach gelöscht werden?

**Comment by AnnaLoerke** [comment]
genau. Das habe ich auch schon gemacht.
