### ISSUE TITLE
he:Infrastrukturanalyse meta:uses he:ItDiagnose

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#228]
The edge "he:Infrastrukturanalyse meta:uses he:ItDiagnose" is incorrect.

**Details**
verstoß gegen metamodell

**Comment by KonradHoeffner** [comment]
@AnnaLoerke: Bitte entscheiden, was damit passieren soll: Muss die Kante gelöscht werden oder passt hier eine andere Property?

**Comment by AnnaLoerke** [comment]
functionComponent wäre die mögliche Relation. Soll das entsprechend geändert werden?

**Comment by BirgitSNIK** [comment]
Mein Vorschlag:
ItDiagnose subClassOf Infrastrukturanalyse
 
Von: AnnaLoerke <notifications@github.com> 
Gesendet: Dienstag, 16. April 2019 10:58
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: BirgitSNIK <birgit.schneider@imise.uni-leipzig.de>; Assign <assign@noreply.github.com>
Betreff: Re: [IMISE/snik-ontology] he:Infrastrukturanalyse meta:uses he:ItDiagnose (#228)
 
functionComponent wäre die mögliche Relation. Soll das entsprechend geändert werden?

**Comment by KonradHoeffner** [comment]
Damit das nicht weiter verschleppt wird, setze ich jetzt Birgits Vorschlag um und schließe diese Issue. Wenn jemand etwas dagegen hat, bitte wieder aufmachen und melden.
