### ISSUE TITLE
http://www.snik.eu/ontology/he/Informationsinfrastruktur

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#229]
The class http://www.snik.eu/ontology/he/Informationsinfrastruktur has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Typ ist falsch, müsste eigentlich entity sein. Bitte umfeld prüfen!

**Comment by AnnaLoerke** [comment]
@KonradHoeffner Darf isAssociatedWith zwischen einer Funktion und einem Entity Type vorliegen?

**Comment by AlfredWinter** [comment]
im prinzip ja. Aber vielleicht passt ja eine andere Beziehung aus dem Metamodell.

**Comment by AnnaLoerke** [comment]
Es gibt einige Inverse-Relationen mit rdfs:domain. Diese sind ja nicht Teil des Meta-Modells. Sollen die so bleiben?

**Comment by AlfredWinter** [comment]
Diskutieren

**Comment by AnnaLoerke** [comment]
Es geht um he:Informationsinfrastruktur (Entity Type) meta:isAssociatedWith he:Strukturmanagement (Funktion). @BirgitSNIK meinst du da passt uses oder updates?

**Comment by AnnaLoerke** [comment]
Informationsinfrastruktur ist jetzt nur noch ein Entity Type.

**Comment by KonradHoeffner** [comment]
@AnnaLoerke: `meta:isAssociatedWith` ist (siehe Metamodell) zwischen Top und Top definiert, also zwischen allen SNIK Klassen. Allerdings ist es so eine Art Resterelation für Fälle, in denen nichts anderes passt. Es ist aber immer besser, wenn man eine andere, spezifischere Relation finden kann.

**Comment by KonradHoeffner** [comment]
Da es jetzt ein entity type ist, nehme ich an, dass die Issue erledigt ist und schließe sie.
