### ISSUE TITLE
http://www.snik.eu/ontology/bb/OpenEHR (subClassOf) http://www.snik.eu/ontology/bb/Organization v2016-10-04

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#23]
The edge "http://www.snik.eu/ontology/bb/OpenEHR (subClassOf) http://www.snik.eu/ontology/bb/Organization" is incorrect.

**Details**
Das stimmt nicht.

**Comment by KonradHoeffner** [comment]
Herausfinden, was die korrekte Superklasse ist.

**Comment by KonradHoeffner** [comment]
Da es sehr viele solche Ressourcen ohne nicht-subtop-Superklasse gibt, schließe ich das hier, vielleicht kann man später mal eine gesammelte Aktion starten.
