### ISSUE TITLE
Virtuelle Triple?

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-ontology#233]
Wenn man im RelFinder zwei Begriffe verbindet (bsp. bb:CIO und bb:HospitalStaff), bekommt man als Kanten "annotatedSource" und "annotatedTarget" sowie den Knoten "no link availble for" angezeigt.

**Comment by AnnaLoerke** [comment]
Ich glaube das haben wir neulich gelöst, oder? Das dürften die Axiome sein, die der RelFinder einfach nicht anzeigen kann.

**Comment by KonradHoeffner** [comment]
Ja das sind Axiome, die z.B. Seitenzahlen für Tripel enthalten. Soweit ich weiß hat RelFinder aber eine blacklist für properties, dort müsste man annotatedSource und annotatedTarget hinzufügen können.

**Comment by KonradHoeffner** [comment]
Klären:

Anzahl von:
- [ ] Axiomen
- [ ] Annotations
- [ ] Restrictions
- [ ] Seitenzahlen
