### ISSUE TITLE
closeMatch- nur in eine Richtung? welche?

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-ontology#234]
closeMatch findet sich häufiger in beide Richtungen zwischen zwei Knoten (bsp. Informationsmanagement im bb und ob). Konrad wünscht für die bessere Lesbarkeit in der Visualisierung nur ein closeMatch in eine Richtung. Wie kann die Regel für die Richtung aussehen?

**Comment by AnnaLoerke** [comment]
Besprechung 29.01.19: Richtung egal. Man muss im LodView dann immer sowohl die ausgehenden Relationen, als auch die inversen Relationen bezüglich eines closeMatch betrachten, um alle Verbindungen zu sehen.

**Comment by KonradHoeffner** [comment]
Ich mache das mal wieder auf, da es immer noch 65 solche doppelten closeMatches gibt:

```
select count(*)
{
 ?x skos:closeMatch ?y.
 ?y skos:closeMatch ?x.
 filter(?x<?y)
}
```

**Comment by KonradHoeffner** [comment]
Sind in folgenden Graphen:

```
select ?g ?h count(*)
{
 graph ?g {?x skos:closeMatch ?y.}
 graph ?h {?y skos:closeMatch ?x.}
 filter(?x<?y)
 filter(?g!=<ludwig>)
 filter(?h!=<ludwig>)
}
```
 g|h | count
-- | -- | --
http://www.snik.eu/ontology/bb | http://www.snik.eu/ontology/limes-exact | 61
http://www.snik.eu/ontology/limes-exact | http://www.snik.eu/ontology/bb | 1
http://www.snik.eu/ontology/bb | http://www.snik.eu/ontology/match | 2
http://www.snik.eu/ontology/bb | http://www.snik.eu/ontology/ciox | 1

**Comment by KonradHoeffner** [comment]
bb -- limes-exact

```
delete
{
 graph <http://www.snik.eu/ontology/bb> {?x skos:closeMatch ?y.}
 graph <http://www.snik.eu/ontology/limes-exact> {?y skos:closeMatch ?x.}
}
insert
{
 graph <http://www.snik.eu/ontology/match> {?x skos:closeMatch ?y.}
}
where
{
 graph <http://www.snik.eu/ontology/bb> {?x skos:closeMatch ?y.}
 graph <http://www.snik.eu/ontology/limes-exact> {?y skos:closeMatch ?x.}
}
```

**Comment by KonradHoeffner** [comment]
bb -- match

```
delete
{
 graph <http://www.snik.eu/ontology/bb> {?x skos:closeMatch ?y.}
}
where
{
 graph <http://www.snik.eu/ontology/bb> {?x skos:closeMatch ?y.}
 graph <http://www.snik.eu/ontology/match> {?y skos:closeMatch ?x.}
}
```

**Comment by KonradHoeffner** [comment]
bb -- ciox

```
delete
{
 graph <http://www.snik.eu/ontology/bb> {?x skos:closeMatch ?y.}
}
where
{
 graph <http://www.snik.eu/ontology/bb> {?x skos:closeMatch ?y.}
 graph <http://www.snik.eu/ontology/match> {?y skos:closeMatch ?x.}
}
```

Done
