### ISSUE TITLE
bb:StrategicInformationManagementPlan = IT-Rahmenplan?

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-ontology#235]
http://www.snik.eu/ontology/bb/StrategicInformationManagementPlan

Ist die Übersetzung richtig? Im ob ist StrategicInformationManagementPlan mit Rahmenplan übersetzt.

**Comment by FranziskaJahn** [comment]
Die korrekte Übersetzung wäre "Strategischer Rahmenplan des Informationsmanagements".
Als Synonyme noch ergänzen: IT-Strategie, Rahmenplan

**Comment by AnnaLoerke** [comment]
done.
