### ISSUE TITLE
ob:CommunicationInterface meta:isAssociatedWith ob:CommunicationLink

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#237]
The edge "ob:CommunicationInterface meta:isAssociatedWith ob:CommunicationLink" is incorrect.

**Details**
Bitte mit einer Teil-Von Beziehung (schnittstelle ist Teil von Verbindung) modellieren. AW

**Comment by AnnaLoerke** [comment]
done.
