### ISSUE TITLE
bb:StorageAreaNetwork meta:supports bb:StorageService

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#239]
The edge "bb:StorageAreaNetwork meta:supports bb:StorageService" is incorrect.

**Details**
http://www.snik.eu/ontology/bb/StorageAreaNetwork ist kein application system, also ist diese Beziehung nicht zulässig. 
Diskussion erforderlich, ob wir auch Physische Werkzeuge hier erlauben und das im Metamodell ergänzen.

**Comment by AlfredWinter** [comment]
Beschreibung von Architekturen gehört nicht dazu. Keine Function wie sonst verwendet. Nur im Text beschreibbar. Raus aus den Tripeln, rein in die Definition.

**Comment by KonradHoeffner** [comment]
@FranziskaJahn @BirgitSNIK: Kann einer von euch die Definition aktualisieren? Wenn euch das zu umständlich ist, könnt ihr mir auch einfach den Text schicken und ich baue das selbst ein.

**Comment by KonradHoeffner** [comment]
Habe es jetzt selbst geändert:

Rein: `skos:definition "A network that provides storage services of different kinds to all servers integrated in the network."@en;`

Raus: `meta:supports bb:StorageService ;`
