### ISSUE TITLE
http://www.snik.eu/ontology/bb/Enterprise_Resource_Planning_System (typicalFeature) http://www.snik.eu/ontology/bb/Feature_Provide_means_for_general_ledger_accounting v2016-10-04

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#24]
The edge "http://www.snik.eu/ontology/bb/Enterprise_Resource_Planning_System (typicalFeature) http://www.snik.eu/ontology/bb/Feature_Provide_means_for_general_ledger_accounting" is incorrect.

**Details**
Es sind noch die Features drin. Sollten die nicht raus?
AW

**Comment by KonradHoeffner** [comment]
Die Visualisierung stellt die Ontologieversion vom 4.10.2016 dar (siehe Titel), dort sind die features noch drin. Ich bin gerade dabei, die neue Ontologieversion 0.3.0 in die Visualisierung zu bringen.
