### ISSUE TITLE
he/ChiefInformationOfficer

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-ontology#240]
Der he/ChiefInformationOfficer hat einige Fehler im Aufbau seiner Daten. Bitte automatisiert korrigieren!

**Comment by KonradHoeffner** [comment]
Part of and test case for https://github.com/IMISE/snik-ontology/issues/176.

**Comment by AnnaLoerke** [comment]
Für CIO scheint es jetzt zu stimmen. Kann das Ticket geschlossen werden?

**Comment by KonradHoeffner** [comment]
Ja, ich mache es zu.
