### ISSUE TITLE
Inverse Relationen zwischen Informationsmanagement und Spezialisierungen

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-ontology#241]
Aktuell gibt es jeweils eine Relation functionComponent von http://www.snik.eu/ontology/bb/InformationManagement zu operatives, strategisches und taktisches Informationsmanagement. Die drei haben jedoch zusätzlich die Beschreibung in die andere Richtung als isSubclassOf. Welche Richtung ist erwünscht?

**Comment by FranziskaJahn** [comment]
Ich denke, es handelt sich hier um eine Zerlegung und nicht um eine Spezialisierung. Infosern sollte es nur die "functionComponent"-Beziehung geben.

**Comment by AnnaLoerke** [comment]
done.
