### ISSUE TITLE
http://www.snik.eu/ontology/he/Kommunikation

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-ontology#243]
http://www.snik.eu/ontology/he/Kommunikation ist als entityType und als Funktion modelliert. Vermutlich ist Funktion für das Umfeld korrekt und sollte entsprechend ummodelliert werden.

Außerdem gibt es eine inverseRelation als closeMatch zu it:Kommunikation. Da it nicht mehr öffentlich ist und man somit auch keine Informationen dazu bekommt, sollte diese Relation im LodView nicht angezeigt werden. @KonradHoeffner ist das zu realisieren?

**Comment by KonradHoeffner** [comment]
Das berührt ein generelles Problem, das ich gerne mal diskutieren möchte: In welchem Graphen sollen interlinks gespeichert werden?

Da die skos Interlink-Relationen entweder symmetrisch sind (close match, exact match, related) oder sowohl antisymmetrisch als auch einen inversen Partner haben (narrow - broad) (@LudwigWermke: Du bist doch Mathematiker, korrigiere mich, falls ich das falsch ausgedrückt habe), würde redundante Information entstehen, wenn wir beides abbilden würden.

Daher modellieren wir immer nur eine Richtung, die andere gilt dann implizit, sonst würde das auch die Visualisierung überladen und Änderungen erschweren, da immer beide Elemente eines Paares zusammen geändert werden müssten und  Konsistenzprobleme auftauchen könnten.

Als Speicherort haben wir bis jetzt meist den Graph genommen, der das Subjekt des Linktripels enthält, auch wenn es in diesem Fall hier andersherum zu sein scheint.

Bei neuen haben Anna und ich letztens angefangen, bestätigte Interlinks in den Graph <http://www.snik.eu/ontology/match> zu legen, damit man beim editieren nicht erst den Graph suchen muss und das alles an einem Ort hat. Jetzt gibt es aber das Problem mit der IT-Subontologie wegen der fehlenden Lizenz.

Am einfachsten wäre es eigentlich, nochmal bei den IT-Quellen-Publishern zu fragen ob wir das nicht doch veröffentlichen könnten, denn diese ganzen Probleme kommen nur daher, dass diese eine Teilontologie nicht öffentlich sein darf.

Ansonsten wäre eine Lösung, für jedes Paar von graphen einen extra Paargraph zu erstellen, aber die Zahl der Paargraphen skaliert quadratisch mit der Anzahl der Graphen und das wäre allgemein sehr umständlich.

Ich würde es daher vorziehen, alles in den neuen Matchgraphen zu legen. Ist es denn schlimm, wenn da ein paar IT-Links drin sind? Man könnte die ja auch alle Interlinks mit einem Ende im IT Graph in den IT Graphen schieben, dann sind die alle dort versteckt, das wäre vielleicht die einfachste gründliche Lösung.

**Comment by AnnaLoerke** [comment]
#234

**Comment by KonradHoeffner** [comment]
Ich splitte die Issue mal auf, da es zwei verschiedene Aufgaben enthält, einmal he:Kommunikation und einmal den Graph von Interlinks.

**Comment by KonradHoeffner** [comment]
Wir nehmen jetzt erstmal den match Graph für Interlinks. Ich nehme mal an, dass das keine Lizenzprobleme hervorruft, da Links ja nur die URLs enthalten und keinerlei Details über die betreffenden Ressourcen.

Daher kann diese Issue jetzt auch bleiben, sie ist jetzt nur noch für das Remodelling von he:Kommunikation da, wie ursprünglich gedacht.

@FranziskaJahn, @BirgitSNIK: Anna ist ja nicht mehr da, daher spiele ich euch den Ball wieder zu.

**Comment by KonradHoeffner** [comment]
Aus der Klasse Kommunikation einen EntityType machen.
Beziehungen für Funktionen entfernen:
- meta:uses beziehung
- Komplette Klasse "EmpfangenderBotschaft" entfernen
