### ISSUE TITLE
http://www.snik.eu/ontology/bb/SystemAnalysis

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#248]
The class http://www.snik.eu/ontology/bb/SystemAnalysis has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Bitte closeMatch zu http://www.snik.eu/ontology/he/Systemanalyse

**Comment by AnnaLoerke** [comment]
done.
