### ISSUE TITLE
nicht meta properties in Definition der Domäne packen

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#251]

**Comment by AnnaLoerke** [comment]
Beispiel siehe #229

**Comment by KonradHoeffner** [comment]
```
select distinct(?p) count(*)
{
 ?s ?p ?o.
 filter(strstarts(str(?p),"http://www.snik.eu/ontology/"))
 filter(!strstarts(str(?p),"http://www.snik.eu/ontology/meta/"))
} order by desc(count(*))
```


p | callret-1
-- | --
http://www.snik.eu/ontology/he/page | 3660
http://www.snik.eu/ontology/ob/tripelPage | 2954
http://www.snik.eu/ontology/bb/tripelPage | 2311
http://www.snik.eu/ontology/bb/page | 622
http://www.snik.eu/ontology/bb/conceptDomain | 424
http://www.snik.eu/ontology/it4it/keyDataObject | 28
http://www.snik.eu/ontology/it4it/page | 18
http://www.snik.eu/ontology/it4it/purpose | 13
http://www.snik.eu/ontology/it4it/mainFunctions | 10
http://www.snik.eu/ontology/it4it/serviceModelBackboneDataObject | 9
http://www.snik.eu/ontology/it4it/auxiliaryFunctionalComponent | 8
http://www.snik.eu/ontology/ob/conceptDomain | 8
http://www.snik.eu/ontology/it4it/entityRelationship | 5
http://www.snik.eu/ontology/it4it/keyFunctionalComponent | 5
http://www.snik.eu/ontology/it4it/auxiliaryDataObject | 1
http://www.snik.eu/ontology/it4it/dataObject | 1
http://www.snik.eu/ontology/it4it/ontologyUse | 1
http://www.snik.eu/ontology/it4it/ontologyUser | 1
http://www.snik.eu/ontology/bb/isNeededFor | 1
http://www.snik.eu/ontology/it4it/policyToRequirementFunctionalComponent | 1
http://www.snik.eu/ontology/it4it/policy | 1
http://www.snik.eu/ontology/it4it/recordFabricIntegration | 1
http://www.snik.eu/ontology/it4it/ontologyDomain | 1
http://www.snik.eu/ontology/ob/page | 1
http://www.snik.eu/ontology/it4it/assetsAvailability | 1
http://www.snik.eu/ontology/it4it/competencyAvailability | 1
http://www.snik.eu/ontology/it4it/conceptualServiceBlueprint | 1
http://www.snik.eu/ontology/it4it/currentPracticeEngagementDataflow | 1
http://www.snik.eu/ontology/it4it/engagementDataflow | 1
http://www.snik.eu/ontology/it4it/functionalComponent | 1
http://www.snik.eu/ontology/it4it/policyToConceptualService | 1
http://www.snik.eu/ontology/it4it/portfolioBacklogItem | 1
http://www.snik.eu/ontology/it4it/portfolioBacklogItemRationalizedPrioritzed | 1
http://www.snik.eu/ontology/it4it/scopeAgreement | 1
http://www.snik.eu/ontology/it4it/serviceArchitectureToConceptualService | 1
http://www.snik.eu/ontology/it4it/ontologyQuestionTypes | 1

**Comment by KonradHoeffner** [comment]
Without it4it:

```
select distinct(?p) count(*)
{
 ?s ?p ?o.
 filter(strstarts(str(?p),"http://www.snik.eu/ontology/"))
 filter(!strstarts(str(?p),"http://www.snik.eu/ontology/meta/"))
 filter(!strstarts(str(?p),"http://www.snik.eu/ontology/it4it/"))
} order by desc(count(*))
```

p | callret-1
-- | --
http://www.snik.eu/ontology/he/page | 3660
http://www.snik.eu/ontology/ob/tripelPage | 2954
http://www.snik.eu/ontology/bb/tripelPage | 2311
http://www.snik.eu/ontology/bb/page | 622
http://www.snik.eu/ontology/bb/conceptDomain | 424
http://www.snik.eu/ontology/ob/conceptDomain | 8
http://www.snik.eu/ontology/bb/isNeededFor | 1
http://www.snik.eu/ontology/ob/page | 1

**Comment by KonradHoeffner** [comment]
```
select *
{
 ?s bb:isNeededFor ?o.
}
```

**Comment by KonradHoeffner** [comment]
```
SPARQL
with <http://www.snik.eu/ontology/bb>
delete data
{
bb:PhysicalDataProcessingSystem bb:isNeededFor	bb:ApplicationComponent.
}

```
Delete from <http://www.snik.eu/ontology/bb>, 1 (or less) triples -- done

**Comment by KonradHoeffner** [comment]
```
SPARQL with <http://www.snik.eu/ontology/bb>
delete {bb:isNeededFor ?y ?z.}
where {bb:isNeededFor ?y ?z.}
```
