### ISSUE TITLE
SNIK-Daten scheinbar nicht erreichbar

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-ontology#254]
Ich kann aktuell weder den Graphen laden (Fehlermeldung: "Error initializing SNIK Graph undefined") noch einzelne Seiten im LodView angucken. Scheinbar ist irgendwas am Endpunkt oder ähnliches defekt.

**Comment by KonradHoeffner** [comment]
Der Virtuoso ist gerade nicht erreichbar. @SebStaeubert: Kannst du das mal ansehen?

**Comment by KonradHoeffner** [comment]
Funktioniert wieder!
