### ISSUE TITLE
ob:ProjectManager ob:approves ob:ChangeRequest

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#265]
The edge "ob:ProjectManager ob:approves ob:ChangeRequest" is incorrect.

**Details**
Muss approvesEntityType sein

**Comment by AnnaLoerke** [comment]
done.

Zusätzlich identischen Fehler mit ob:ProjectSteeringCommittee ob:approves ob:ChangeRequest  korrigiert.
