### ISSUE TITLE
he:Auftragnehmer skos:closeMatch ob:Contractor

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#268]
The edge "he:Auftragnehmer skos:closeMatch ob:Contractor" is incorrect.

**Details**
Das ist nicht ganz genau dasselbe. Welche Skos-Beziehung gibt sowas wieder?

**Comment by FranziskaJahn** [comment]
Ich würde sagen, closeMatch passt hier gut. Es ist in beiden Büchern der Auftragnehmer gemeint. Evtl. ist "Contractor" einfach die falsche Übersetzung für Auftragnehmer?

**Comment by AlfredWinter** [comment]
Es ist zwar beide Male der Auftragnehmer. Aber einmal ist es der Projektleiter als Auftragnehmer für das Projekt und einmal scheint es mir der Auftragnehmer bei der Lieferung eines Produktes zu sein.

**Comment by FranziskaJahn** [comment]
Die Definition ist bei Heinrich zunächst sehr weit gefasst, erst die Beispiel deuten darauf hin, dass er etwas anderes meinen könnte: "natürliche oder juristische Person die einen Auftrag übernimmt und in der Regel auch durchführt (Hersteller, Softwarehaus, Systemhaus)" 
Wenn man in den Text reinliest, merkt man, dass er immer den Hersteller meint und nicht den internen Auftragnehmer in Form der IT-Abteilung. Also könnte man hier evtl. zu relatedMatch "abmildern".

**Comment by KonradHoeffner** [comment]
@AnnaLoerke : Bitte zu relatedMatch ändern.

**Comment by KonradHoeffner** [comment]
done

**Comment by KonradHoeffner** [comment]
Wenn ich mir die Definitionen ansehe kommt mir das schon ziemlich gleich vor.

**Comment by BirgitSNIK** [comment]
Ja, mir auch. Ich verstehe ehrlich gesagt Annas Kommentar nicht. Sind das Elemente, die aus der Ontologie gelöscht wurden? Vielleicht hatten sie ja den falschen Typ.
VG Birgit



 Von:   Konrad Höffner ***@***.***> 
 An:   snikproject/ontology ***@***.***> 
 Kopie:   BirgitSNIK ***@***.***>, Assign ***@***.***> 
 Gesendet:   17.05.2022 10:33 
 Betreff:   [Extern] Re: [snikproject/ontology] he:Auftragnehmer skos:closeMatch ob:Contractor (#268) 


 
Wenn ich mir die Definitionen ansehe kommt mir das schon ziemlich gleich vor.

**Comment by KonradHoeffner** [comment]
Die Elemente sind noch da aber es handelt sich um automatisch mit LIMES erstellte skos:closeMatch interlinks, welche manuell überprüft wurden, um Homonyme (gleichnamige Wörter) mit unterschiedlicher Bedeutung zu entfernen.
Laut dieser Issue soll der Interlink entfernt werden, da es zwei unterschiedliche Begriffe seien, daher habe ich den Link entfernt. Allerdings bin ich der Meinung, der Link war doch richtig, aber ich bin auch kein Domänenexperte.

**Comment by BirgitSNIK** [comment]
Geht es um #238 oder #268?
Mir ist das zu verwirrend!
Birgit


 Von:   Konrad Höffner ***@***.***> 
 An:   snikproject/ontology ***@***.***> 
 Kopie:   BirgitSNIK ***@***.***>, Assign ***@***.***> 
 Gesendet:   17.05.2022 11:42 
 Betreff:   [Extern] Re: [snikproject/ontology] he:Auftragnehmer skos:closeMatch ob:Contractor (#268) 


 
Die Elemente sind noch da aber es handelt sich um automatisch mit LIMES erstellte skos:closeMatch interlinks, welche manuell überprüft wurden, um Homonyme (gleichnamige Wörter) mit unterschiedlicher Bedeutung zu entfernen.
 Laut dieser Issue soll der Interlink entfernt werden, da es zwei unterschiedliche Begriffe seien, daher habe ich den Link entfernt. Allerdings bin ich der Meinung, der Link war doch richtig, aber ich bin auch kein Domänenexperte.

**Comment by KonradHoeffner** [comment]
#268 ist ein Teil von #238. Letzteres fasst mehrere solche falschen Links zusammen. Bei dem hier in #268 bin ich aber der Meinung, dass es nicht unbedingt hätte entfernt werden müssen aber das muss nicht unbedingt heißen dass es rückgängig gemacht werden muss, ich wollte das nur mal notieren falls wir später irgendwann mal darauf zurück kommen sollten. Das Heinrich-Buch ist ja sowieso nicht fertig konsolidiert.

**Comment by BirgitSNIK** [comment]
Aber gerade zu der #268 gibt es doch eine lange Diskussion, in der Franziska erklärt hatte, dass zumindest closeMatch nicht richtig ist. "ähnlich" würde wohl eher zutreffen.
Birgit



 Von:   Konrad Höffner ***@***.***> 
 An:   snikproject/ontology ***@***.***> 
 Kopie:   BirgitSNIK ***@***.***>, Assign ***@***.***> 
 Gesendet:   17.05.2022 13:42 
 Betreff:   [Extern] Re: [snikproject/ontology] he:Auftragnehmer skos:closeMatch ob:Contractor (#268) 


 
#268 ist ein Teil von #238. Letzteres fasst mehrere solche falschen Links zusammen. Bei dem hier in #268 bin ich aber der Meinung, dass es nicht unbedingt hätte entfernt werden müssen aber das muss nicht unbedingt heißen dass es rückgängig gemacht werden muss, ich wollte das nur mal notieren falls wir später irgendwann mal darauf zurück kommen sollten. Das Heinrich-Buch ist ja sowieso nicht fertig konsolidiert.

**Comment by KonradHoeffner** [comment]
Ja related match ist auch drin momentan, OK dann passt alles so wie es ist.
