### ISSUE TITLE
ob:ItServiceContract meta:roleComponent ob:Contractor

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#270]
The edge "ob:ItServiceContract meta:roleComponent ob:Contractor" is incorrect.

**Details**
wahrscheinlich use oder update

**Comment by AnnaLoerke** [comment]
Das ist beides vermutlich nicht möglich. 

ob:ItServiceContract ist EntityType; ob:Contractor ist Rolle. Daher ist nur ob:Contractor isResponsibleForEntityType oder approvesEntityType ob:ItServiceContract erlaubt.

Generell ist bei ob:ItServiceContract meta:roleComponent ob:Contractor sowie zusätzlich ob:ItServiceContract meta:roleComponent ob:Sponsor nicht erlaubt laut Meta-Modell.

**Comment by AnnaLoerke** [comment]
Identisch zu #269 Daher werde ich Issue 269 schließen.

**Comment by AlfredWinter** [comment]
Dann nehmen wir  approvesEntityType.

**Comment by KonradHoeffner** [comment]
`ob:ItServiceContract meta:roleComponent ob:Contractor.`
geändert zu
`ob:ItServiceContract meta:approvesEntityType ob:Contractor.`
