### ISSUE TITLE
ob:Contractor ob:approves ob:ProjectGoal

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#272]
The edge "ob:Contractor ob:approves ob:ProjectGoal" is incorrect.

**Details**
approves gibt es doch gar nicht im MetaModell. hier passt responsibleforrole besser.

**Comment by AnnaLoerke** [comment]
Meinen Sie isResponsibleForEntityType? ProjectGoal ist ja als EntityType definiert. Außerdem gibt es zusätzlich die Verbindung ob:Sponsor ob:approves ob:ProjectGoal. Soll diese Verbindung identisch verändert werden?

**Comment by AnnaLoerke** [comment]
meta:approvesEntityType wäre auch zulässig.

**Comment by AlfredWinter** [comment]
Dann nehmen wir das doch. 
AW

**Comment by KonradHoeffner** [comment]
Die `ob:approved`-Relation taucht 33 mal auf:

```
select count(*) ?z
{
 ?x ob:approves ?y.
 ?y meta:subTopClass ?z.
}
```

```
callret-0 | z
-- | --
1 | http://www.snik.eu/ontology/meta/Function
32 | http://www.snik.eu/ontology/meta/EntityType
```

**Comment by KonradHoeffner** [comment]
Alle ob:approved Relationen sind jetzt in ob:approvesEntityType, respective ob:approvesFunction umbenannt.
