### ISSUE TITLE
http://www.snik.eu/ontology/he/Projektmanager

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#275]
The class http://www.snik.eu/ontology/he/Projektmanager has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Ist identisch mit http://www.snik.eu/ontology/he/Projektleiter. bitte beide zusammenführen.

**Comment by AnnaLoerke** [comment]
done.
