### ISSUE TITLE
http://www.snik.eu/ontology/bb/ComponentAlignmentModel

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#276]
The class http://www.snik.eu/ontology/bb/ComponentAlignmentModel has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Bitte umbenennen in Comppnent mode ...l "of Martin"

**Comment by AnnaLoerke** [comment]
done.
