### ISSUE TITLE
bb:Ceo missing connections?

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#283]
The definition of http://www.snik.eu/ontology/bb/Ceo is "Responsible for setting and carrying out the strategic plans and policies of an enterprise." but there are no meta:isResponsibleFor... connections from this class to any other.

Possible candidates:

http://www.snik.eu/ontology/bb/StrategicDecision
http://www.snik.eu/ontology/bb/StrategicInformationManagementPlan
http://www.snik.eu/ontology/bb/StrategicGoalOfTheNetwork
http://www.snik.eu/ontology/bb/StrategicAlignmentModel
http://www.snik.eu/ontology/bb/StrategicInformationManagementGoal
http://www.snik.eu/ontology/bb/StrategicHISPlanning
http://www.snik.eu/ontology/bb/StrategicAlignment
http://www.snik.eu/ontology/bb/StrategicInformationManagement
http://www.snik.eu/ontology/bb/StrategicGoalOfTheInstitution
http://www.snik.eu/ontology/bb/StrategicHISMonitoringResult
http://www.snik.eu/ontology/bb/StrategicHospitalGoal
http://www.snik.eu/ontology/bb/StrategicHISMonitoring
http://www.snik.eu/ontology/bb/StrategicHISDirecting
http://www.snik.eu/ontology/bb/UseOfStrategicInformationManagementPlan
http://www.snik.eu/ontology/bb/CreationOfStrategicInformationManagementPlan
http://www.snik.eu/ontology/bb/ApprovalToStrategicInformationManagementPlan
http://www.snik.eu/ontology/bb/UpdatingTheStrategicInformationManagementPlan
http://www.snik.eu/ontology/bb/DeploymentOfStrategicInformationManagementPlan
http://www.snik.eu/ontology/bb/FulfillmentOfStrategicHospitalGoal

**Comment by AlfredWinter** [comment]
NUR:
isResponsibleForEntityType
http://www.snik.eu/ontology/bb/BusinessStrategy

**Comment by KonradHoeffner** [comment]
Hinzugefügt

```
SPARQL
INSERT DATA INTO <http://www.snik.eu/ontology/bb>
{
 bb:ChiefExecutiveOfficer meta:isResponsibleForEntityType bb:BusinessStrategy.
}
```
