### ISSUE TITLE
Zukunft von IT4IT

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#286]
Soll IT4IT eine prominente Rolle im Semantic Web Journal Paper spielen? Es sieht allgemein gut aus aber es gibt noch kleinere Problemchen, lohnt es sich für SNIK, wenn Sebastian da noch einmal nachbessert oder ist IT4IT für den Folgeantrag und das SWJ Paper nicht so relevant?

![snik](https://user-images.githubusercontent.com/839577/53492156-72faf480-3a98-11e9-8bfe-3c63d5e86749.png)

[it4it.json.txt](https://github.com/IMISE/snik-ontology/files/2910369/it4it.json.txt)

**Comment by AlfredWinter** [comment]
Hat ja schon das Label "next meeting". Wir müssen besprechen, wie wir damit umgehen. 
Mir scheint, da wir unser Interesse auf "Wer macht was was womit" fokussiert haben, können wir vor diesem Hintergrund noch einmal an IT4IT herangehen.

**Comment by AlfredWinter** [comment]
Nicht im Paper prominent verwenden.

Workshop mit Sebastian Stäubert durchführen?

**Comment by KonradHoeffner** [comment]
Hat sich erledigt durch KKs Bachelorarbeit.
