### ISSUE TITLE
Wiki aktualisieren 

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-ontology#287]
Die Bearbeitungsregeln im Wiki einfügen und aktualisieren.
Vgl #175

**Comment by KonradHoeffner** [comment]
@ThomasPause: Da Anna nicht mehr da ist, weise ich dir das mal zu.

**Comment by KonradHoeffner** [comment]
Ich mach das mal lieber selber, da ich da wenig nachschlagen muss.

**Comment by KonradHoeffner** [comment]
Habe jetzt https://wiki.imise.uni-leipzig.de/Projekte/SNIK/ontologie/extraktion/relationen erweitert. Ist immer noch nicht perfekt aber da das initiale SNIK Projekt sich ja nicht mehr in der heißen Phase befindet würde ich hier nur bei Bedarf nachbessern. In diesem Fall dann bitte die Issue wieder öffnen oder bei ganz gezielten Sachen eine neue Issue öffnen.
