### ISSUE TITLE
Ergänzungen bb

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-ontology#289]
Im bb bitte folgende Beziehungen einfügen:

Hospital Goals isSubclassOf Strategic Goal of Institution
Hospital Strategic Plan isSubclassOf Business Strategy
Hospital Management isResponsibleFor Hospital Strategic Plan

**Comment by AnnaLoerke** [comment]
Soll "Hospital Strategic Plan" durch bb:HospitalBusinessPlan oder durch bb: StrategicInformationManagementPlan repräsentiert werden?

Hospital Management oder Hospital Management Staff (zukünftig Top Management) verwenden?

**Comment by KonradHoeffner** [comment]
@AlfredWinter: Bitte Bescheid sagen, welche der von Anna vorgeschlagenen Optionen gewählt werden sollen, ich baue das dann ein.

**Comment by AlfredWinter** [comment]
Soll "Hospital Strategic Plan" durch bb:HospitalBusinessPlan oder durch bb: StrategicInformationManagementPlan repräsentiert werden?
Antwort: durch bb:HospitalBusinessPlan
Hospital Management oder Hospital Management Staff (zukünftig Top Management) verwenden?
Antwort: (1) Einfügen:  bb:TopManagement IsResponibleForFunction bb:HospitalManagement
(2) Ändern: bb:HospitalManagement isResponsibleFor bb:HospitalBusinessPlan    ändern zu          bb:HospitalManagement updates bb:HospitalBusinessPlan    
AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      +49 341-97-16107, 
Mobil: +49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
twitter: @MedInfoL
instagram: medinfo.unileipzig
 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Konrad Höffner [mailto:notifications@github.com] 
Gesendet: Dienstag, 24. September 2019 16:21
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Mention <mention@noreply.github.com>
Betreff: Re: [IMISE/snik-ontology] Ergänzungen bb (#289)
 
@AlfredWinter: Bitte Bescheid sagen, welche der von Anna vorgeschlagenen Optionen gewählt werden sollen, ich baue das dann ein.

**Comment by KonradHoeffner** [comment]
Folgende Tripel hinzugefügt:

```
bb:StrategicHospitalGoal rdfs:subClassOf bb:StrategicGoalOfTheInstitution.
bb:HospitalBusinessPlan rdfs:subClassOf bb:BusinessStrategy.
bb:HospitalManagement meta:updates bb:HospitalBusinessPlan.
bb:TopManagement meta:isResponsibleForFunction bb:HospitalManagement.
```
