### ISSUE TITLE
http://www.snik.eu/ontology/he/StrategischeItPlanung

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#298]
The class http://www.snik.eu/ontology/he/StrategischeItPlanung has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Hierzu gibt es einen äquivalenten Begriff im bb. Bitte suchen und nach Möglichkeit CloseMatch herstellen.
AW

**Comment by KonradHoeffner** [comment]
Ich habe auch mal im Blue Book und im SNIK Graph geschaut aber nichts gefunden.

**Comment by KonradHoeffner** [comment]
@BirgitSNIK hat es gefunden: https://www.snik.eu/ontology/bb/StrategicHISPlanning

**Comment by KonradHoeffner** [comment]
Hinzugefügt in 4b2cca9cfa68f53836353fba8e485ca183b3efd4.
