### ISSUE TITLE
http://www.snik.eu/ontology/he/StrategischerItPlan

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#299]
The class http://www.snik.eu/ontology/he/StrategischerItPlan has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Hierzu gibt es äquivalenten Begriff in bb. Dass könnte https://www.snik.eu/ontology/bb/StrategicInformationManagementPlan sein, oder aber https://www.snik.eu/ontology/bb/ProjectPortfolio. Bitte mit Birgit und Franziska Jahn klären, welcher Begriff hier für ein closematch am ehesten passt.

**Comment by KonradHoeffner** [comment]
Entscheidung in SNIK Jour Fixe 2020-02-18: 

- closeMatch mit https://www.snik.eu/ontology/bb/ProjectPortfolio.
- 4 Zeilen auf Seite 127 von he zweiter Absatz "Inhalt des strategischen IT-Plans ..." als Definition nehmen.

**Comment by KonradHoeffner** [comment]
@FranziskaJahn, @BirgitSNIK: Kann mir jemand von euch den Heinrich ausleihen oder digital geben? Ich habe ihn leider nicht.
