### ISSUE TITLE
http://www.snik.eu/ontology/ciox/ITStrategie

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#300]
The class http://www.snik.eu/ontology/ciox/ITStrategie has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Das ist ein Dublette zu http://www.snik.eu/ontology/ciox/ItStrategie. Bitte miteinander verschmelzen.

**Comment by AnnaLoerke** [comment]
Ticket #182 

Aktuell noch Rückmeldung aus Besprechung erwartet, dann Abschluss des Tickets.
