### ISSUE TITLE
http://www.snik.eu/ontology/he/StrategischesProjektportfolio

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#301]
The class http://www.snik.eu/ontology/he/StrategischesProjektportfolio has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Das gibt es auch im bb. Bitte suchen und ggf. closematch

**Comment by FranziskaJahn** [comment]
closematch zu bb/ProjectPortfolio, ob/ProjektPortfolio und ciox/Projektportfolio einfügen.

**Comment by KonradHoeffner** [comment]
Done
