### ISSUE TITLE
bb:PatientIdentificationAndCheckingForRecurrent meta:updates bb:Patient

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#305]
The edge "bb:PatientIdentificationAndCheckingForRecurrent meta:updates bb:Patient" is incorrect.

**Details**
Kniffliges Problem, dass wir besprechen müssen:
Diese Relation widerspricht dem Meta-Modell, da eine Function keine Rolle updaten kann. Wir benötigen vermutlich eine weitere Klasse "Patient" als enitity-type. Die könnte dann geupdated werden. Aber wir benötigen noch eine geeignete Relation zwischen dem Entity-Type "Patient" und der Rolle "Patient". Ich vermute, das Problem haben wir häufiger auch an anderen Stellen, dass im Informationsmanagement Informationen über Rollen bearbeitet werden. Daher könnte es sinnvoll sein eine neue Relation zwischen Rolle und Entity-Type im Meta-Modell einzuführen.

**Comment by AlfredWinter** [comment]
Ich sehe gerade, dass es einige solcher falscher Relationen zur Rolle Patient gibt.

**Comment by FranziskaJahn** [comment]
Bei einem anderen Issue hat AW geschrieben, dass wir in unserem IM-Kontext den Patienten nicht als Rolle, sondern als Objekttyp modellieren sollten. Wird der Patient zum Objekttyp, dann stimmen alle Beziehungen bis auf eine: Er darf dann keine subClassOf HIS Stakeholder mehr sein.

**Comment by KonradHoeffner** [comment]
HIS Stakeholder wird auch zum Entity Type, siehe https://github.com/IMISE/snik-ontology/issues/306. Daher stimmt dann auch die letzte Beziehung wieder.
