### ISSUE TITLE
http://www.snik.eu/ontology/bb/Patient

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#306]
The class http://www.snik.eu/ontology/bb/Patient has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Patient ist hier Rolle, aber dieser Knoten wird meist als Entity-Type genutzt. Siehe dazu auch issue #305

**Comment by AlfredWinter** [comment]
De Facto wird der Patient von uns im Informationsmanagement nur als Gegenstand gesehen, über den Informationen verarbeitet werden. Wir billigen ihm keine aktive Rolle im Informationsmanagement zu. dann sollten wir ihn konsequent auch einfach als entity type führen. Für die anderen Stakeholder (https://www.snik.eu/ontology/bb/HisStakeholder) ist das auch zu überprüfen und ggf. zu ändern. Mir scheint, Stakeholder sind zwar Rollen, aber im IM interessieren sie nur als entity types.

**Comment by KonradHoeffner** [comment]
Entschieden in SNIK Jour Fixe 2020-01-17

|  Class                                              | Old Type   | New Type   | Other Changes                             |
|-----------------------------------------------------|------------|------------|-------------------------------------------|
| https://www.snik.eu/ontology/bb/Patient             | EntityType | EntityType | isResponsibleForFunction -> ...EntityType |
| https://www.snik.eu/ontology/bb/GeneralPractitioner | Role       | EntityType |                                           |
| https://www.snik.eu/ontology/bb/Relative            | Role       | EntityType |                                           |
| https://www.snik.eu/ontology/bb/Consultant          | Role       | EntityType |                                           |
| https://www.snik.eu/ontology/bb/HospitalStaff       | Role       | Role       | subClassOf -> associatedWith Stakeholder  |
| https://www.snik.eu/ontology/bb/FundingInstitute    | Role       | EntityType |                                           |
| https://www.snik.eu/ontology/bb/Outpatient          |            |            | no changes                                |
| https://www.snik.eu/ontology/bb/Vendor              | Role       | Role       | subClassOf -> associatedWith Stakeholder  |
| https://www.snik.eu/ontology/bb/ClinicalDepartment  | Role       | Role       | subClassOf -> associatedWith Stakeholder  |
