### ISSUE TITLE
bb:Hospital meta:roleComponent bb:Patient

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#307]
The edge "bb:Hospital meta:roleComponent bb:Patient" is incorrect.

**Details**
Verstoß gegen Metamodell. Klären ob "Hospital" Rolle oder EntityType ist. (vg.l #305 )

**Comment by FranziskaJahn** [comment]
Da der Patient ja auch jetzt ein Entity Type sein soll, kann Hospital nun auch zum Entity Type werden, dann stimmen alle ein- und ausgehenden Beziehungen.

**Comment by KonradHoeffner** [comment]
Patient und Hospital sind jetzt beide Entity Type. Aber dadurch geht Patient subclassof HIS Stakeholder nicht mehr, habe es durch "is associated with" ersetzt.
