### ISSUE TITLE
bb:Patient rdfs:subClassOf bb:PatientCareEntityType

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#308]
The edge "bb:Patient rdfs:subClassOf bb:PatientCareEntityType" is incorrect.

**Details**
vgl. #305 
Verstoß gegen Metamodell

**Comment by KonradHoeffner** [comment]
Soll die Kante einfach gelöscht werden, oder ist eine alternative Modellierung gewünscht?

**Comment by FranziskaJahn** [comment]
Patient soll zu einem Objekttyp werden. Siehe auch #305, #306, #307

**Comment by KonradHoeffner** [comment]
Wurde in der SNIK Jour Fixe heute 2020-01-17 entschieden: Da Patient jetzt ein Objekttyp ist, darf die Verbindung bleiben.
