### ISSUE TITLE
Extract missing pages and chapters from blue book

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#310]
See also: https://github.com/IMISE/snik-ontology/issues/296, https://github.com/IMISE/snik-ontology/issues/309.

Despite efforts to restore missing chapters, there are still several hundred classes in the blue book without page, partly without chapter too.
All classes with a page now have a chapter because we automatically generated those, see IMISE/snik-cytoscape.js#214.

However for those that don't have a page and maybe also don't have a chapter, we should extract those from the blue book. Using the digital version and using search it should be doable semi-automatically and it would be a huge help for the chapter search feature for teaching.

**Comment by ThomasPause** [comment]
missing pages extracted and output as rdf triples in a private repo due to license issues: https://github.com/ThomasPause/MissingPageFinder

**Comment by ThomasPause** [comment]
solve the following problems:
- [ ] geld in Ziegeldach: match only complete words
- [ ] offset between pdf pages and book pages
- [ ] analyse the differences between human and automatic extraction

**Comment by ThomasPause** [comment]
I think the main difference is that the algorithm finds any occurrence of a given word or word group, specified by the regex, whilst the human extraction maybe a little bit inconsistent.
The algo can not rate if a word fits in the context of the text or not but it is definitely much faster.
Words like "hospital", "operation" or "communication" are found very often throughout the book (maybe exclude them in the script)

**Comment by ThomasPause** [comment]
![haeufigkeit](https://user-images.githubusercontent.com/27236726/65603205-870ec200-dfa5-11e9-8f1d-ae6607cea5d5.png)

**Comment by ThomasPause** [comment]
this shows that some buzzwords occur very often and the question is if it is useful or not to have an array of about 250 pagenumbers where the term "hospital" is in the book.
So I think there is a limit for automated extraction. Maybe we can skip the most often occurring words and let the manual analysis test which pagenumber(s) are useful to keep and which are not.

**Comment by ThomasPause** [comment]
|# | Wort | ‰|
|-----|---------------|-------|
|249 | hospital | 242|
|99 | communication | 96.2|
|68 | organization | 66.1|
|56 | operation | 54.4|
|54 | network | 52.5|
|49 | physician | 47.6|
|40 | ward | 38.9|
|36 | standard | 35|
|33 | outpatient | 32.1|
|32 | laboratory | 31.1|
|27 | resource | 26.2|
|26 | security | 25.3|
|22 | book | 21.4|
|21 | medication | 20.4|
|20 | nurse | 19.4|
|16 | education | 15.5|
|16 | study | 15.5|
|14 | event | 13.6|
|12 | inpatient | 11.7|
|12 | vendor | 11.7|
|11 | framework | 10.7|
|8 | library | 7.8|
|6 | drg | 5.8|
|6 | law | 5.8|
|6 | workstation | 5.8|
|6 | xml | 5.8|
|5 | icd | 4.9|
|5 | pathology | 4.9|
|5 | pharmacy | 4.9|
|4 | cluster | 3.9|
|4 | diet | 3.9|
|4 | eurorec | 3.9|
|4 | switch | 3.9|
|3 | loinc | 2.9|
|3 | pager | 2.9|
|3 | surgeon | 2.9|
|2 | backbone | 1.9|
|2 | ct | 1.9|
|2 | customizing | 1.9|
|2 | ethernet | 1.9|
|2 | icd10 | 1.9|
|2 | jointcommission | 1.9|
|2 | laptop | 1.9|
|2 | nutrition | 1.9|
|2 | orientation | 1.9|
|2 | pencil | 1.9|
|2 | radiotherapy | 1.9|
|2 | tiss | 1.9|
|1 | ascii | 1|
|1 | atc | 1|
|1 | catering | 1|
|1 | cen | 1|
|1 | complaint | 1|
|1 | consultant | 1|
|1 | excretion | 1|
|1 | hipaa | 1|
|1 | icpm | 1|
|1 | iukdg | 1|
|1 | jpeg | 1|
|1 | khg | 1|
|1 | khstatv | 1|
|1 | mpeg | 1|
|1 | nomenclature | 1|
|1 | snomed | 1|
|1 | telemicroscopy | 1|
|1 | tiff | 1|
|1 | ultrasound | 1|
|1 | umls | 1|

**Comment by ThomasPause** [comment]
![wortverteilung](https://user-images.githubusercontent.com/27236726/65604603-0ac9ae00-dfa8-11e9-83f1-72687f286e6b.png)
![vorkommen](https://user-images.githubusercontent.com/27236726/65605223-05b92e80-dfa9-11e9-813e-d0042d2b0c02.png)

**Comment by KonradHoeffner** [comment]
[classeswithpage.tsv.txt](https://github.com/IMISE/snik-ontology/files/3652748/classeswithpage.tsv.txt)

**Comment by ThomasPause** [comment]
![Verteilung_manuell](https://user-images.githubusercontent.com/27236726/65607995-c6411100-dfad-11e9-85bb-0f7d9cb6c5ba.png)
 Die Verteilung nach manueller Extraktion

**Comment by ThomasPause** [comment]
![Verteilung_automatisiert](https://user-images.githubusercontent.com/27236726/65609514-305ab580-dfb0-11e9-9a4e-5e566c109adc.png)

Die Verteilung nach automatisierter Extraktion

**Comment by ThomasPause** [comment]
Die manuelle Extraktion liefert maximal 2 Seiten pro Klasse, bei der automatisierten gibt es Klassen mit mehreren hundert Vorkommen. Daher ist die Frage ob es sinnvoll ist, einen Cutoff zu setzen und wenn ja wo.

**Comment by ThomasPause** [comment]
cutoff is now at 3, twhat means that classes which appear more than 3 times are not written into the file. 
Last problem now is, that the offset between pdf manuscript and the 2nd edition book varies and so the pages are not correct yet.
We need a pdf from the 2nd edition book to extract correctly

**Comment by ThomasPause** [comment]
algorithm now converts to normalized unicode, sorted results are attached here as .nt file
@KonradHoeffner please put them into the SPARQL endpoint
[outputsorted.nt.txt](https://github.com/IMISE/snik-ontology/files/3711884/outputsorted.nt.txt)

**Comment by KonradHoeffner** [comment]
Upload done
