### ISSUE TITLE
Split page literals

### ISSUE THREAD

**Issue by ThomasPause** [IMISE/snik-ontology#311]
Pages should be integers, comma separated literals such as "123, 345" are thus invalid. Split those up into two triples.

**Comment by KonradHoeffner** [comment]
See also https://github.com/IMISE/snik-ontology/issues/311.

**Comment by KonradHoeffner** [comment]
Happens in ob and bb:

```
select distinct ?g
{
 graph ?g
{ ?s ?p ?page.}
 filter(regex(str(?p),"page","i"))
 filter(regex(str(?page),","))
}
```

**Comment by KonradHoeffner** [comment]
## Fix datatype

```
sparql
with <http://www.snik.eu/ontology/he-unconsolidated>
delete 
{
 ?s ?p ?page.
}
insert
{
 ?s ?p ?pagep.
}
where
{
 ?s ?p ?page.
 filter(regex(str(?p),"page","i"))
 bind(STRDT(str(?page),xsd:positiveInteger) as ?pagep)
}
```

Other graphs analogously.

**Comment by KonradHoeffner** [comment]
Now we have some page triples that don't match the datatype:

```
select distinct ?p ?page
{
 ?s ?p ?page.
 filter(regex(str(?p),"page","i"))
 filter(xsd:int(?page)!=?page)
}
```
p | page
-- | --
http://www.snik.eu/ontology/bb/tripelPage | "manuell hinzugefügt"^^<http://www.w3.org/2001/XMLSchema#positiveInteger>
http://www.snik.eu/ontology/bb/tripelPage | "manuell ergänzt"^^<http://www.w3.org/2001/XMLSchema#positiveInteger>
http://xmlns.com/foaf/0.1/homepage | "http://www.snik.eu"^^<http://www.w3.org/2001/XMLSchema#positiveInteger>
http://xmlns.com/foaf/0.1/homepage | "http://www.snik.eu/"^^<http://www.w3.org/2001/XMLSchema#positiveInteger>
http://www.snik.eu/ontology/bb/page | "manuell hinzugefügt"^^<http://www.w3.org/2001/XMLSchema#positiveInteger>
http://www.snik.eu/ontology/meta/DefinitionDEPage | "manuell hinzugefügt"^^<http://www.w3.org/2001/XMLSchema#positiveInteger>
http://www.snik.eu/ontology/ob/tripelPage | "manuell hinzugefügt"^^<http://www.w3.org/2001/XMLSchema#positiveInteger>

**Comment by KonradHoeffner** [comment]
For unknown reasons, the conductor does not execute the following query without an error message, so the "manuell hinzugefügt" triples stay with the incorrect datatype for now:

```
sparql
with <http://www.snik.eu/ontology/bb>
delete
{
?s ?p "manuell hinzugefügt"^^<http://www.w3.org/2001/XMLSchema#positiveInteger>.
}
insert
{
 ?s ?p "manuell hinzugefügt".
}
where
{
?s ?p "manuell hinzugefügt"^^<http://www.w3.org/2001/XMLSchema#positiveInteger>.
}
```
