### ISSUE TITLE
http://www.snik.eu/ontology/bb/ItServiceManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#314]
The class http://www.snik.eu/ontology/bb/ItServiceManagement has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Das Englische Label von "Information Management Function" ändern zu "Information Management". Bitte von MG prüfen lassen, ob auch die persische Übersetzung geändert werden muss.

**Comment by KonradHoeffner** [comment]
Das englische Label von http://www.snik.eu/ontology/bb/ItServiceManagement ist derzeit "IT Service Management", soll es trotzdem zu "Information Management" geändert werden?

**Comment by AlfredWinter** [comment]
Da hatte ich auf den falschen Knoten geklickt. Danke für's Aufpassen. 
Es geht um: http://www.snik.eu/ontology/bb/InformationManagement. Da gibt es zwei Label. Das Label "Information Management Function" muss weg. Beim Persisch dann bitte prüfen lassen.

**Comment by KonradHoeffner** [comment]
sparql
DELETE DATA {GRAPH <http://www.snik.eu/ontology/bb> {<http://www.snik.eu/ontology/bb/InformationManagement> rdfs:label "Information Management Function"@en.}}

**Comment by KonradHoeffner** [comment]
@maghalandari: Please tell us, if the label "مدیریت اطلاعات" is means "Information Management" or "Information Management Function".

**Comment by KonradHoeffner** [comment]
According to Google Translate it is only two words so I will close this already. @maghalandari: If it's wrong, please reopen.
