### ISSUE TITLE
http://www.snik.eu/ontology/he/BetriebKomponenteInformationsfunktion

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#323]
The class http://www.snik.eu/ontology/he/BetriebKomponenteInformationsfunktion has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Englische Übersetzung des Labels muss überarbeitet werden

**Comment by KonradHoeffner** [comment]
Geändert zu "Operation of a component of an information function".
