### ISSUE TITLE
http://www.snik.eu/ontology/bb/NonComputerBasedPhysicalDataProcessingSystem

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#327]
The class http://www.snik.eu/ontology/bb/NonComputerBasedPhysicalDataProcessingSystem has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
CloseMatch zu http://www.snik.eu/ontology/ob/NonComputerBasedPhysicalTool einfügen

**Comment by KonradHoeffner** [comment]
Erledigt

```
sparql
INSERT DATA {GRAPH <http://www.> {<http://www.snik.eu/ontology/bb/NonComputerBasedPhysicalDataProcessingSystem> skos:closeMatch <http://www.snik.eu/ontology/ob/NonComputerBasedPhysicalTool>.}}
```
