### ISSUE TITLE
he:QuantitativeMessgroesse

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#328]
@BirgitSNIK: Es wird eine he:QuantitativeMessgroesse referenziert im he aber es gibt keine Informationen darüber. Was hat es damit auf sich? Soll ich die Referenzen darauf löschen? Oder fehlen einfach die Einträge über die Messgröße?

**Comment by BirgitSNIK** [comment]
Hallo Konrad,
um all diese Fragen zu beantworten, bräuchte ich nochmal richtig Zeit, die ich gerade aber nicht habe, weil ich mich in die SMITH-Jet Aufgabe einarbeiten muss. Ich weiß echt nicht, wann ich das machen soll und welche Priorität es hat.
Wenn Elemente einfach nur „dumm“ rumhängen, absolut nicht passen aber kaum verbunden sind, würde ich sie gnadenlos rauslöschen. Wir haben Heinrich soundso nicht komplett abgedeckt, da ist es m.E. egal, wenn die Lücken noch etwas größer werden.
Birgit
 
Von: Konrad Höffner <notifications@github.com> 
Gesendet: Freitag, 4. Oktober 2019 12:30
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: BirgitSNIK <birgit.schneider@imise.uni-leipzig.de>; Mention <mention@noreply.github.com>
Betreff: [IMISE/snik-ontology] he:QuantitativeMessgroesse (#328)
 
@BirgitSNIK: Es wird eine he:QuantitativeMessgroesse referenziert im he aber es gibt keine Informationen darüber. Was hat es damit auf sich? Soll ich die Referenzen darauf löschen? Oder fehlen einfach die Einträge über die Messgröße?

**Comment by KonradHoeffner** [comment]
OK, habe jetzt alle Referenzen auf he:QuantitativeMessgroesse gelöscht.
