### ISSUE TITLE
he:Schlechte-Konzepte--Dennoch-interessante-Information...

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#331]
Bei https://www.snik.eu/ontology/he/UrsachenStrategischerUeberdehnung ist als Kapitel https://www.snik.eu/ontology/he/Schlechte-Konzepte--Dennoch-interessante-Information--Wie-soll-Konzeptualisiert-werden--Evtl--lediglich-als-Textblock-verwenden----MS-FJ- angegeben. Was soll damit passieren?

**Comment by FranziskaJahn** [comment]
Konzept löschen, es ist sowieso nichts damit verknüpft.

**Comment by KonradHoeffner** [comment]
Konzept und Kapitel gelöscht.
