### ISSUE TITLE
http://www.snik.eu/ontology/bb/ChiefInformationOfficer

### ISSUE THREAD

**Issue by FranziskaJahn** [IMISE/snik-ontology#333]
The class http://www.snik.eu/ontology/bb/ChiefInformationOfficer has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Please insert the following alternative labels:
IT-Leiter, EDV-Leiter, Abteilungsleiter IT, Geschäftsbereichsleiter IT, EDV-Administrator, IT-Administrator, Objektleiter Biomedizintechnik/IT, EDV-Koordinator, Leiter Medizinische Informatik, IT-Organisator

Source: CIO Survey 2016

**Comment by KonradHoeffner** [comment]
```dump_one_graph ('http://www.snik.eu/ontology/bb', './dumps/20191011bb', 1000000000);```

**Comment by KonradHoeffner** [comment]
Erledigt
