### ISSUE TITLE
bb:LongTermHISPlanning rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#337]
The edge "bb:LongTermHISPlanning rdfs:subClassOf bb:InformationManagement" is incorrect.

**Details**
Bitte löschen (das ergibt sich transitiv dadurch, dass es functional component von stragic planning ist.

**Comment by KonradHoeffner** [comment]
Da es momentan keine andere Oberklasse hat, würde ich dann Function als Oberklasse setzen, ist das richtig so? Allerdings hätte man dann dieselbe Anzahl Tripel und mit weniger Genauigkeit.

Und gilt das immer bei uns? Also wenn x eine Komponente y hat und x gehört zur Klasse C, dann gehört y auch zur Klasse C?

Denn im Allgemeinen gilt das ja nicht, ein Auto hat die Komponente Rad und gehört zur Klasse Fahrzeug aber ein Rad ist kein Fahrzeug.

**Comment by AlfredWinter** [comment]
Bitte vorab mit BS und FJ besprechen

**Comment by KonradHoeffner** [comment]
Ich baue das mal in das übergeordnete Ticket ein und mache hier zu.
