### ISSUE TITLE
bb:ShortTermHISPlanning rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#338]
The edge "bb:ShortTermHISPlanning rdfs:subClassOf bb:InformationManagement" is incorrect.

**Details**
Bitte löschen (das ergibt sich transitiv dadurch, dass es functional component von stragic planning ist.

**Comment by KonradHoeffner** [comment]
Analog zu #337 ist hier auch keine weitere Oberklasse angegeben, Oberklasse durch meta:Function ersetzen oder bb:HospitalFunction?

**Comment by AlfredWinter** [comment]
Wenn unbedingt eine Oberklasse nötig ist, dann meta:Function. Bitte mit FJ und BS besprechen. 
AW

**Comment by KonradHoeffner** [comment]
Ich baue das mal in das übergeordnete Ticket ein und mache hier zu.
