### ISSUE TITLE
bb:StrategicHISPlanning rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#339]
The edge "bb:StrategicHISPlanning rdfs:subClassOf bb:InformationManagement" is incorrect.

**Details**
Bitte löschen (das ergibt sich transitiv dadurch, dass es functional component von stragic management ist.

**Comment by KonradHoeffner** [comment]
Analog zu issue #337 würde ich das gerne nochmal diskutieren, welche Transitivitätsregeln wir da ansetzen.

**Comment by KonradHoeffner** [comment]
Ich baue das mal in das übergeordnete Ticket ein und mache hier zu.
