### ISSUE TITLE
ob:StrategicHISPlanning rdfs:subClassOf ob:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#340]
The edge "ob:StrategicHISPlanning rdfs:subClassOf ob:InformationManagement" is incorrect.

**Details**
Bitte löschen (das ergibt sich transitiv dadurch, dass es functional component von stragic management ist.

**Comment by KonradHoeffner** [comment]
Analog zu issue #337 hier auch die Frage, wie genau wir das mit der Transitivität handhaben.

**Comment by AlfredWinter** [comment]
Bitte mit FJ und BS einen Vorschlag erarbeiten, wie wir mit transititivität umgehen sollen. Dann möchte ich über diesem Vorschlag mitentscheiden. 
AW

**Comment by KonradHoeffner** [comment]
Ich baue das mal in das übergeordnete Ticket ein und mache hier zu.
