### ISSUE TITLE
ob:StrategicManagementOfInformationSystems meta:updates ob:StrategicInformationManagementPlan

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#341]
The edge "ob:StrategicManagementOfInformationSystems meta:updates ob:StrategicInformationManagementPlan" is incorrect.

**Details**
Löschen. Ist redundant

**Comment by KonradHoeffner** [comment]
Erledigt.

[OntoWiki Link](https://www.snik.eu/ontowiki/view?r=http://www.snik.eu/ontology/ob/StrategicManagementOfInformationSystems&m=http://www.snik.eu/ontology/ob)
