### ISSUE TITLE
bb:StrategicInformationManagement meta:updates bb:StrategicInformationManagementPlan

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#342]
The edge "bb:StrategicInformationManagement meta:updates bb:StrategicInformationManagementPlan" is incorrect.

**Details**
Löschen

**Comment by KonradHoeffner** [comment]
Erledigt.

[OntoWiki Link](https://www.snik.eu/ontowiki/view/?r=http%3A%2F%2Fwww.snik.eu%2Fontology%2Fbb%2FStrategicInformationManagement)
