### ISSUE TITLE
ob:StrategicHISPlanning meta:updates ob:StrategicInformationManagementPlan

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#343]
The edge "ob:StrategicHISPlanning meta:updates ob:StrategicInformationManagementPlan" is incorrect.

**Details**
Löschen

**Comment by KonradHoeffner** [comment]
Erledigt.

[OntoWiki Link](https://www.snik.eu/ontowiki/view?r=http://www.snik.eu/ontology/ob/StrategicHISPlanning&m=http://www.snik.eu/ontology/ob)
