### ISSUE TITLE
ob:StrategicHISPlanning meta:updates ob:ProjectPortfolio

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#344]
The edge "ob:StrategicHISPlanning meta:updates ob:ProjectPortfolio" is incorrect.

**Details**
löschen

**Comment by KonradHoeffner** [comment]
Erledigt.

[OntoWiki Link](https://www.snik.eu/ontowiki/view?r=http://www.snik.eu/ontology/ob/StrategicHISPlanning&m=http://www.snik.eu/ontology/ob)
