### ISSUE TITLE
ciox:ITStrategieentwicklung meta:updates ciox:Projektportfolio

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#345]
The edge "ciox:ITStrategieentwicklung meta:updates ciox:Projektportfolio" is incorrect.

**Details**
löschen

**Comment by KonradHoeffner** [comment]
Erledigt.

https://www.snik.eu/ontowiki/view?r=http://www.snik.eu/ontology/ciox/ITStrategieentwicklung&m=http://www.snik.eu/ontology/ciox
