### ISSUE TITLE
ob:FormulationOfAProjectIdea rdfs:subClassOf ob:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#346]
The edge "ob:FormulationOfAProjectIdea rdfs:subClassOf ob:InformationManagement" is incorrect.

**Details**
löschen

**Comment by KonradHoeffner** [comment]
Analog zu issue #337 gibt es auch hier nur Function als alternative Klasse und würde das gerne nochmal besprechen.

**Comment by AlfredWinter** [comment]
Bitte mit BS und FJ klären

**Comment by KonradHoeffner** [comment]
Ich baue das mal in das übergeordnete Ticket ein und mache hier zu.

**Comment by KonradHoeffner** [comment]
Ich baue das mal in das übergeordnete Ticket ein und mache hier zu.
