### ISSUE TITLE
ob:ProjectPortfolio meta:isBasedOn ob:StrategicInformationManagementPlanning

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#347]
The edge "ob:ProjectPortfolio meta:isBasedOn ob:StrategicInformationManagementPlanning" is incorrect.

**Details**
ersetzen durch "updates" von ob:StrategicInformationManagementPlanning nach ob:ProjectPortfolio

**Comment by KonradHoeffner** [comment]
Erledigt.
