### ISSUE TITLE
http://www.snik.eu/ontology/ob/StrategicInformationManagementPlanning

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#348]
The class http://www.snik.eu/ontology/ob/StrategicInformationManagementPlanning has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Diese Klasse und die Klasse http://www.snik.eu/ontology/ob/StrategicHISPlanning sind identisch und nur irrtümlich zwei Klassen. Bitte zusammenführen (auf Seitenzahlen und Definitionen achten)

**Comment by KonradHoeffner** [comment]
OK, ich werde es in die Klasse https://www.snik.eu/ontology/ob/StrategicInformationManagementPlanning zusammenführen. http://www.snik.eu/ontology/ob/StrategicHISPlanning hat zum Glück weder Definition noch Seitenzahlen.

```
SPARQL
with <http://www.snik.eu/ontology/ob>
delete
{
?s ?p <http://www.snik.eu/ontology/ob/StrategicHISPlanning> .
}
insert
{
?s ?p <http://www.snik.eu/ontology/ob/StrategicInformationManagementPlanning> .
}
where
{
?s ?p <http://www.snik.eu/ontology/ob/StrategicHISPlanning> .
}
```
```
SPARQL
with <http://www.snik.eu/ontology/ob>
delete
{
<http://www.snik.eu/ontology/ob/StrategicHISPlanning> ?s ?p  .
}
insert
{
 <http://www.snik.eu/ontology/ob/StrategicInformationManagementPlanning>  ?s ?p.
}
where
{
<http://www.snik.eu/ontology/ob/StrategicHISPlanning> ?s ?p  .
}
```
