### ISSUE TITLE
Transitivität über component-Relation?

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#351]
@FranziskaJahn, @BirgitSNIK:
Ich brauche mal euren Input für ein gemeinsames Problem der Issues #337, #338, #339, #340:

Wenn X eine Komponente Y hat und X ist Unterklasse der Klasse C, ist Y dann auch Unterklasse von C?

Und wenn ja, soll das Unterklassenstatement zwischen Y und C dann entfernt werden? Was, wenn es das einzige solche Statement ist, wodurch soll es dann ersetzt werden?

Für die part-of Relation gilt das ja nicht allgemein, ein Auto hat die Komponente Rad und gehört zur Klasse Fahrzeug aber ein Rad ist kein Fahrzeug. Aber die component-Relation in SNIK kann ja anders definiert sein.

**Comment by BirgitSNIK** [comment]
M.E. kann eine Teilaufgabe (z.B. Systemanalyse) Komponente in verschiedenen Aufgaben sein und muss daher nicht unbedingt Subklasse dieser Aufgaben sein bzw. diese können sich ja auch unterscheiden.

**Comment by KonradHoeffner** [comment]
Dann würde ich die Tripel gerne behalten aus folgenden Gründen:

- Da es laut Birgit sich nicht in jedem Fall ableiten lässt, können wir es bei Entfernen des Tripels nicht automatisch rekonstruieren.
- Da wir sowieso immer mindestens ein Subklassentripel pro Klasse haben, müssten wir es dann weiter hoch hängen, was den SNIK Graph unübersichtlich macht und weniger Information repräsentiert.
- Würde dies dann auch SPARQL-Queries komplizierter machen, bzw. nicht alle gewünschten Ergebnisse liefern wenn man z.B. nach allen Unterklassen von Information Management Function sucht.

Was meinen Sie, @AlfredWinter?

**Comment by AlfredWinter** [comment]
ich möchte das gerne gemeinsam anhand meines konkreten Beispiels diskutieren. Und dann brauchen wir eine generelle Regel

**Comment by KonradHoeffner** [comment]
Ich habe die Untertickets mal geschlossen und die Einträge hier hinzugefügt, damit wir alles an gleichen Ort haben. Es geht um die folgenden Tripel:

Subjekt|Prädikat|Objekt
---|---|---
ob:StrategicHISPlanning |rdfs:subClassOf| ob:InformationManagement
bb:ShortTermHISPlanning| rdfs:subClassOf| bb:InformationManagement
bb:LongTermHISPlanning| rdfs:subClassOf| bb:InformationManagement 
ob:FormulationOfAProjectIdea| rdfs:subClassOf| ob:InformationManagement

## Komponenten

Subjekt|Prädikat|Objekt
---|---|---
ob:InformationManagement | meta:functionComponent | ob:StrategicManagementOfInformationSystems
bb:InformationManagement | meta:functionComponent | bb:StrategicInformationManagement

**Comment by KonradHoeffner** [comment]
Es muss da im Einzelfall entschieden werden. In den in den Issues #337, #338, #339 und #340 beschriebenen Fällen soll die Verbindung entfernt (also auf EntityType/Role/Function umgehängt werden).
