### ISSUE TITLE
Mehrere Klassen für Application Component / System

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#352]
Wir haben ja im Metamodell die Klassen [meta:ApplicationComponent](https://www.snik.eu/ontology/meta/ApplicationComponent) und [meta:ComputerBasedApplicationComponent](https://www.snik.eu/ontology/meta/ComputerBasedApplicationComponent). Daher würde ich gerne wissen, ob wir die gleichnamigen Klassen in den Unterontologien wirklich brauchen, oder ob wir die dadurch ersetzen können, denn wir haben ja auch nicht in jeder Unterontologie Function, Role und EntityType. Außerdem sind die Labels auch sehr unterschiedlich, manche Sachen heißen System, sind aber mit Components verlinkt oder andersherum oder es gibt gleich beide Labels in einer Klasse, wie bei CIOX.

Momentan sieht es so aus:

Subjekt|Prädikat|Objekt
--|--|--
[ob:ComputerBasedApplicationSystem](https://www.snik.eu/ontology/ob/ComputerBasedApplicationSystem) |rdfs:subClassOf|ob:ApplicationSystem
[ob:ApplicationSystem](https://www.snik.eu/ontology/ob/ApplicationSystem) |rdfs:subClassOf|ob:InformationProcessingTool 
[ciox:ComputerbasiertesAnwendungssystem](http://www.snik.eu/ontology/ciox/ComputerbasiertesAnwendungssystem)|rdfs:subClassOf|[ciox:Anwendungssystem](http://www.snik.eu/ontology/ciox/Anwendungssystem)
[ciox:ComputerbasiertesAnwendungssystem](http://www.snik.eu/ontology/ciox/ComputerbasiertesAnwendungssystem)|skos:closeMatch|bb:ComputerBasedApplicationComponent
[ciox:ComputerbasiertesAnwendungssystem](http://www.snik.eu/ontology/ciox/ComputerbasiertesAnwendungssystem)|skos:closeMatch|ob:ComputerBasedApplicationSystem
[ciox:Anwendungssystem](http://www.snik.eu/ontology/ciox/Anwendungssystem)|rdfs:subClassOf|meta:ApplicationComponent
[ciox:Anwendungssystem](http://www.snik.eu/ontology/ciox/Anwendungssystem)|skos:closeMatch|ob:ComputerBasedApplicationSystem
[ciox:Anwendungssystem](http://www.snik.eu/ontology/ciox/Anwendungssystem)|skos:closeMatch|he:Anwendungssystem
[bb:ApplicationComponent](http://www.snik.eu/ontology/bb/ApplicationComponent)|rdfs:subClassOf|meta:ApplicationComponent
[bb:ComputerBasedApplicationComponent](http://www.snik.eu/ontology/bb/ComputerBasedApplicationComponent)|rdfs:subClassOf|meta:ComputerBasedApplicationComponent

**Comment by AlfredWinter** [comment]
Wir brauchen die unterschiedlichen Klassen in den Unterontologien, weil es zu diesem Begriff duchaus unterschiedliche Lehrmeinungen gibt, bzw. geben kann. Das drückt sich dann auch in den unterschiedlichen Lables aus. So ist eben die Vielfalt schon in der eigenen 'Familie'. Das ist eine andere Angelegenheit als z.B. bei Rolle. Rolle wird in der betrachteten Literatur nicht unterschiedlich gesehen. Das kann man einfach auf die Meta-Ebene heben
Die Meta-Klasse "application component" ist  von uns quasi als Referenzpunkt einfach festgelegt. Eigentlich müssten alle diesbezüglichen Klassen der Teilontologien damit explizit verbunden werden.

**Comment by KonradHoeffner** [comment]
Ah jetzt verstehe ich es. Dann füge ich die folgenden Verbindungen hinzu:

**Comment by AlfredWinter** [comment]
ok

**Comment by KonradHoeffner** [comment]
Ist hinzugefügt.
