### ISSUE TITLE
http://www.snik.eu/ontology/ob/ApplicationSystem v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#36]
The class http://www.snik.eu/ontology/ob/ApplicationSystem has [incorrect/missing attribute values | 

**Details**
Hat keine Description. Scheint ein systematischer Fehler zu sein.
AW

**Comment by KonradHoeffner** [comment]
Hm das könnte ein Fehler an der alten LodView Implementierung sein, mittlerweile geht es LodView.
