### ISSUE TITLE
CPOE exists but not POE

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#363]
In BB, there is only [CPOE](https://www.snik.eu/ontology/bb/ComputerizedPhysicianOrderEntrySystem) but no class for POE. However the blue book does describe POE in section 6.4.5 and table 6.5. Should we create and add a POE class as a superclass of CPOE?

**Comment by FranziskaJahn** [comment]
I think we decided to use the more common acronym CPOE as label in SNIK although it is called POE in the book. POE should be a synonym of CPOE in SNIK. We do not need super- and subclasses.

**Comment by KonradHoeffner** [comment]
Add POE synonym to SNIK.

**Comment by KonradHoeffner** [comment]
```
SPARQL
INSERT DATA {GRAPH <http://www.snik.eu/ontology/bb> {<http://www.snik.eu/ontology/bb/ComputerizedPhysicianOrderEntrySystem> skos:altLabel "CPOE"@en, "POE"@en, "Physician Order Entry System"@en.}}
```
