### ISSUE TITLE
http://www.snik.eu/ontology/bb/HisQuality

### ISSUE THREAD

**Issue by BirgitSNIK** [IMISE/snik-ontology#365]
Problem with the class [bb:HisQuality](http://www.snik.eu/ontology/bb/HisQuality) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/HisQuality&m=http://www.snik.eu/ontology/bb)):
missing association: 
HISQuality is subclassOf Quality (both in BB)
Kommentar: Dann kommt man nämlich direkt zu all den schönen Aufgaben (HIS Benchmarking, quality assessment, ...), die sonst nur über quality zu erreichen sind!

**Comment by ThomasPause** [comment]
Solved.
