### ISSUE TITLE
Quality Check: subClassOf and component between the same classes

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#367]
Add Quality Check for two classes that are connected both via subclassOf and also via component relation, possibly in the other direction. If there are more occurences, decide manually about those.

**Comment by KonradHoeffner** [comment]
- what exactly is the semantic difference between component and subclass?
- what to do if the relation is decided to be component but the class doesn't have another superclass?

**Comment by ThomasPause** [comment]
for disjunctive properties we may use:
https://www.w3.org/2007/OWL/wiki/FullSemanticsDisjointProperties

**Comment by KonradHoeffner** [comment]
Available at https://imise.github.io/snik-ontology/2017/06/01/qualitycheck#subclassof-and-component.
