### ISSUE TITLE
bb:QualityOfStructures rdfs:subClassOf bb:Quality

### ISSUE THREAD

**Issue by BirgitSNIK** [IMISE/snik-ontology#369]
Problem with the edge [bb:QualityOfStructures rdfs:subClassOf bb:Quality](http://www.snik.eu/ontology/bb/QualityOfStructures) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/QualityOfStructures&m=http://www.snik.eu/ontology/bb)):
m.E. Sind Quality of Outcome, Quality of Process und Quality of Structures entityTypeComponten von Quality; dann sieht man auch den Unterschied zu HIS-Quality viel besser, die tatsächlich subClass of Quality ist.

**Comment by BirgitSNIK** [comment]
das Gleiche gilt für die Teilkomponenten von HIS-Quality (Quality of HIS-Outcome, Quality of HIS Process, Quality of HIS Structures), dort auch statt der suClass Beziehung jeweils entityTypeComponent

**Comment by BirgitSNIK** [comment]
sorry, falscher Knopf!

**Comment by KonradHoeffner** [comment]
```
SPARQL
DELETE DATA
{
 GRAPH <http://www.snik.eu/ontology/bb>
 {
  bb:QualityOfStructures rdfs:subClassOf bb:Quality.
  bb:QualityOfProcesses rdfs:subClassOf bb:Quality.
  bb:QualityOfOutcome rdfs:subClassOf bb:Quality.

  bb:QualityOfHISStructures rdfs:subClassOf bb:HisQuality.
  bb:QualityOfHISProcesses rdfs:subClassOf bb:HisQuality.
  bb:QualityOfHISOutcome rdfs:subClassOf bb:HisQuality.
 }
}
INSERT DATA
{
 GRAPH <http://www.snik.eu/ontology/bb>
 {
  bb:Quality meta:entityTypeComponent bb:QualityOfStructures.
  bb:Quality meta:entityTypeComponent bb:QualityOfProcesses.
  bb:Quality meta:entityTypeComponent bb:QualityOfOutcome.
 
  bb:HisQuality meta:entityTypeComponent bb:QualityOfHISStructures.
  bb:HisQuality meta:entityTypeComponent bb:QualityOfHISProcesses.
  bb:HisQuality meta:entityTypeComponent bb:QualityOfHISOutcome.
 }
}
```
