### ISSUE TITLE
bb:QualityOfHISArchitecture rdfs:subClassOf bb:QualityOfHISStructures

### ISSUE THREAD

**Issue by BirgitSNIK** [IMISE/snik-ontology#370]
Problem with the edge [bb:QualityOfHISArchitecture rdfs:subClassOf bb:QualityOfHISStructures](http://www.snik.eu/ontology/bb/QualityOfHISArchitecture) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/QualityOfHISArchitecture&m=http://www.snik.eu/ontology/bb)):
Noch so ein Fall: statt subClassOf bitte entityTypeComponent.
Gilt auch für "Quality of Data" entityTypeComponent "Quality of HIS Structures"
und
"Quality of Computerbased Application Compnets and ..." entityTypeComponent "Quality of HIS Structures"

**Comment by KonradHoeffner** [comment]
```
SPARQL
DELETE DATA
{
 GRAPH <http://www.snik.eu/ontology/bb>
 {
  bb:QualityOfHISArchitecture rdfs:subClassOf bb:QualityOfHISStructures.
  bb:QualityOfData rdfs:subClassOf bb:QualityOfHISStructures.
  bb:QualityOfComputerBasedApplicationComponentsAndTheirIntegration rdfs:subClassOf bb:QualityOfHISStructures.
 }
}
INSERT DATA
{
 GRAPH <http://www.snik.eu/ontology/bb>
 {
   bb:QualityOfHISStructures meta:entityTypeComponent bb:QualityOfHISArchitecture.
   bb:QualityOfHISStructures meta:entityTypeComponent bb:QualityOfData.
   bb:QualityOfHISStructures meta:entityTypeComponent bb:QualityOfComputerBasedApplicationComponentsAndTheirIntegration.
 }
}
```

**Comment by KonradHoeffner** [comment]
```Delete from <http://www.snik.eu/ontology/bb>, 3 (or less) triples -- done Insert into <http://www.snik.eu/ontology/bb>, 3 (or less) triples -- done Commit -- done```
