### ISSUE TITLE
he:Benutzerforschung und he:BenutzerforschungDurchfuehren

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#374]
- he:Benutzerforschung und he:BenutzerforschungDurchfuehren sind nicht miteinander verbunden, intuitiv müsste da aber doch ein Zusammenhang bestehen, oder ist das wirklich so korrekt?
-Bei he:BenutzerforschungDurchfuehren wurden die Seiten 423 und 426 entfernt. Soweit ich das sehen kann, ist die Entfernung auch korrekt, da auf den angegebenen Seiten von "Benutzerforschung" gesprochen wird, allerdings hat he:Benutzerforschung jetzt überhaupt keine Seite mehr. Wo kommt es denn dann überhaupt her? Als Kapitel ist INBAN angegeben, wo auch die Benutzerforschung an sich beschrieben ist. Brauchen wir die Seiten nicht unbedingt?

**Comment by BirgitSNIK** [comment]
Ich nehme mal an, dass ich oder jemand anderes das "durchführen" angehängt hat, um aus dem simplen EntityType eine Aufgabe zu machen, bei der man dann sagen kann: uses, increases etc. m Buch weden meit nur Schlagworte verwendet, bei denen aber eigentlich oft Aufgaben dahinter stecken, besonders, wenn dann auch noch erklärt wird, mit welchen Methoden bei diesem "Schlagwort" gearbeitet wird.
Birgit



 Von:   Konrad Höffner <notifications@github.com> 
 An:   IMISE/snik-ontology <snik-ontology@noreply.github.com> 
 Kopie:   BirgitSNIK <birgit.schneider@imise.uni-leipzig.de>, Assign <assign@noreply.github.com> 
 Gesendet:   25.06.2020 16:09 
 Betreff:   [IMISE/snik-ontology] he:Benutzerforschung und he:BenutzerforschungDurchfuehren (#374) 


 he:Benutzerforschung und he:BenutzerforschungDurchfuehren sind nicht miteinander verbunden, intuitiv müsste da aber doch ein Zusammenhang bestehen, oder ist das wirklich so korrekt?
 -Bei he:BenutzerforschungDurchfuehren wurden die Seiten 423 und 426 entfernt. Soweit ich das sehen kann, ist die Entfernung auch korrekt, da auf den angegebenen Seiten von "Benutzerforschung" gesprochen wird, allerdings hat he:Benutzerforschung jetzt überhaupt keine Seite mehr. Wo kommt es denn dann überhaupt her?

**Comment by KonradHoeffner** [comment]
Bedeutet das, dass alles OK ist und ich die Issue schließen kann?

**Comment by KonradHoeffner** [comment]
Ich schließe die issue mal, wenn da doch noch etwas zu erledigen ist, dann bitte wieder öffnen.
