### ISSUE TITLE
bb:ProjectCompletion rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#377]
Problem with the edge [bb:ProjectCompletion rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/ProjectCompletion) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/ProjectCompletion&m=http://www.snik.eu/ontology/bb)):

Beziehung löschen; bringt keinen Mehrwert.

**Comment by KonradHoeffner** [comment]
Teil von #366.
