### ISSUE TITLE
bb:InformationManagement meta:updates bb:HospitalInformationSystem

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#378]
Problem with the edge [bb:InformationManagement meta:updates bb:HospitalInformationSystem](http://www.snik.eu/ontology/bb/InformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/InformationManagement&m=http://www.snik.eu/ontology/bb)):

Beziehung löschen, da kein Mehrwert

**Comment by KonradHoeffner** [comment]
Erledigt.
