### ISSUE TITLE
bb:ProjectExecution rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#380]
Problem with the edge [bb:ProjectExecution rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/ProjectExecution) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/ProjectExecution&m=http://www.snik.eu/ontology/bb)):

Löschen, da kein Mehrwert

**Comment by KonradHoeffner** [comment]
Teil von https://github.com/IMISE/snik-ontology/issues/366.
