### ISSUE TITLE
bb:ProjectPlanning rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#381]
Problem with the edge [bb:ProjectPlanning rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/ProjectPlanning) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/ProjectPlanning&m=http://www.snik.eu/ontology/bb)):

Löschen, da kein  Mehrwert

**Comment by KonradHoeffner** [comment]
Die Kante ist gar nicht mehr vorhanden, anscheinend haben wir das schon erledgt. bb:ProjectPlanning ist jetzt nur noch Unterklasse von Tactical HIS Planning. Falls das geändert werden soll, Ticket bitte wieder öffnen.
