### ISSUE TITLE
bb:TacticalHISPlanning rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#382]
Problem with the edge [bb:TacticalHISPlanning rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/TacticalHISPlanning) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/TacticalHISPlanning&m=http://www.snik.eu/ontology/bb)):

Löschen, da kein Mehrwert. Im Übrigen steht das auch im Widerspruch zu der transitiven Kette von FunctionComponent über Taktikal Information Management. Also raus.

**Comment by KonradHoeffner** [comment]
Teil von Issue #366.
