### ISSUE TITLE
bb:TacticalHISMonitoring rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#383]
Problem with the edge [bb:TacticalHISMonitoring rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/TacticalHISMonitoring) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/TacticalHISMonitoring&m=http://www.snik.eu/ontology/bb)):

Löschen, da kein Mehrwert. Im Übrigen steht das auch im Widerspruch zu der transitiven Kette von FunctionComponent über Taktikal Information Management. Also raus.

**Comment by KonradHoeffner** [comment]
Ist bereits gelöscht, wahrscheinlich da es Teil von Issue #366 ist.
