### ISSUE TITLE
bb:TacticalHISDirecting rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#384]
Problem with the edge [bb:TacticalHISDirecting rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/TacticalHISDirecting) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/TacticalHISDirecting&m=http://www.snik.eu/ontology/bb)):

Löschen, da kein Mehrwert. Im Übrigen steht das auch im Widerspruch zu der transitiven Kette von FunctionComponent über Taktikal Information Management. Also raus.

**Comment by KonradHoeffner** [comment]
Bereits erledigt im Rahmen von #366.
