### ISSUE TITLE
http://www.snik.eu/ontology/bb/ProjectCompletion

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#385]
Problem with the class [bb:ProjectCompletion](http://www.snik.eu/ontology/bb/ProjectCompletion) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/ProjectCompletion&m=http://www.snik.eu/ontology/bb)):

Diese Klasse kann ganz weg. Angeblich steht das in Kapitel 9 des BB. Habe kontrolliert. Da gibt es dazu nichts spezielles. Ich kann keinen Sinn in dem Begriff erkennen.

**Comment by KonradHoeffner** [comment]
Erledigt.
