### ISSUE TITLE
http://www.snik.eu/ontology/bb/ChiefInformationOfficer

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#386]
Problem with the class [bb:ChiefInformationOfficer](http://www.snik.eu/ontology/bb/ChiefInformationOfficer) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/ChiefInformationOfficer&m=http://www.snik.eu/ontology/bb)):

Bitte folgende Relation einfügen: http://www.snik.eu/ontology/bb/ChiefInformationOfficer isResponsibleForFunction https://www.snik.eu/ontology/bb/InformationManagement

**Comment by KonradHoeffner** [comment]
Erledigt (bereits vorhanden).
