### ISSUE TITLE
bb:ChiefInformationOfficer meta:isResponsibleForFunction bb:TacticalInformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#389]
Problem with the edge [bb:ChiefInformationOfficer meta:isResponsibleForFunction bb:TacticalInformationManagement](http://www.snik.eu/ontology/bb/ChiefInformationOfficer) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/ChiefInformationOfficer&m=http://www.snik.eu/ontology/bb)):

Löschen. Aber beachten: #386 !!!!

**Comment by KonradHoeffner** [comment]
Erledigt (bereits entfernt).
