### ISSUE TITLE
ciox:Softwareprodukt skos:closeMatch ob:SoftwareProduct

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#392]
Problem with the edge [ciox:Softwareprodukt skos:closeMatch ob:SoftwareProduct](http://www.snik.eu/ontology/ciox/Softwareprodukt) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ciox/Softwareprodukt&m=http://www.snik.eu/ontology/ciox)):

bestätige ich

**Comment by KonradHoeffner** [comment]
Was genau ist das Problem, soll die Kante gelöscht werden?

**Comment by AlfredWinter** [comment]
Nein, Nein!! Im gegenteil! Ich bestätige den Close Match, der noch mit einem Warndreieck ausgestattet war. Das "Problem" wird ja automatisch genereiert.

**Comment by KonradHoeffner** [comment]
Achso, stimmt ja. Habe die Bestätigung ausgeführt.
