### ISSUE TITLE
http://www.snik.eu/ontology/bb/TreatmentBill

### ISSUE THREAD

**Issue by cubexy** [IMISE/snik-ontology#394]
http://www.snik.eu/ontology/bb/TreatmentBill

Described as "Bill" rather than "Treatment Bill" in the Blue Book (p.78), while the ontology labels it "Treatment Bill", resulting in an awkward definition.

> "Is demanded payment"

The top class [Bill](https://www.snik.eu/ontology/bb/Bill) has no definition.

**Comment by KonradHoeffner** [comment]
- [ ] treatment bill löschen
- [ ] bei Bill manuell hinzugefügt entfernen und Seite 78 hinzufügen
