### ISSUE TITLE
http://www.snik.eu/ontology/ob/StrategicGoal

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#398]
Problem with the class [ob:StrategicGoal](http://www.snik.eu/ontology/ob/StrategicGoal) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/StrategicGoal&m=http://www.snik.eu/ontology/ob)):
 Bitte Seitenangabe ergänzen: 337

**Comment by KonradHoeffner** [comment]
Erledigt.
