### ISSUE TITLE
ciox:ItMassnahme skos:closeMatch bb:InformationManagementGoal

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#404]
Problem with the edge [ciox:ItMassnahme skos:closeMatch bb:InformationManagementGoal](http://www.snik.eu/ontology/ciox/ItMassnahme) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ciox/ItMassnahme&m=http://www.snik.eu/ontology/ciox)):

Löschen. Das ist ein Fehler.

**Comment by KonradHoeffner** [comment]
Erledigt.
