### ISSUE TITLE
bb:SystematicInformationProcessing meta:isAssociatedWith bb:StrategicGoalOfTheInstitution

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#405]
Problem with the edge [bb:SystematicInformationProcessing meta:isAssociatedWith bb:StrategicGoalOfTheInstitution](http://www.snik.eu/ontology/bb/SystematicInformationProcessing) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/SystematicInformationProcessing&m=http://www.snik.eu/ontology/bb)):

Ändern in uses: bb:SystematicInformationProcessing uses bb:StrategicGoalOfTheInstitution

**Comment by KonradHoeffner** [comment]
Erledigt.
