### ISSUE TITLE
ob:GoalDefinition meta:uses ob:ProjectGoal

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#408]
Problem with the edge [ob:GoalDefinition meta:uses ob:ProjectGoal](http://www.snik.eu/ontology/ob/GoalDefinition) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/GoalDefinition&m=http://www.snik.eu/ontology/ob)):

ändern  in "updates"

**Comment by KonradHoeffner** [comment]
Erledigt
