### ISSUE TITLE
bb:SystematicInformationProcessing meta:isAssociatedWith bb:StrategicInformationManagementGoal

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#410]
Problem with the edge [bb:SystematicInformationProcessing meta:isAssociatedWith bb:StrategicInformationManagementGoal](http://www.snik.eu/ontology/bb/SystematicInformationProcessing) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/SystematicInformationProcessing&m=http://www.snik.eu/ontology/bb)):

ersetzen durch "uses"

**Comment by KonradHoeffner** [comment]
Erledigt.
