### ISSUE TITLE
bb:Directing rdfs:subClassOf bb:Management

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#414]
Problem with the edge [bb:Directing rdfs:subClassOf bb:Management](http://www.snik.eu/ontology/bb/Directing) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/Directing&m=http://www.snik.eu/ontology/bb)):

Löschen. Das iist keine SubclassOf sondern Komponente (diese Beziehung besteht schon).

**Comment by KonradHoeffner** [comment]
Dann hat bb:Directing allerdings keine Oberklasse mehr, was laut unseren Modellierungsregeln nicht erlaubt ist. Haben Sie eine alternative Oberklasse, die ich einsetzen kann?

**Comment by AlfredWinter** [comment]
siehe #413

**Comment by KonradHoeffner** [comment]
OK, durch meta:Function ersetzt.
