### ISSUE TITLE
bb:Controlling rdfs:subClassOf bb:Management

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#415]
Problem with the edge [bb:Controlling rdfs:subClassOf bb:Management](http://www.snik.eu/ontology/bb/Controlling) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/Controlling&m=http://www.snik.eu/ontology/bb)):

Löschen.

**Comment by KonradHoeffner** [comment]
Erledigt.
