### ISSUE TITLE
ob:InformationManagement meta:functionComponent ob:OperationalManagementOfInformationSystems

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#416]
Problem with the edge [ob:InformationManagement meta:functionComponent ob:OperationalManagementOfInformationSystems](http://www.snik.eu/ontology/ob/InformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/InformationManagement&m=http://www.snik.eu/ontology/ob)):

Löschen (die component Beziehung behalten)

**Comment by KonradHoeffner** [comment]
Ist bereits gelöscht.
