### ISSUE TITLE
bb:InformationManagement meta:functionComponent bb:OperationalInformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#417]
Problem with the edge [bb:InformationManagement meta:functionComponent bb:OperationalInformationManagement](http://www.snik.eu/ontology/bb/InformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/InformationManagement&m=http://www.snik.eu/ontology/bb)):

Löschen

**Comment by KonradHoeffner** [comment]
Ich habe die Kante gelöscht, dabei fiel mir aber auf, dass bb:OperationalInformationManagement keine Oberklasse hat, daher habe ich dann bb:InformationManagement als Oberklasse genommen. Falls das nicht so sein soll, bitte Issue wieder öffnen.

Analog bin ich dann auch bei Strategic und Tactical und Information Management vorgegangen.

**Comment by AlfredWinter** [comment]
Jetzt bin ich auf einmal völlig unsicher, warum ich die Löschung dieser Kante wollte. Waren da vielleicht vorher mehrere Beziehungen?  Auf jeden Fall ist gut, dass Sie die SubClass-Beziehung eingeführt haben. Nehmen sie den Punkt mal in die Kategorie "Diskussion". Müssen wir mit FJ noch mal besprechen, ob subClass oder component das Richtigere ist.

**Comment by AlfredWinter** [comment]
Schauen Sie mal nach #447

**Comment by KonradHoeffner** [comment]
In die Diskussionsliste aufgenommen über das Label "needsdiscussion".
