### ISSUE TITLE
bb:InformationManagement meta:functionComponent bb:StrategicInformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#418]
Problem with the edge [bb:InformationManagement meta:functionComponent bb:StrategicInformationManagement](http://www.snik.eu/ontology/bb/InformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/InformationManagement&m=http://www.snik.eu/ontology/bb)):

ersetzen durch: bb:StrategicInformationManagement SubClassOf bb:InformationManagement

**Comment by KonradHoeffner** [comment]
Erledigt. Analog zu https://github.com/IMISE/snik-ontology/issues/417.
