### ISSUE TITLE
ob:InformationManagement meta:functionComponent ob:StrategicManagementOfInformationSystems

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#419]
Problem with the edge [ob:InformationManagement meta:functionComponent ob:StrategicManagementOfInformationSystems](http://www.snik.eu/ontology/ob/InformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/InformationManagement&m=http://www.snik.eu/ontology/ob)):

löschen

**Comment by KonradHoeffner** [comment]
Erledigt.
