### ISSUE TITLE
ob:OperationalHISMonitoring rdfs:subClassOf ob:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#420]
Problem with the edge [ob:OperationalHISMonitoring rdfs:subClassOf ob:InformationManagement](http://www.snik.eu/ontology/ob/OperationalHISMonitoring) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/OperationalHISMonitoring&m=http://www.snik.eu/ontology/ob)):

löschen

**Comment by KonradHoeffner** [comment]
Teil von https://github.com/IMISE/snik-ontology/issues/395.

Analog zu bb:Monitoring wollte ich es auf auf [ob:Monitoring](http://www.snik.eu/ontology/ob/Monitoring) umhängen aber das gibt es nicht.
