### ISSUE TITLE
bb:OperationalHISMonitoring rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#421]
Problem with the edge [bb:OperationalHISMonitoring rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/OperationalHISMonitoring) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/OperationalHISMonitoring&m=http://www.snik.eu/ontology/bb)):

löschen

**Comment by KonradHoeffner** [comment]
Die Klasse hat leider keine andere Oberklasse. Nach unseren Regeln, dass es mindestens eine geben muss, müssen wir erstmal eine andere finden. Damit ist diese Issue in #395 enthalten und ich schließe diese hier.

Die Einträge dafür stehen in der Tabelle https://docs.google.com/spreadsheets/d/1A7THvy5Le23aQF_6pE0AbS6ov3WrlCvMBb2ANz2hewc. Für diese Klasse ist dort jedoch noch kein Eintrag vorhanden.

In diesem Fall sehe ich aber schon eine passende Oberklasse, und zwar bb:Monitoring und trage das in die Tabelle ein. Die Einträge in der Tabelle werden gesammelt und dann abgearbeitet. Falls jemand eine passendere Oberklasse findet (bb:HISMonitoring gibt es nicht), bitte in der Tabelle ändern und falls schon als erledigt angekreuzt dort mir Bescheid sagen zum Ändern im SPARQL Endpunkt.

**Comment by AlfredWinter** [comment]
Mir fehlt jetzt die Ruhe, das zu durchdenken. Aber wir müssen aufpassen dass wir #447 nicht noch weiter verschlimmern. in die Diskussionsliste nehmen.
