### ISSUE TITLE
bb:OperationalHISPlanning rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#422]
Problem with the edge [bb:OperationalHISPlanning rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/OperationalHISPlanning) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/OperationalHISPlanning&m=http://www.snik.eu/ontology/bb)):

löschen

**Comment by KonradHoeffner** [comment]
Teil von https://github.com/IMISE/snik-ontology/issues/366.
