### ISSUE TITLE
ob:OperationalHISDirecting rdfs:subClassOf ob:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#423]
Problem with the edge [ob:OperationalHISDirecting rdfs:subClassOf ob:InformationManagement](http://www.snik.eu/ontology/ob/OperationalHISDirecting) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/OperationalHISDirecting&m=http://www.snik.eu/ontology/ob)):

löschen

**Comment by KonradHoeffner** [comment]
Teil von https://github.com/IMISE/snik-ontology/issues/395.
