### ISSUE TITLE
http://www.snik.eu/ontology/bb/StrategicInformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#425]
Problem with the class [bb:StrategicInformationManagement](http://www.snik.eu/ontology/bb/StrategicInformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/StrategicInformationManagement&m=http://www.snik.eu/ontology/bb)):

eine subclassOf zu bb:Informationmanagement einfügen

**Comment by KonradHoeffner** [comment]
Erledigt. Analog zu https://github.com/IMISE/snik-ontology/issues/417.
