### ISSUE TITLE
http://www.snik.eu/ontology/ob/StrategicManagementOfInformationSystems

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#426]
Problem with the class [ob:StrategicManagementOfInformationSystems](http://www.snik.eu/ontology/ob/StrategicManagementOfInformationSystems) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/StrategicManagementOfInformationSystems&m=http://www.snik.eu/ontology/ob)):

eine subclassOf zu ob:Informationmanagement einfügen

**Comment by KonradHoeffner** [comment]
Erledigt.
