### ISSUE TITLE
ob:NetworkManagement rdfs:subClassOf ob:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#427]
Problem with the edge [ob:NetworkManagement rdfs:subClassOf ob:InformationManagement](http://www.snik.eu/ontology/ob/NetworkManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/NetworkManagement&m=http://www.snik.eu/ontology/ob)):

Löschen

**Comment by KonradHoeffner** [comment]
Teil von https://github.com/IMISE/snik-ontology/issues/395.
