### ISSUE TITLE
bb:InformationAndKnowledgeLogistics rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#429]
Problem with the edge [bb:InformationAndKnowledgeLogistics rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/InformationAndKnowledgeLogistics) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/InformationAndKnowledgeLogistics&m=http://www.snik.eu/ontology/bb)):

Löschen

**Comment by KonradHoeffner** [comment]
Teil von https://github.com/IMISE/snik-ontology/issues/366.
