### ISSUE TITLE
ob:InformationAndKnowledgeLogistics rdfs:subClassOf ob:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#430]
Problem with the edge [ob:InformationAndKnowledgeLogistics rdfs:subClassOf ob:InformationManagement](http://www.snik.eu/ontology/ob/InformationAndKnowledgeLogistics) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/ob/InformationAndKnowledgeLogistics&m=http://www.snik.eu/ontology/ob)):

löschen

**Comment by KonradHoeffner** [comment]
Teil von https://github.com/IMISE/snik-ontology/issues/366.
