### ISSUE TITLE
http://www.snik.eu/ontology/bb/CobitDomain

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#431]
Problem with the class [bb:CobitDomain](http://www.snik.eu/ontology/bb/CobitDomain) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/CobitDomain&m=http://www.snik.eu/ontology/bb)):

Klären: Wo kommt das her? Das ist keine Funktion.

**Comment by KonradHoeffner** [comment]
Laut dem "tripelPage" Attribute kommt das aus Seite 270 des blauen Buches. In meiner PDF Version (Manuscript 2010 2nd Edition) ist das Seite 336 laut PDF Viewer bzw. Seite 305 laut Buch. Kapitel 9.5.4.2 COBIT:

> 
> COBIT is built on a process model that defines 34 IT-related processes within
> four domains: plan and organize; acquire and implement; deliver and support; monitor and
> evaluate. For each of these 34 processes, among others, information on how the specific
> process goals can be measured, what the key activities and major deliverables are, and
> who is responsible for them is provided. The following list presents an overview of the
> four domains and selected, simplified key metrics (key performance indicators) for each of
> them.
> Plan and organize [...]

**Comment by AlfredWinter** [comment]
Diese Klasse muss umbenannt werden in "COBIT Processes for IT Governance" . Die BEziehung zu https://www.snik.eu/ontology/bb/Cobit muss geändert werden in "isAssociatedWith" (jetzt falsch: functionComponent).

**Comment by KonradHoeffner** [comment]
```
SPARQL
WITH <http://www.snik.eu/ontology/bb>
DELETE {bb:CobitDomain ?p ?o.}
INSERT { bb:CobitProcess ?p ?o.}
WHERE { bb:CobitDomain ?p ?o.}
```

**Comment by KonradHoeffner** [comment]
SPARQL
WITH <http://www.snik.eu/ontology/bb>
DELETE {?s ?p bb:CobitDomain.}
INSERT {?s ?p bb:CobitProcess.}
WHERE {?s ?p bb:CobitDomain.}

**Comment by KonradHoeffner** [comment]
Erledigt.
