### ISSUE TITLE
bb:CobitDomain rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#432]
Problem with the edge [bb:CobitDomain rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/CobitDomain) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/CobitDomain&m=http://www.snik.eu/ontology/bb)):

löschen

**Comment by KonradHoeffner** [comment]
Teil von https://github.com/IMISE/snik-ontology/issues/366.
