### ISSUE TITLE
bb:PortfolioManagement rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#434]
Problem with the edge [bb:PortfolioManagement rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/PortfolioManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/PortfolioManagement&m=http://www.snik.eu/ontology/bb)):

ersetzen durch: functionalComponent of bb:StrategicHISPlanning

**Comment by KonradHoeffner** [comment]
Solves part of issue #395. 
Also entered in https://docs.google.com/spreadsheets/d/1A7THvy5Le23aQF_6pE0AbS6ov3WrlCvMBb2ANz2hewc.
