### ISSUE TITLE
bb:TransactionManagement rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#435]
Problem with the edge [bb:TransactionManagement rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/TransactionManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/TransactionManagement&m=http://www.snik.eu/ontology/bb)):

Löschen! Das ist mal richtig eindeutiger Unfug.

**Comment by KonradHoeffner** [comment]
Die Klasse hat leider keine andere Oberklasse. Nach unseren Regeln, dass es mindestens eine geben muss, müssen wir erstmal eine andere finden. Damit ist diese Issue in von https://github.com/IMISE/snik-ontology/issues/395 enthalten und ich schließe diese hier. Die Einträge dafür stehen in der Tabelle https://docs.google.com/spreadsheets/d/1A7THvy5Le23aQF_6pE0AbS6ov3WrlCvMBb2ANz2hewc .
