### ISSUE TITLE
bb:AdoptionOfProjectResult rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#436]
Problem with the edge [bb:AdoptionOfProjectResult rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/AdoptionOfProjectResult) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/AdoptionOfProjectResult&m=http://www.snik.eu/ontology/bb)):

Löschen

**Comment by KonradHoeffner** [comment]
Die Klasse hat leider keine andere Oberklasse. Nach unseren Regeln, dass es mindestens eine geben muss, müssen wir erstmal eine andere finden. Damit ist diese Issue in von https://github.com/IMISE/snik-ontology/issues/395 enthalten und ich schließe diese hier.
