### ISSUE TITLE
bb:ExecutionOfAnITEvaluationStudy rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#440]
Problem with the edge [bb:ExecutionOfAnITEvaluationStudy rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/ExecutionOfAnITEvaluationStudy) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/ExecutionOfAnITEvaluationStudy&m=http://www.snik.eu/ontology/bb)):

Löschen!

**Comment by KonradHoeffner** [comment]
Die Klasse hat leider keine andere Oberklasse. Nach unseren Regeln, dass es mindestens eine geben muss, müssen wir erstmal eine andere finden. Damit ist diese Issue ein Teil von https://github.com/IMISE/snik-ontology/issues/395.
