### ISSUE TITLE
bb:InformationManagement meta:isAssociatedWith bb:EnterpriseFunction

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#441]
Problem with the edge [bb:InformationManagement meta:isAssociatedWith bb:EnterpriseFunction](http://www.snik.eu/ontology/bb/InformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/InformationManagement&m=http://www.snik.eu/ontology/bb)):

Löschen!

**Comment by KonradHoeffner** [comment]
Erledigt
