### ISSUE TITLE
bb:HisOperation rdfs:subClassOf bb:InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#442]
Problem with the edge [bb:HisOperation rdfs:subClassOf bb:InformationManagement](http://www.snik.eu/ontology/bb/HisOperation) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/HisOperation&m=http://www.snik.eu/ontology/bb)):

ersetzen durch functionalComponent of bb/OperationalHISDirecting

**Comment by KonradHoeffner** [comment]
Laut FJ in https://docs.google.com/spreadsheets/d/1A7THvy5Le23aQF_6pE0AbS6ov3WrlCvMBb2ANz2hewc hat die Aufgabe keine Definition und keine Beziehungen und wird daher gelöscht.

**Comment by AlfredWinter** [comment]
Das verstehe ich jetzt nicht. Mir ging es doch darum, die SubClass Beziehung durch eine component-Beziehung zu ersetzen

**Comment by KonradHoeffner** [comment]
Das ist normalerweise auch kein Problem, außer in dem Spezialfall, dass die Klasse nur diese einzige Oberklasse hat.
Dann darf man die Beziehung nicht ersetzen, weil es dann keine Oberklasse mehr gäbe.
Und dann ist nicht mehr definiert, ob die Klasse eine Rolle, Funktion oder ein Objekttyp ist. Daher definieren wir immer mindestens eine Oberklasse.
Außerdem war die Klasse sowieso für das Löschen vorgemerkt.

Wenn Sie die Klasse trotzdem behalten möchten, kann ich sie wiederherstellen und dann als Oberklasse meta:Function setzen.
Das ist allerdings laut unseren [Modellierungsregeln](https://wiki.imise.uni-leipzig.de/Projekte/SNIK/ontologie/modellierungsregeln) nicht so günstig: 

> Fast jede Klasse sollte ein subClassOf außerhalb von meta haben.
