### ISSUE TITLE
http://www.snik.eu/ontology/bb/InformationManagement

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#443]
Problem with the class [bb:InformationManagement](http://www.snik.eu/ontology/bb/InformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/InformationManagement&m=http://www.snik.eu/ontology/bb)):

Alle subClass of Beziehungen der Knoten in dem beigelegten Bild zu diesem Knoten bb/InformationManagement löschen
![Unbenannt](https://user-images.githubusercontent.com/22190396/97041776-4c90a380-1570-11eb-8b04-2244f788c041.JPG)

**Comment by KonradHoeffner** [comment]
Dies wird in Issue #366 und in Tabelle https://docs.google.com/spreadsheets/d/1A7THvy5Le23aQF_6pE0AbS6ov3WrlCvMBb2ANz2hewc/edit#gid=0 bereits bearbeitet.
