### ISSUE TITLE
bb:StrategicInformationManagement meta:uses bb:StrategicInformationManagementPlan

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#444]
Problem with the edge [bb:StrategicInformationManagement meta:uses bb:StrategicInformationManagementPlan](http://www.snik.eu/ontology/bb/StrategicInformationManagement) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/StrategicInformationManagement&m=http://www.snik.eu/ontology/bb)):

Löschen

**Comment by KonradHoeffner** [comment]
Ist mittlerweile bereits gelöscht.
