### ISSUE TITLE
http://www.snik.eu/ontology/bb/ChiefInformationOfficer

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#445]
Problem with the class [bb:ChiefInformationOfficer](http://www.snik.eu/ontology/bb/ChiefInformationOfficer) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/ChiefInformationOfficer&m=http://www.snik.eu/ontology/bb)):

alle isResponsibleForFunction beziehungen löschen und dafür eine einzigeisResponsibleForFunction  zu bb/InformationManagement

**Comment by KonradHoeffner** [comment]
Erledigt
