### ISSUE TITLE
Meta-Modell

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#45]
bitte noch einmal alle Begriffe des Meta-Modells daraufhin überprüfen, ob sie in dem Bild von Birgit Schneider vorkommen. Und umgekehrt. 
Viele Grüße
AW

**Comment by KonradHoeffner** [comment]
Erledigt. Einige Sachen wurden aus dem Metamodell entfernt. subTopClass fehlt noch im graphischen Metamodell.
