### ISSUE TITLE
http://www.snik.eu/ontology/bb/InformationManagementEntityType v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#46]
The class http://www.snik.eu/ontology/bb/InformationManagementEntityType has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Das scheint mir ein Element des Meta-Modells zu sein, ist aber so nicht modelliert. AW

**Comment by KonradHoeffner** [comment]
Duplikat von #48.
