### ISSUE TITLE
http://www.snik.eu/ontology/bb/ResearchAndEducationEntityType v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#47]
The class http://www.snik.eu/ontology/bb/ResearchAndEducationEntityType has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Meta-Modell??? AW

**Comment by KonradHoeffner** [comment]
Die von Ihnen genannte Ressource gehört zu bb, nicht zu meta. Aber es gab `meta:EducationResearchEntityType`, das ich jetzt entfernt habe.
