### ISSUE TITLE
http://www.snik.eu/ontology/bb/InformationManagementEntityType v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#48]
The class http://www.snik.eu/ontology/bb/InformationManagementEntityType has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Diese Klasse ist eigentlich  ein Element des Meta-Modells und müsste bei Nutzung des entsprechenden Filters eigentlich verschwinden. Bitte Korrigieren. Bitte zusätzlich alle elemente des Meta-Modells in der Ontologie suchen und als solche Kennzeichnen. Grüße und Danke. AW

**Comment by KonradHoeffner** [comment]
Es gibt sowohl die Klasse meta:InformationManagementEntityType als auch deren Subklassen bb:InformationManagementEntityType und ob:InformationManagementEntityType.
Das Label war allerdings falsch bei meta:..., nämlich "InformationManagementEntityType" (fehlende Leerzeichen). Ich habe das jetzt korrigiert.
