### ISSUE TITLE
http://www.snik.eu/ontology/bb/HospitalFunction v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#49]
The class http://www.snik.eu/ontology/bb/HospitalFunction has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Das ist auch ein Meta-Modell-Element.
AW

**Comment by KonradHoeffner** [comment]
http://www.snik.eu/ontology/bb/HospitalFunction gehört auch zur bb Ontologie und nicht zum Meta-Modell. In SNIK Graph wird er auch blau angezeigt. Daher schließe ich die Issue mal, da das Problem nicht mehr aufzutreten scheint. Sollte es wieder passieren, bitte wieder öffnen.
