### ISSUE TITLE
http://www.snik.eu/ontology/meta/Management v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#50]
The class http://www.snik.eu/ontology/meta/Management has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Wieso ist das rot? Das ist doch gar kein Meta-Modell-Element.
AW

**Comment by AlfredWinter** [comment]
Bekomme ich Nachricht, wenn ein Ticket bearbeitet worden ist?
AW

**Comment by KonradHoeffner** [comment]
Sie müssten Nachrichten für Ihre Tickets automatisch abonniert haben.

**Comment by KonradHoeffner** [comment]
In Version 0.3.0 gab es noch die Funktion "Management"; ich habe diese jetzt entfernt.
