### ISSUE TITLE
http://www.snik.eu/ontology/meta/Administration v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#51]
The class http://www.snik.eu/ontology/meta/Administration has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
auch kein Meta-Modell-Element

**Comment by KonradHoeffner** [comment]
Wurde Entfernt.
