### ISSUE TITLE
http://www.snik.eu/ontology/bb/StorageAreaNetwork v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#53]
The class http://www.snik.eu/ontology/bb/StorageAreaNetwork has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Seitenzahl fehlt in der Description

**Comment by KonradHoeffner** [comment]
Im Buch gefunden und hinzugefügt.
Fehlende Seitenzahlen können allerdings automatisch gefunden werden mittels `select ?c {?c a owl:Class. ?c bb:page "".}` (page prefix analog für andere Unterontologien). Es gibt alleine bei bb 660 solche Fälle, bei ob sind es 777. Ich schlage daher vor, in Zukunft solche Fehler nicht über die Ticketverfolgung einzeln zu lösen, sondern, wenn diese gelöst werden sollen, dies durch die Extrahierer komplett zu lösen durch die Extrahierer, dies dürfte allerdings viel Zeit in Anspruch nehmen.
