### ISSUE TITLE
http://www.snik.eu/ontology/ob/ComponentOfAnInformationSystem v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#55]
The class http://www.snik.eu/ontology/ob/ComponentOfAnInformationSystem has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Dieser Begriff wird nicht weiter verwendet obwohl z.B. eine Verbindung zu "Communication Interface 1" denkbar wäre. Auch hier möge Frau jahn sich er Angelegenheit annehmen.

**Comment by FranziskaJahn** [comment]
"Component of an information system" stammt aus dem Thesarus, wird aber im Rest des Buches nicht verwendet. Allerdings fehlen auch die im Thesaurus genannten Relationen: {enterprise function | business process | application component | physical data processing system}  subclassOf Coais.

**Comment by AlfredWinter** [comment]
Das sind ja subclassOf relationen. Die sollten also noch eingefügt werden

**Comment by AnnaLoerke** [comment]
Im ob gibt es "application component" nicht. Außerdem ist "enterprise function" einen Funktion, während "Component of an information system" ein Entity Type ist. "subClassOf" wäre somit gegen das Meta-Modell. Welche Modellierung wird stattdessen erwünscht? 

 Die anderen beiden Relationen sind hinzugefügt.

**Comment by AnnaLoerke** [comment]
Die Relationen lassen sich aktuell nicht darstellen. Rücksprache mit Franziska: Der Begriff kommt nur im Thesarus und daher belassen wir es jetzt dabei.
