### ISSUE TITLE
http://www.snik.eu/ontology/ob/CommunicationInterface v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#56]
The class http://www.snik.eu/ontology/ob/CommunicationInterface has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Es ist merkwürdig, dass dieser Begriff keine Beziehung zu ob/Communication link hat. -> Frau Jahn

**Comment by KonradHoeffner** [comment]
Die haben tatsächlich keine Beziehung. Soll ich eine isAssociatedWith-Beziehung hinzufügen oder ist da etwas anderes gewünscht?

**Comment by AnnaLoerke** [comment]
done.

**Comment by AlfredWinter** [comment]
Es fehlt die Deutsche Übersetzung: Kommunikationsschnittstelle

**Comment by AnnaLoerke** [comment]
done.

Bitte für die Zukunft:
wenn Sie eine Anmerkung an ein geschlossenes Ticket anfügen, bitte das Ticket erneut öffnen, sonst wird es nicht bei den zu bearbeitenden Tickets angezeigt und die Anmerkung geht ggf. verloren.

**Comment by AlfredWinter** [comment]
o.k. Hatte ich mir schon gedacht, aber ich habe keine Button zum öffnen gefunden und dann gehofft, es öffnet sich durch das Anhängen des Kommentars von alleine. Wie öffne ich denn ein geschlossenes ticket wieder?
AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      +49 341-97-16107, 
Mobil: +49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
twitter: @MedizinischeL
instagram: medinfo.unileipzig
 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: AnnaLoerke [mailto:notifications@github.com] 
Gesendet: Mittwoch, 23. Januar 2019 09:47
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-ontology] http://www.snik.eu/ontology/ob/CommunicationInterface v0.3.0, 2016-11-18 (#56)
 
done.
Bitte für die Zukunft:
wenn Sie eine Anmerkung an ein geschlossenes Ticket anfügen, bitte das Ticket erneut öffnen, sonst wird es nicht bei den zu bearbeitenden Tickets angezeigt und die Anmerkung geht ggf. verloren.
