### ISSUE TITLE
http://www.snik.eu/ontology/meta/PatientCareEntityType v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#57]
The class http://www.snik.eu/ontology/meta/PatientCareEntityType has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
kein Meta!

**Comment by AlfredWinter** [comment]
Zumindest kein Core Meta

**Comment by KonradHoeffner** [comment]
Resolved by commit aa1ea276fc7f8a2fe0d8f2a92e9177a994f7565c.
