### ISSUE TITLE
http://www.snik.eu/ontology/ob/DelphiMethod v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#58]
The class http://www.snik.eu/ontology/ob/DelphiMethod has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Es gibt in OB auch ein Begriff "Delphi Study". Vermutlich ist das das selbe wie DelphiMethod. Beide Begriffe müssen zusammengeführt werden.
Gruß, AW

**Comment by KonradHoeffner** [comment]
DelphiMethod ist als Kreativitätstechnik auf Seite 64 definiert und DelphiStudie als Systemevaluationsmethode auf Seite 268, vielleicht sind die beiden doch unterschiedlich?

**Comment by AlfredWinter** [comment]
Definition ergänzen falls nötig.

**Comment by AnnaLoerke** [comment]
Die DelphiMethod ist schon definiert. Allerdings gibt es zur DelphiStudie auf Seite 268 nur einen Satz und es wird wieder in das Kapitel der DelphiMethod zurück verwiesen. Eventuell ist das doch gleich? Ich werde Rücksprache mit Franziska oder Birgit halten.

**Comment by FranziskaJahn** [comment]
Beide Begriffe aus OB zusammenführen unter "DelphiMethod".

**Comment by AnnaLoerke** [comment]
done.
