### ISSUE TITLE
http://www.snik.eu/ontology/ciox/Personalmanagement v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#59]
The class http://www.snik.eu/ontology/ciox/Personalmanagement has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Fehlermeldung beim Versuch, Descriptions aufzurufen:
404 
Oops! something went wrong
http://www.snik.eu/sparql
doesn't contain any information about
<http:​/​/​www.​snik.​eu/​ontology/​ciox/​Personalmanagement>

**Comment by KonradHoeffner** [comment]
CIOX ist aus Datenschutzgründen nicht im öffentlichen SPARQL Endpunkt und daher leider auch nicht im Lod View verfügbar. Ich überlege mir eine Lösung mit Passwortschutz.
