### ISSUE TITLE
Weiterentwicklung der Funktion "submit Ticket"

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#6]
Ist es möglich, bei der Wahl der Funktion "submit ticket" bei einer Klasse die Betreffzeile des Tickets gleich automatisch auszufüllen mit "Hinweis zur Klasse <name der Klasse>"?

Auch zu den Relationen sollte es die Möglichkeit geben, Tickets abzusetzen. 
AW

**Comment by KonradHoeffner** [comment]
Im Bitbucket geht das, daher konnte ich diese Funktionalität jetzt wieder aktivieren.
Es gibt übrigens auch einen Ticket-Tracker nur für die Visualisierung unter https://github.com/IMISE/snik-cytoscape.js da finde ich es schneller.
