### ISSUE TITLE
Filter, CIOx, ob

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#60]
Ich habe im Filter von den Ontologien nur CIOx ausgewählt. Es wird auch fast (!) nur CIOx angezeigt. Aber es werden auch einige orange Knoten angezeigt, die aber wahrscheinlich gar nicht zum ob aber auch nicht zum CIOx gehören. 
Z.B. "Research and Education Function" scheint aus dem bb zu stammen.

Bitte kontrollieren
aW

**Comment by AlfredWinter** [comment]
Habe noch etwas mehr Klarheit erreicht: Die oben genannten orangen Knoten wie z.B. "Research and Education Function" bleiben genau dann angezeigt, wenn im Filter alle Ontologien abgewählt wurden. offenbar gehören diese Knoten zu nichts. Bitte alle diese Knoten überprüfen.

**Comment by KonradHoeffner** [comment]
Ich schätze mal, dass da Definitionsaussagen der Unterontologien fehlen (also z.B. "meta definiert ResearchAndEducationFunction" fehlt). Ich kümmere mich darum.

**Comment by KonradHoeffner** [comment]
Müsste jetzt behoben sein.
