### ISSUE TITLE
http://www.snik.eu/ontology/ciox/ExcelFile v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#61]
The class http://www.snik.eu/ontology/ciox/ExcelFile has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
was ist das???

**Comment by KonradHoeffner** [comment]
`ciox:ExcelFile` wird als Dateiformat von Dokumenten in CIOX benutzt. Ist das OK so oder soll ich da etwas ändern?

**Comment by AlfredWinter** [comment]
Besprechung 18.12. Herr Winter hat gesagt "ist erledigt"
