### ISSUE TITLE
"http://www.snik.eu/ontology/ciox/Etat" ("http://purl.org/dc/terms/format") http://www.snik.eu/ontology/ciox/ExcelFile v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#62]
The edge ""http://www.snik.eu/ontology/ciox/Etat" ("http://purl.org/dc/terms/format") http://www.snik.eu/ontology/ciox/ExcelFile" is incorrect.

**Details**
Was ist "format"?? Das gibt es nicht als Kantentyp.

**Comment by KonradHoeffner** [comment]
Die Relation "format" habe ich aus dem Dublin Core Vokabular genommen, da es weit verbreitet ist und in diesem Fall gut zu passen scheint. Definition von dc:format: "The file format, physical medium, or dimensions of the resource.".

**Comment by KonradHoeffner** [comment]
This edge does not exist anymore.
