### ISSUE TITLE
"http://www.snik.eu/ontology/ciox/Projekt" ("http://www.snik.eu/ontology/ciox/Kurzbeschreibung") http://www.w3.org/2001/XMLSchema#string v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#63]
The edge ""http://www.snik.eu/ontology/ciox/Projekt" ("http://www.snik.eu/ontology/ciox/Kurzbeschreibung") http://www.w3.org/2001/XMLSchema#string" is incorrect.

**Details**
"Kurzbeschreibung" ist keine zulässige Kante

**Comment by KonradHoeffner** [comment]
Wurde wie gewünscht entfernt.
