### ISSUE TITLE
http://www.w3.org/2001/XMLSchema#string v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#64]
The class http://www.w3.org/2001/XMLSchema#string has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Was ist das? Gehört nicht in die Ontologie

**Comment by KonradHoeffner** [comment]
Das ist der Datentyp für Zeichenketten und gehört damit Standardvokabular, das von der Ontologie verwendet wird. Taucht es denn in der Visualisierung auf? Dort gehört es wirklich nicht hin. Wenn ja, können Sie beschreiben, wo man es findet? Mit einer Suche nach "string" taucht es nicht auf.

**Comment by KonradHoeffner** [comment]
I will close this for now, please reopen if it occurs again.
