### ISSUE TITLE
http://www.snik.eu/ontology/ciox/Projektmanagement v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#72]
The class http://www.snik.eu/ontology/ciox/Projektmanagement has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
das ist nicht das sich das Blaue Buch un deas Orange Buch unter Projektmanagement vorstellen. Daher muss eine Relation  des neuen Relationstyps "sounds similar but is different" zum  Projektmanagement im bb und im ob hier modelliert sderden. Dann müssen die Gründe dafür als Kommentar in der Beziehung abglegt werden.

**Comment by KonradHoeffner** [comment]
Umgeändert zu meta:hyponym. Keine commit referenz hier da im ciox repository auf bitbucket.
