### ISSUE TITLE
http://www.snik.eu/ontology/he/Lizenzmanagement

### ISSUE THREAD

**Issue by EwaldRode** [IMISE/snik-ontology#73]
Definition consists of a short text copy-pasted 9 times [http://www.snik.eu/ontology/he/Lizenzmanagement](http://www.snik.eu/ontology/he/Lizenzmanagement).

**Comment by BirgitSNIK** [comment]
Never read this passage before. Take 8 copies out.

**Comment by KonradHoeffner** [comment]
Ah das ist ja im Heinrich, daher müsstest du das in der Extraktionstabelle ändern, @BirgitSNIK.

**Comment by BirgitSNIK** [comment]
Ist die #73 jetzt erledigt?
Sorry ich hab da den Überblick verloren.
Birgit
 
Von: Konrad Höffner [mailto:notifications@github.com] 
Gesendet: Montag, 24. April 2017 12:13
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: BirgitSNIK <birgit.schneider@imise.uni-leipzig.de>; Mention <mention@noreply.github.com>
Betreff: Re: [IMISE/snik-ontology] http://www.snik.eu/ontology/he/Lizenzmanagement (#73)
 
Assigned #73 to @BirgitSNIK.

**Comment by AnnaLoerke** [comment]
done.
