### ISSUE TITLE
http://www.snik.eu/ontology/bb/ChiefInformationOfficer v0.3.0, 2016-11-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#75]
The class http://www.snik.eu/ontology/bb/ChiefInformationOfficer has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Abkürzung "CIO" fehlt. Langtext "Chief Informations Officer" zu "Chief Information Officer"

**Comment by KonradHoeffner** [comment]
In der aktuellen Version ist die Abkürzung bereits enthalten.
