### ISSUE TITLE
http://www.snik.eu/ontology/ob/Knowledge (http://www.snik.eu/ontology/meta/isDecomposedIn) http://www.snik.eu/ontology/ob/Data v0.3.3, 2017-04-13

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#77]
The edge "http://www.snik.eu/ontology/ob/Knowledge (http://www.snik.eu/ontology/meta/isDecomposedIn) http://www.snik.eu/ontology/ob/Data" is incorrect.

**Details**
Data ist nicht decomposed in Knowledge. Data repräsentiert Knowledge. Da bleibt also nur ein "associated" Beziehung übrig.

**Comment by KonradHoeffner** [comment]
Hierbei sieht es etwas merkwürdig aus eine OWL restriction zu verwenden, da müsste man generell nochmal überlegen, ob man meta:isAssociatedWith vielleicht direkt auf Klassenbasis verwendet.
