### ISSUE TITLE
http://www.snik.eu/ontology/ob/Knowledge (http://www.snik.eu/ontology/meta/isDecomposedIn) http://www.snik.eu/ontology/ob/Data v0.3.3, 2017-04-13

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#78]
The edge "http://www.snik.eu/ontology/ob/Knowledge (http://www.snik.eu/ontology/meta/isDecomposedIn) http://www.snik.eu/ontology/ob/Data" is incorrect.

**Details**
Data ist nicht decomposed in Knowledge. bitte Löschen

(Data repräsentiert Knowledge. Da bleibt dann die"associated" Beziehung übrig.)

**Comment by KonradHoeffner** [comment]
Duplikat von issue #77. Bereits erledigt in commit 9e416d0f756b2e0ebc6683803c7c4e4b3c2b8d27.
