### ISSUE TITLE
http://www.snik.eu/ontology/ob/InformationAndKnowledgeLogistics (http://www.w3.org/2000/01/rdf-schema#subClassOf) http://www.snik.eu/ontology/ob/InformationManagement v0.3.3, 2017-04-13

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#85]
The edge "http://www.snik.eu/ontology/ob/InformationAndKnowledgeLogistics (http://www.w3.org/2000/01/rdf-schema#subClassOf) http://www.snik.eu/ontology/ob/InformationManagement" is incorrect.

**Details**
Beziehung stimmt nicht. löschen

**Comment by KonradHoeffner** [comment]
Habe es gelöscht aber es hatte keine andere Oberklasse und keine sub top class, daher habe ich für beides meta:Function angegeben. Falls das falsch sein sollte bitte das Ticket wieder öffnen und sagen, was es sein soll.
