### ISSUE TITLE
http://www.snik.eu/ontology/bb/HumanResourceManagement v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#93]
The class http://www.snik.eu/ontology/bb/HumanResourceManagement has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
decomposed in : auch zu sich selber. Das ist aber falsch. Löschen.

**Comment by KonradHoeffner** [comment]
Das ist im SPARQL Endpunkt und im Repository bereits behoben aber die Visualisierung zeigt noch den alten Stand.
