### ISSUE TITLE
http://www.snik.eu/ontology/bb/CertifiablePhysicalDataProcessingSystem v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#95]
The class http://www.snik.eu/ontology/bb/CertifiablePhysicalDataProcessingSystem has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Schreibfehler: Im Label nicht "certifiabile" sondern "certifiable"

**Comment by AlfredWinter** [comment]
Der Fehler ist aber immer noch da …  http://www.snik.eu/ontology/bb/CertifiablePhysicalDataProcessingSystem 
AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      ++49 341-97-16107, 
Mobile: ++49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Konrad Höffner [mailto:notifications@github.com] 
Gesendet: Montag, 19. Juni 2017 17:06
An: IMISE/snik-ontology <snik-ontology@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-ontology] http://www.snik.eu/ontology/bb/CertifiablePhysicalDataProcessingSystem v0.3.3, 2017-04-18 (#95)
 
Closed #95 via aafb72e.

**Comment by KonradHoeffner** [comment]
Es ist noch nicht im SPARQL Endpunkt, wird aber in Kürze auch dort aktualisiert.

**Comment by KonradHoeffner** [comment]
Jetzt ist es auch im SPARQL Endpunkt geändert.
