### ISSUE TITLE
http://www.snik.eu/ontology/bb/Patient (http://www.snik.eu/ontology/bb/case) http://www.snik.eu/ontology/bb/Case v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#97]
The edge "http://www.snik.eu/ontology/bb/Patient (http://www.snik.eu/ontology/bb/case) http://www.snik.eu/ontology/bb/Case" is incorrect.

**Details**
Der Beziehungstyp "case" kommt nicht im Meta-Modell vor.

**Comment by FranziskaJahn** [comment]
Siehe #98
