### ISSUE TITLE
http://www.snik.eu/ontology/bb/Patient v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-ontology#98]
The class http://www.snik.eu/ontology/bb/Patient has [incorrect/missing attribute values | incorrect/missing relations to other classes, other (please specify and remove not applicable ones).]

**Details**
Die Relationen "admitting patient", "case" and "relative" gibt es nicht im Metamodell. Muss das nicht korrigiert werden? Wie gehen wir mit diesen Beziehungen um? Ich möchte dadrüber sprechen.

**Comment by KonradHoeffner** [comment]
Die drei Relationen sind zwar nicht im Metamodell aber alle in der bb-Ontologie sauber definiert mit domain und range. "relative" zum Beispiel ist am 1.11.2016 dazugekommen, siehe https://github.com/IMISE/snik-ontology/commit/9b926124e7ee0865e8be1294bf586003c49aa0e5#diff-e16d2bfaed5a8726bc643bba65fd112f. Ich habe leider keine Propertytabelle vom blauen Buch um zu sehen, wo das ursprünglich herkommt, da die ja schon konvertiert war als ich angefangen habe aber Heinrich hat ja z.B. auch eine separate Tabelle mit eigenen Properties.

**Comment by AlfredWinter** [comment]
Bitte bei nächster Besprechung besprechen.
AW

**Comment by FranziskaJahn** [comment]
Wir hatten im Blauen Buch an einigen Stellen owl data properties (Eigenschaften einer Klasse, d.h. Verbindungen zwischen Individuals und Literalen) definiert, diese sind jedoch im Graph genauso dargestellt wie owl object properties (unsere Relationstypen laut Metamodell), das verwirrt natürlich.  
Können wir am Freitag besprechen.

**Comment by KonradHoeffner** [comment]
Data properties sind im graph gar nicht dargestellt, weil wir keine Anzeige von Literalen haben und damit auch keine Verbindungen zwischen Literalen und Klassen.

**Comment by FranziskaJahn** [comment]
Ich glaube, wir hatten irgendwann als "Behelfslösung" diese data properties als object properties modelliert, damit diese im Graphen nicht verlorengehen?!

**Comment by KonradHoeffner** [comment]
Franziska und ich haben das gerade besprochen, wir schlagen vor, die data properties in object properties umzuwandeln und je eine meta property als superproperty festzulegen, dann wird implizit das meta modell verwendet und die Zusatzinformation geht trotzdem nicht verloren.

**Comment by AlfredWinter** [comment]
Ersetzen durch "isAssociatedWith"

**Comment by AnnaLoerke** [comment]
done.
