### ISSUE TITLE
http://www.snik.eu/ontology/bb/HisStakeholder (http://www.w3.org/2000/01/rdf-schema#subClassOf) http://www.snik.eu/ontology/bb/InformationManagementEntityType v0.3.3, 2017-04-18

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#99]
The edge "http://www.snik.eu/ontology/bb/HisStakeholder (http://www.w3.org/2000/01/rdf-schema#subClassOf) http://www.snik.eu/ontology/bb/InformationManagementEntityType" is incorrect.

**Details**
Unterklasse ist Rolle, Oberklasse ist Objekttyp.

**Comment by AnnaLoerke** [comment]
Die Verbindung existiert gar nicht mehr. Daher wird das Ticket nun geschlossen.
